XIVComboExpanded/Combos/SGE.cs
Fixed SageDPSFeature to work for all levels of Dosis with a level check.
=> Fixed SageDPSFeature to include Dosis at all levels

XIVComboExpanded/Combos/RPR.cs, XIVComboExpanded/CustomComboPreset.cs
Added feature requested in #36 (I think. At least that's what I thought was being requested.) Makes Blood Stalk turn into Gluttony when off-CD and turns into Gibbet/Gallows when used (so all in 1 button). Same with Grim Swathe.
As an aside, I had to build in the GrimSwatheFeature as I figured if people want a 1 button rotation for Blood Stalk -> Gibbet/Gallows they'd want the same for Grim Swathe -> Guillotine. The Feature doesn't differentiate between if the Gluttony is being used for AoE or ST so I had to break it up. So, up to you guys if you want to remove the feature in lieu for the built in option here.
=> Added Blood Stalk and Grim Swathe Combo features as requested

XIVSlothCombo/Combos/SMN.cs
Level sync fix for Searing Light one button combo (need to be level 66 or greater, wasn't working while sub 66)
Also fix for one button combo egi summons, was returning summon titan (I) instead of summon titan II at level 90 and was nonfunctional.
Also fixed one button combo for pre-bahamut level sync, had summon bahamut when you couldn't click it.
Unsure if I did this entirely correctly but it does seem to work fine in-game when testing at sub 66 for searing light, and sub 30/post 30 for carbuncles and egis.
=> SMN One button combo level sync fixes

XIVSlothCombo/Combos/RPR.cs, XIVSlothCombo/CustomComboPreset.cs
Added Cross/Void Reaping + Communio to BloodSwathe Option as requested in #76.
Redoing my PR because I'm stupid and I forgot to do checks for Enhanced Cross/Void Reaping.
=> Add RPR Enshrouded Combos to BloodSwathe Option

XIVSlothCombo/Combos/WAR.cs, XIVSlothCombo/CustomComboPreset.cs
Added the option for the ST/AoE Combos to use their spenders at 50 instead of at overcap with level checks. As well as, adding Chaotic Cyclone to the AoE combo when the Inner Chaos Option is ticked.
=> Fell Cleave/Decimate Option + Edit to Inner Chaos Option

XIVSlothCombo/Combos/RPR.cs
Should fix the issue in #86. I've tested it starting it on both Void or Cross Reaping and it hasn't broken yet so it should be good now.
=> Fixed Enshroud Combo breaking if started manually

XIVSlothCombo/Combos/AST.cs, XIVSlothCombo/Combos/SCH.cs, XIVSlothCombo/Combos/SGE.cs, XIVSlothCombo/Combos/WHM.cs
Took a look at the Dev Console errors from #97 and realised half the conditions are just repeating themselves such as the level checks so just cleaned it up. Also streamlined it because you can get remaining time from FindTargetEffect and also do the same thing as TargetHasEffect with a null check.
Anyway, with those changes it's stopped throwing errors in my log, so hopefully that fixes the issue.
=> Cleaned up Healer DPS code/Pretty sure it fixes the errors in the dev console

XIVSlothCombo/Combos/BRD.cs
Makes the BardSimpleAoEFeature class a lot DRY'er
surrounding conditionals for repeated checks, creating a single variable for said check
moved level checking to be in the beginning to save on method calls if playing lower level content
removed unnecessary braces in some if statements
introduced braces in some if statements to increase readability
removed duplicate GetJobGauge calls
Let me know if this is OK, I will do the same to SimpleBardFeature if you like what I've done here :)
Thanks!
=> chore: dry-ify BardSimpleAoEFeature class

XIVSlothCombo/Combos/BRD.cs
#119 Optimises BRD's SimpleSongOption to use timings based on The Balance (and the Issue's) advice.
I have tested it in-game, the rotation did have to be a slightly longer Ballad otherwise you would end up with no song on for a few seconds whilst Minuet was on CD.
The rotation goes as;
43-ish seconds of Minuet
35-ish seconds of Ballad
43-ish seconds of Paeon
I have also put an initial song check in, so that if songs are used on the AOE option or individually on pulls in dungeons, it won't affect the rotation too much. (It'll just pick up where it can, and go into the rotation asap).
I have also put it around a Minuet level check, because optimising when you're under that level is a bit pointless.
=> feat: optimise BRD SimpleSongOption song usage

XIVSlothCombo/Combos/WAR.cs
When using infuriate, if you use fell cleave instead of chaotic cyclone pre-80 your aoe combo button becomes unusable until you get gauge required for chaotic cyclone.
This change makes your aoe combo default back to overpower until you get gauge.
=> Adds a gauge check to Chaotic Cyclone

XIVSlothCombo/Combos/MCH.cs, XIVSlothCombo/Combos/WAR.cs, XIVSlothCombo/CustomComboPreset.cs
Fixed OnslaughtOptionTwo and adjusted description. Now leaves 1 charge below 88.
Moved Orogeny combo up, so it will activate in time with Upheaval. Will still wait for Storm's buff
Attempt at cleaning up my ugly formatting
=> Warrior fixes

XIVSlothCombo/Combos/WAR.cs
If you use Infuriate without surging tempest buff or lose surging tempest before you can use inner chaos, and then gain surging tempest while still having Nascent Chaos buff active, your single target combo becomes unusable due to no gauge.
=> Added same gauge check for inner chaos.

XIVSlothCombo/Combos/BRD.cs, XIVSlothCombo/CustomComboPreset.cs
Adds health checking to SimpleBard functionalities, such as buffs, songs and DOTs.
Adds a new feature toggle "BardSimpleRaidMode" (219), allowing users to override these health checks in raids, as boss %'s are usually still high at 1% (and you still want to use literally everything at that % in a raid). This lets dungeon running and raiding have slightly different functionalities, as you don't want to go using your song or buffs for half a second of boss HP in dungeons.
=> feat(BRD): add health checking and raid toggle

XIVSlothCombo/Combos/BRD.cs, XIVSlothCombo/CustomComboPreset.cs
Another small little addition to BRD's SimpleBard Single Target rotation.
Uses interrupt if applicable, also with toggle for convenience if people would like to interrupt manually :)
=> feat(BRD): simple interrupt

XIVSlothCombo/Combos/BLU.cs, XIVSlothCombo/CustomComboPreset.cs
Added an option to add the primals to Final Sting so I can toggle it on and off between doing it for raids or 1-shotting ARR primals for Wondrous Tails.
=> Blu Final Sting Adjustments

XIVSlothCombo/Combos/GNB.cs, XIVSlothCombo/CustomComboPreset.cs
Complete overhaul of GNB including features asked for in #141 (who even did the original because that was rough).
Features added:
- Added Gnashing Fang, Continuation, Double Down, Bow Shock, Sonic Break, Blasting Zone/Danger Zone, Rough Divide into main combo. Gnashing Fang will need to be started manually (as requested in the #141) in order for users to have more control during unfortunate phase change timing. These abilities are modular for increased choice in the main combo
- Overcap features for both ST and AoE
- No Mercy Rotation on No Mercy: Added the full Gnashing Fang/DD/oGCDs/Continuation burst into No Mercy.
=> GNB Overhaul

XIVSlothCombo/Combos/GNB.cs, XIVSlothCombo/CustomComboPreset.cs
Added Burst Strike/Hypervelocity to the end of the No Mercy windows as requested in #141.
Added the burst rotation on to Gnashing Fang.
Fixed issue where DD wouldn't trigger at 3 ammo.
=> Added more GNB features

XIVSlothCombo/Combos/BRD.cs
little tweak to fix the reset and to also shore-up the usedStraightShotReady checks to move to next steps.
=> fix: brd opener reset and shore up burst shots

XIVSlothCombo/Combos/BRD.cs
Adds pitch perfect to simple bard opener (in a good few places due to the random nature of the song)
Adds better bloodletter charge detection based on CD
Adds a opener override on Simple Bard ST if you used Simple Bard AOE first. (To assist with trash clearing).
=> chore: upgrade simple brd opener with protections and pitch perfect

XIVSlothCombo/Combos/MNK.cs
Adjusted L80 due to some funkiness with gauge spender, aoe gauge spender works as expected after change.
Cleaned up L97 to be more like its single target equivalent, adjusted level due to MNK having a aoe gauge spender at 40
Adjusted L128-L136, Mnk was not currently able to generate a solar nadi the way it was set up even though they can do it no problem, moved solar nadi from "high level" to low level for ease of reading and adjusted level check, it works as expected lv60+.
Adjusted L255 level check, MNK gets a single target gauge spender at lv15.
Fairly sure everything works right as I've been leveling mnk with these changes, feel free to make any comments/edits if things are wrong.
=> [MNK] Adjustments for low level/level sync and cleanup.

XIVSlothCombo/Combos/MNK.cs
Moved the gauge spender code above the 1-2-3 to mirror the single target version.
Howling Fist/Enlightenment now appears properly when GCD is on cooldown just like Forbidden Chakra for single target.
Tested in Zadnor, my mnk isn't above 80 yet.
=> [MNK] Believe I've resolved the AOE gauge spender issue.

XIVSlothCombo/Combos/MNK.cs, XIVSlothCombo/CustomCombo.cs
Mnk is one of the few classes that are able to aoe without a target, due to this as its currently set up there are small windows in which they can't use an ability that requires a target.
I'm not 100% sure if this existed already but I've added a check to see if the player has a battle target.
From what I can tell it works as expected, returns the 1-2-3 combo if you don't have a target, otherwise shows gauge spender.
=> Added target check to MNK aoe combo.

XIVSlothCombo/Combos/BRD.cs, XIVSlothCombo/CustomComboPreset.cs
Pools bloodletter charges during AP, uses them during burst window of raging strikes on WM. 
#189
=> feat(BRD): simple bard bloodletter pooling toggle

XIVSlothCombo/Combos/BLM.cs, XIVSlothCombo/CustomComboPreset.cs, XIVSlothCombo/XIVSlothCombo.csproj
Change Scathe to Fire 3 when MP is maxed, in Umbral Ice and with 3 Umbral Hearts.
Change Scathe to Blizzard 3 when MP is 0 and in Astral Fire.
Change Scathe to Blizzard 3 when MP is below 1600 and in Astral Fire at low levels.
Change Freeze to be cast only when MP is below 10000 in Umbral Ice at low levels since Umbral Hearts aren't granted.
Tested changes locally and should be fine, but feel free to make comments.
=> [BLM] Update to all-in-one rotation and aoe for level sync

XIVSlothCombo/Combos/BRD.cs
Fixes #208 issue wherein the pitch perfect of first branch was triple weaving.
=> fix: tripple weaving on pitch perfect in first branch of opener

XIVSlothCombo/Combos/MNK.cs, XIVSlothCombo/CustomComboPreset.cs, XIVSlothCombo/XIVSlothCombo.csproj
Wanted the Twin Snakes/True Strike swapping function as a standalone.  It should swap the skill regardless of form/pb, the only checked variables being level and Disciplined Fist duration. Set the duration to < 6 seconds to future-proof skillspeed and accommodate people who gotta go fast (potential to get fancy with actual skillspeed math but I don't wanna)
resolves #221
=> Added a new MNK CustomCombo for Twin Snakes

XIVSlothCombo/Combos/MNK.cs, XIVSlothCombo/CustomComboPreset.cs
Just a feature I had thought of since you should always be using both when both are ready to keep cooldowns aligned (60s/120s)
If anybody has any suggestions, I'd more than welcome them.
=> Added feature to replace riddle of fire with brotherhood when on CD

XIVSlothCombo/Combos/MNK.cs, XIVSlothCombo/CustomComboPreset.cs
Added two subfeatures for Basic Combo Plus, adjusted some ogcd timings for clipping.
MainComboBuffsFeature puts damage buffs onto main combo when PB is active.
MnkRiddleOfWindFeature puts Riddle of Wind on main combo after twin snakes to maximize gains from it.
Both features entirely optional.
=> Added features for damage buffs on main combo (Basic Combo Plus)

XIVSlothCombo/Combos/RPR.cs
- Puts ShadowOfDeath up in priority
- Fixes issue with ShadowOfDeath not being casted between certain combos
=> Reaper ReaperSliceCombo Changes

XIVSlothCombo/Combos/NIN.cs, XIVSlothCombo/CustomComboPreset.cs
Greetings,
- Implement a preset for casting ninjutsu without failing
- semi-auto
- Lv1 should still be called with ninjutsu.
- Lv2 can be casted with ninjutsu or any of the other 2 mudras , they will change to ninjutsu to avoid miscast.
- Lv3 should make all mudras change to the ninjutsu.
- should solve #266 
-  1st example, will try to make the 2nd example later.
- During my tests I have not met any, but feedback will be necessary for the high lv special ninjutsu's , lv76+ , since my ninja is not that high xD
Fun fact
The mudras are oGCDs disguised as GCDs, and you cant track them at all after the initial state, you have to track the ninjutsu that come from using the "combo" mudras.
ps: I need to rebase my fork , the commit list is starting to get out of hand >.>
=> NIN Simple Mudra 

XIVSlothCombo/Combos/BRD.cs, XIVSlothCombo/Combos/MNK.cs, XIVSlothCombo/XIVSlothCombo.csproj
Hello,
- Raised the priority of refreshing/casting dots on simple bard in relation to Apex/Blast Arrow
- Noticed it sometimes while raiding this week, if the timing of use of Apex came right when I needed to refresh the dots, the way it was  the apex arrow was gonna cast and dots would fall off because it would immediately try to blast arrow , and not cast an IJ like it does because AA and BA had priority over the dots.
- This makes that in that case it'll still cast apex , but will do an IJ between ApexA and BlastA
- Changing the way a var is created in the MnkAoeCombo section to avoid the following error:
@Iaotle This time I bumped the version :P
=> [BRD] - Simple bard priority of dots; [MNK] - bug fix 

XIVSlothCombo/Combos/RPR.cs
Hi!
I've faced an issue with RPR job: when downsynced to lvl 50 and enabled option "Soul Slice Feature" or "Soul Scythe Feature" main combo (or main aoe combo) becomes unusable because it transforms to Soul Slice/Soul Scythe which cannot be used at that level
Picture for attracting attention xD
=> RPR add level check for SoulSlice/SoulScythe

XIVSlothCombo/Combos/BRD.cs, XIVSlothCombo/Combos/RDM.cs, XIVSlothCombo/ConfigWindow.cs, XIVSlothCombo/CustomComboPreset.cs, XIVSlothCombo/PluginConfiguration.cs, XIVSlothCombo/XIVSlothCombo.csproj
Hello
- Simple Bard
- Most notable:
-  Added an option in the config window to customize the time which the snapshot happens relative to the remaining time of raging strikes.
- Had the need to change that when using different attack skill spds, the reasoning behind it was that i had to change it almost every time i changed my threshold to avoid clipping etc @_@
- Tweak on the opener to make compatible with lv80+ instead of only lv 90.
- Tweak on pooling feature of BLs inside AP, start pooling at 30s on the song, to squeeze a little more dps.
The custom time config , can be extended to any jobs that need a custom time for anything. I looked out on the other jobs that did something similar, but all of them shared the same variable , so changing the config in one changed on the other …
=> [BRD] Couple tweaks to Simple Bard and RagingJaws features;

XIVSlothCombo/Combos/BLM.cs
Correct BLM levels.
Update BLM to cast Thunder/Thunder3 only if enough MP.
Update BLM to cast Fire3 when in Umbral Ice and max MP pre-Fire4.
Update BLM to cast Blizzard when in Umbral Ice and pre-Blizzard4.
=> BLM Level Sync Fixes

XIVSlothCombo/Combos/DNC.cs, XIVSlothCombo/CustomComboPreset.cs
- Moved SS priority above TS (just for steps, not beginning/end of dances)
- Removed SimpleDanceFeature and replaced with SimpleStandardFeature and SimpleTechnicalFeature.
- Split DancerSimpleBuffs into DancerSimpleDevilmentFeature and DancerSimpleFlourishFeature.
- Added (HasEffect(DNC.Buffs.TechnicalFinish) to Devilment feature.
When enabled and at level, Devilment should now only trigger on the main rotation if off cooldown and under the effect of Technical Finish.
- Split DancerSimpleShieldNHealsFeature into DancerSimpleSambaFeature, DancerSimplePanicHealsFeature and DancerSimpleImprovFeature.
Set HP thresholds for Curing Waltz and Second Wind to 30% and 50% respectively, with the intention of Waltz being used manually before hitting the threshold, but available as a backup heal, and …
=> [DNC] Simple Dancer Additions

README.md, XIVSlothCombo/Combos/RPR.cs, XIVSlothCombo/CustomComboPreset.cs, XIVSlothCombo/XIVSlothCombo.csproj
- Fixed AoE combo breaking when using combo options #301
- Updated names and descriptions for most features/options
- Re-organised everything into categories of relevance whilst retaining function (the list was getting a bit long)
- Re-assigned all skill IDs (or whatever they're called) to reflect new categories and sort order, with space made for future additions
- Changed bits of level check code to reference `Levels` class
- Added HP% check for Shadow/Whorl of Death Features (no longer applies if target is <5% HP)
- Will consider bumping this to 10% on Whorl of Death after some dungeon testing
- Added `ReaperStunOption` (Leg Sweep into single target combo when target can be interrupted)
- Added `ReaperComboHealsOption` (Second Wind and Bloodbath into single target combo)
- Added …
=> [RPR] Features & Fixes

XIVSlothCombo/Combos/SCH.cs, XIVSlothCombo/Combos/SGE.cs, XIVSlothCombo/CustomComboPreset.cs
[SCH]
- Added all skills from Lv20 - 90 to `Levels` class
- Reorganised skill IDs into relevant sections
- Made all level checks use `SCH.Levels` class
- Removed `var gauge = GetJobGauge<SCHGauge>();` from DPS feature (it doesn't read gauge at the moment anyway)
- Replaced some weave-related functions with `canWeave` for better reliability
- Killed all `&& level >= 2` code. Just don't use Sloth at level 1, dingus
- Renamed occurrences of `biosys` and `biolysys` to `biolysis`
- *Reading the word 'biolysis' a thousand times tonight has given me an aneurysm. You're welcome.*
[SGE]
- Added `Eukrasia` and `Toxikon` to skill IDs and `Levels` class
- Made all level checks use `SGE.Levels` class
=> [SCH, SGE] Features & Fixes

XIVSlothCombo/Combos/MCH.cs, XIVSlothCombo/CustomCombo.cs
- Implemented a way to keep track of combat duration.
- `CombatEngageDuration()` return a `TimeSpan`
- Simply call `CombatEngageDuration().Seconds`, `CombatEngageDuration().Minutes` or `CombatEngageDuration().TotalSeconds` , etc,
=> Implementation of Combat Time Duration tracking

XIVSlothCombo/Combos/DRK.cs
Should fix issue #348 by only using Abyssal drain below 60% health, instead of above 60% health
=> Abyssal drain now gets used at <60% health instead of >60% health

XIVSlothCombo/Combos/NIN.cs, XIVSlothCombo/ConfigWindow.cs, XIVSlothCombo/ConfigWindowFunctions.cs, XIVSlothCombo/PluginConfiguration.cs
Fixes NIN simple single target kassatsu buff messing up trick window. Made it optional.
=> NIN bug fixes plus hide conflicted combos button

XIVSlothCombo/Combos/DRK.cs, XIVSlothCombo/Combos/PLD.cs, XIVSlothCombo/CustomComboPreset.cs
Makes Blood Gauge Overcap Feature a toggle option instead of on by default. Someone mentioned this yesterday on Discord so I figured it'd be a nice way to test if I could figure out how to add options.
Also changed hardcoded DRK levels
#355 PLD suggestion added as well: Changed Low blow to Shield bash, made it so Interject is used first if enemy is interruptable, Low Blow if it's off cooldown, and otherwise Shield Bash if both don't apply.
=> [DRK] Blood Gauge Overcap Feature [PLD] Interrupt/Low blow/Shield Bash onto one button

XIVSlothCombo/Combos/AST.cs, XIVSlothCombo/CustomComboPreset.cs
Adds Lady of Crowns, to aoe heals if the card is drawn and player is in combat.
Priority: Lady of Crowns > Celestial Opposition (if enabled) > Aspected Helios > Helios
(fixed the level check just for this feature)
=> [AST] Lazy Lady feature

XIVSlothCombo/Combos/ALL.cs, XIVSlothCombo/Combos/GNB.cs, XIVSlothCombo/Combos/WAR.cs, XIVSlothCombo/CustomComboPreset.cs
- Fixed issue in #347 
- Minor GNB Refactoring
- WAR Refactoring (and fixes for level checks)
- Made Inner Chaos Option and Fell Cleave/Decimate Option mutually exclusive
- Removed Fellcleave/IB Feature as the Overcap Feature makes it obsolete
- Removed Berserk Condition when under level 70 for Upheaval Feature
=> GNB and WAR Refactoring and fixes

XIVSlothCombo/Combos/BLM.cs, XIVSlothCombo/CustomComboPreset.cs
Removed additional features on enochain stance switcher and moved them over to Simple BLM
Simple BLM contains options for keeping 1 triplecast stack and keeping 1 polygot.
=> Simple BLM + Opener.

XIVSlothCombo/Combos/GNB.cs, XIVSlothCombo/CustomComboPreset.cs
Removed No Mercy Feature
Added Gnashing Fang Starter to Main Combo, No Mercy on Main Combo, Bloodfest on Main Combo (With all Main Combo options turns into a one button rotation)
Minor timer changes to make a one button rotation flexible.
=> GNB: Full One button rotation support

XIVSlothCombo/Combos/WAR.cs, XIVSlothCombo/ConfigWindow.cs, XIVSlothCombo/CustomComboPreset.cs
I saw someone else mention that the duration was long, but personally, I like it longer.  So I thought I'd get a little practice doing a user defined slider.
-Added User Defined Slider input to seconds remaining before refreshing Surging Tempest.
-Added User Defined Slider input to number of Onslaught charges to keep.
-Removed Onslaught Option and Option 2 (Commented out) as they were made redundant by the previous change.
=> User Defined Sliders: Surging Tempest & Onslaught (with feature clean up)

XIVSlothCombo/Combos/RDM.cs, XIVSlothCombo/ConfigWindow.cs, XIVSlothCombo/CustomComboPreset.cs
In response to: https://github.com/Nik-Potokar/XIVSlothCombo/issues/355
Added Lucid Dreaming Option to RDM with a user adjustable MP Level.  Added to all 2 second spells when you can weave only.
=> Lucid Dreaming Option on RDM with User Input

XIVSlothCombo/Combos/WAR.cs, XIVSlothCombo/ConfigWindow.cs, XIVSlothCombo/CustomComboPreset.cs
Couple of things to get Primal Rend working and some clean-up.
- Fixed InnerRelease actionID number (8768 > 7389)
- Added Primal Rend on Inner Release option
- Removed extra spaces in ConfigWindow.cs to make it ★pretty★
In response to me believing that option was always there and https://github.com/Nik-Potokar/XIVSlothCombo/issues/278
=> Primal Rend on Inner Release

XIVSlothCombo/Combos/AST.cs, XIVSlothCombo/CustomComboPreset.cs
- Essential Dignity and Celestial Intersection will now use all charges available.
- Added Aspected Benefic to single target heals. Applies and refreshes the buff if necessary.
- Aspected Helios and Aspected Benefic will apply their shields while under Neutral Sect.
If the shield is applied Aspected Helios and Aspected Benefic will turn into Helios & Benefic
If the shield breaks it will re-apply it.
=> [AST] Enhancements

XIVSlothCombo/Combos/NIN.cs, XIVSlothCombo/ConfigWindow.cs, XIVSlothCombo/ConfigWindowFunctions.cs
Adds level check to under level 76 starter mudra.
Also adds checks for child conflicted combos on the hide feature plus a new shiny "joyn deescorduh" button.
Oh, and radio buttons I guess.
=> Should fix #407

XIVSlothCombo/Combos/DRK.cs, XIVSlothCombo/Combos/GNB.cs, XIVSlothCombo/Combos/WAR.cs, XIVSlothCombo/CustomCombo.cs, XIVSlothCombo/CustomComboPreset.cs
GNB: Simple GNB should work for all levels now
GNB: Minor syntax fix
WAR: Fixed infuriate persisting outside of combat
WAR: Spender Option fix
DRK: Refactoring
DRK: Renamed DeliriumFeatureOption to DelayedDeliriumFeatureOption and moved it under DeliriumFeature as a child combo. Refactored to avoid conflicts.
DRK: Added DarkBloodWeaponOpener
Framework: Added GetBuffRemainingTime as a quicker call for FindEffect(actionID).Remaining Time
=> GNB: All level functionality

XIVSlothCombo/Combos/SGE.cs, XIVSlothCombo/ConfigWindow.cs, XIVSlothCombo/CustomComboPreset.cs
Customizable Single Target Heal
The user can create a custom skill priority by adjusting the HP% values.
Some features only work if there is a target selected
- Adds Kardia to the selected target if absent
- Adds Eukrasian Diagnosis when the target's HP reaches the specified percentage; 
- Eukrasian Shield is only applied if the target selected doesn't have the shield applied.
- Adds Soteria Diagnosis when the target's HP reaches the specified percentage.
- Adds Zoe Diagnosis when the target's HP reaches the specified percentage.
- Triggers Pepsis  when the target's HP reaches the specified percentage.
- Adds Taurochole when the target's HP reaches the specified percentage.
- Adds Haima when the target's HP reaches the specified percentage.
- Adds Rhizomata when the Addersgall reaches 0. …
=> [SGE] Single and AoE heals

XIVSlothCombo/Combos/RDM.cs, XIVSlothCombo/Combos/WAR.cs, XIVSlothCombo/CustomComboPreset.cs
I played a few dungeons with RDM and while it was functional, there were some quirks that I wanted to clean up.
RDM Lucid Dreaming Feature
- Moved from [Jolt I/II, Verstone, Verfire, Veraero II, Verthunder II] to [Veraero I/III, Verthunder I/III and Scatter/Impact].
- Disabled the feature during your Melee combo so it doesn't interfere with the buttons.
- Lucid Dreaming will now appear for the entire weave window, even when your MP regens above the threshold.
WAR Bug Fix (https://github.com/Nik-Potokar/XIVSlothCombo/issues/405)
- Infuriate will now only appear during the weave window.
=> Updates to RDM Lucid Dreaming feature and WAR Bug Fix

XIVSlothCombo/Combos/DRK.cs, XIVSlothCombo/Combos/GNB.cs, XIVSlothCombo/Combos/WAR.cs, XIVSlothCombo/ConfigWindow.cs, XIVSlothCombo/CustomCombo.cs, XIVSlothCombo/CustomComboPreset.cs, XIVSlothCombo/PluginConfiguration.cs
GNB, DRK: Added sliders to gap closer options
GNB: Separated CDs into individual toggles, added DoT skills to NM feature
DRK: Refactored Souleater Combo
DRK: Added Delirium, Shadowbringer, Carve and Spit, Blood Weapon to Main Combo. Added burst features to pool some skills for even minute window bursts. With all options selected will turn Main Combo to Simple DRK.
DRK: Cleaned up Opener, removed flags related to resources. Will be able to enter Opener from outside of combat without any reliance on any resources.
DRK: Added slider for EoS MP Dump.
DRK: AoE refactoring
Framework: Added global Melee Distance Offset
=> DRK ST Overhaul

XIVSlothCombo/ConfigWindow.cs, XIVSlothCombo/ConfigWindowFunctions.cs
Fixes hide conflicting combos with child presets (again).
Adds a button at the bottom of the window that opens up the Github issues page.
=> Actual fix for child conflicts + Issues Button

XIVSlothCombo/Combos/PLD.cs, XIVSlothCombo/CustomComboPreset.cs
PLD: Expiacion and Circle of Scorn Features now both work below level 86
PLD: Typo fix in Combo Info
=> PLD: Expiacion and Circle of Scorn Features level synced

XIVSlothCombo/Combos/SGE.cs, XIVSlothCombo/ConfigWindow.cs, XIVSlothCombo/CustomComboPreset.cs
SGE Class:
Changed Levels to byte. Byte typecastings on level checks no longer needed
Added all class ability levels
CustomComboPreset.cs et all
Renamed Sage's Lucid Dreaming Slider config name to be inline with Cupcake's commit
ConfigWindow.cs
Fixes Nik-Potokar/XIVSlothCombo#421 Rhizomata Feature checkboxes (dup names/desc issue)
Sage.cs
A bit of refactor, and commenting on all combos except SageSingleTargetHeal & SageAoEHeal
SageDPSFeature: Needing to know which Dosis to apply removed. Not needed with OriginalHook magic. Lucid Dreaming slider is a permanent (not optional) feature
SagePhlegmaFeature: Combines PhlegmaToxikon & PhlegmaDyskraia under it as both were using almost identical code. These have been combined under one code tree. May need re-enabling in GUI if you were using these …
=> [SGE] Cleanup/Refactor/Fixes

XIVSlothCombo/Combos/BLM.cs, XIVSlothCombo/Combos/DRK.cs, XIVSlothCombo/Combos/GNB.cs, XIVSlothCombo/Combos/PLD.cs, XIVSlothCombo/Combos/WAR.cs, XIVSlothCombo/ConfigWindow.cs, XIVSlothCombo/CustomComboPreset.cs
DRK: Fix for Shadowbringer ability preventing use of Abyssal Drain on oGCD Feature (https://github.com/Nik-Potokar/XIVSlothCombo/issues/423)
DRK: Fix for Salt and Darkness preventing use of Shadowbringer on oGCD Feature
BLM: Fix for Thunder issue when switching from AoE Combo Feature to Simple BLM (https://github.com/Nik-Potokar/XIVSlothCombo/issues/403)
BLM: Added option to AoE Combo Feature to include Foul and Manafont-to-Flare for additional damage (https://github.com/Nik-Potokar/XIVSlothCombo/issues/403 and https://github.com/Nik-Potokar/XIVSlothCombo/issues/381)
DRK / GNB / PLD / WAR: Double Reprisal Protection Feature (https://github.com/Nik-Potokar/XIVSlothCombo/issues/329)
=> DRK oGCD Feature Bug Fixes || BLM AoE Combo Feature Fix and Enhancement || Tanks Double Reprisal Protection Feature

XIVSlothCombo/Combos/DRK.cs, XIVSlothCombo/Combos/GNB.cs, XIVSlothCombo/Combos/MNK.cs, XIVSlothCombo/Combos/PLD.cs, XIVSlothCombo/Combos/RDM.cs, XIVSlothCombo/Combos/WAR.cs, XIVSlothCombo/CustomCombo.cs
Tanks: No longer shows Stone when Reprisal is on CD
MNK: Meditation on Howling Fist/Enlightenment Feature restored (Was it supposed to be removed?)
⇒ In response to: https://github.com/Nik-Potokar/XIVSlothCombo/issues/435
RDM: Code cleanup on Lucid Dreaming feature
Framework: New check 'CanSpellWeave(actionID)' to check weave window and if a spell is being cast
=> Tanks: Reprisal Feature Beautification ★ MNK Feature restored ★ Added check 'CanSpellWeave(actionID)' and cleanup on RDM

XIVSlothCombo/Combos/BRD.cs
- Barrage was not checking for StraigthArrow buff possibly re-writting it, wasting a RA proc ... oops...
- Changed  order of applied dots, wind 1st venom 2nd
- Disable Apex Arrow was still calling Apex Arrow
- Misc QoL changes
=> [BRD] Barrage was not checking for StraigthArrow buff;

XIVSlothCombo/Combos/BRD.cs, XIVSlothCombo/ConfigWindow.cs, XIVSlothCombo/CustomCombo.cs
-  Remade protection for casting songs when no song is playing;
- Some users reported they were double songing when no song was being used, should be solved.
- Changed the time option of RagingJaws to be 3 to 5 seconds instead of 0 to 3 seconds.
=> [BRD] Protection correction for when you dont have songs going.

XIVSlothCombo/Combos/PLD.cs
Legibility
Removed some redundant level checks (`BoF`)
`Confiteor` Single Target level check fix
`Confiteor` AoE level check fix
Thanks to @Nyuuuwu for the `Confiteor` stuff - #483
=> [PLD] Formatting & Refactoring

XIVSlothCombo/Combos/SGE.cs
PhlegmaReplacementFeature Bug Squishes:
Looked for the wrong GUI checkbox (fixes Nik-Potokar/XIVSlothCombo/#451)
Add "no-target change to Dyskrasia" logic
~~k-kz: Please test the GUI enable/disable is correct ( #451 ) and if Dyskrasia is enabled, it should show Dyskrasia when no target is selected.~~
=> [SGE] Phlegma Fixes

XIVSlothCombo/Combos/SMN.cs
Adjusted searing light to go off after bahamut cast, but during GCD cooldown, timing can be adjusted to whatever you feel is right, its at 55 seconds now to avoid casting it too late during bahamut rotation.
=> [SMN] Adjusts searing light, adjusts ogcd delay checks, removes duplicate code.

XIVSlothCombo/Combos/SMN.cs, XIVSlothCombo/CustomComboPreset.cs
Removes SummonerMainComboFeatureRuin1 as suggested in #464.
Removed some redundant parenthesis in smn file.
Removed code, menu entry, and conflicting combo reference.
=> Remove SummonerMainComboFeatureRuin1

XIVSlothCombo/Combos/ADV.cs, XIVSlothCombo/Combos/AST.cs, XIVSlothCombo/Combos/NIN.cs, XIVSlothCombo/Combos/WHM.cs, XIVSlothCombo/CombosPVP/BRDPVP.cs, XIVSlothCombo/CombosPVP/MCHPVP.cs, XIVSlothCombo/CombosPVP/NINPVP.cs, XIVSlothCombo/CombosPVP/SGEPVP.cs, XIVSlothCombo/ConfigWindow.cs, XIVSlothCombo/CustomCombo.cs, XIVSlothCombo/CustomComboCache.cs, XIVSlothCombo/CustomComboPreset.cs
Changelog for big 6.1 update (Part 1 cause it's soooo big it needs longer to cook).
PVP
- Removes all old PVP features due to redundancy.
- New PVP features for BRD, MCH, RDM, WAR, NIN & SGE added plus common actions for all of them.
- Adds Emergency Heals, Guard and Quick Purify features to be used in tandem with the previously mentioned PVP features.
Framework:
- The configuration window has been redesigned to fit a neater tabbed style.
- `Adventurer` renamed to `All Jobs`
- Developers can now target specific party members easier. Also works in Trusts (big bonus).
- New UI templates to accomodate the targeting update: Job Grid, Role Grids. Both have multiple choice and single choice variants.
- `Debug Mode` added to the `Adventurer` tab to allow developers more ready access to certain …
=> Final 6.1 Part 1 update

XIVSlothCombo/Combos/NIN.cs, XIVSlothCombo/Combos/WHM.cs, XIVSlothCombo/ConfigWindow.cs, XIVSlothCombo/CustomCombo.cs, XIVSlothCombo/CustomComboPreset.cs
WHM: Lucid feature wasn't connected to slider.
NIN: Limited armor crush slider to 30 to prevent overcapping buff.
NIN: Removed slider on Hurajin, always DPS loss if not set to 0.
Framework: Lowered weave window on CanSpellWeave to help account for SPS builds. (https://github.com/Nik-Potokar/XIVSlothCombo/issues/490)
Note: CanSpellWeave change should be a temporary fix until we can set global variables.  Then we can make it a user input slider.
WHM: Lily Overcap Protection (Adds Afflatus Rapture AoE heal to Glare/Stone) (https://github.com/Nik-Potokar/XIVSlothCombo/issues/495)
WHM: Afflatus Misery on Glare/Stone option
=> Various fixes and adjustments

XIVSlothCombo/Combos/BRD.cs
Fix rare cases where you start an opener and Radiant is on CD with coda active
=> BRD opener fix

XIVSlothCombo/Combos/RDM.cs
Fixes:
Fixed `Simple RDM` melee combo checks
Proper lv.90 checks on `Simple RDM`
Refactoring:
Removed redundant parentheses
More level check additions
Removed redundancies
Swapped some `==` for `is` etc
Shortened some statements with `or`
Removed some whitespace
Not finished but... another time.
=> [RDM] Combo Fix

XIVSlothCombo/Combos/SMN.cs, XIVSlothCombo/CustomComboPreset.cs
Adjusts description of main combo.
Removed Rekindle from main and AOE combo, 
Adds main and aoe Rekindle feature to put it back on combo.
Removes searing checks from demi summons
Removes Ruin III from main combo so users can use it for mobility.
Changes CanWeave for CanSpellWeave thanks @damolitionn
=> [SMN] Various tweaks and remove Searing checks from Demis

XIVSlothCombo/Combos/MCH.cs, XIVSlothCombo/CustomComboPreset.cs
- Marking `MachinistHeatblastGaussRicochetFeature` as a conflict with Simple Machinist.
- Should solve #516
=> [MCH] Adding conflict to Simple Machinist

XIVSlothCombo/Combos/SMN.cs, XIVSlothCombo/ConfigWindow.cs, XIVSlothCombo/CustomComboPreset.cs
Reverted Egi behavior to before last push, kept other additions such as Ruin 4 movement feature untouched.
used HasPetPresent() for carbuncle summon feature
=> Fix broken egi Astral flows (ST and AOE)

XIVSlothCombo/Combos/ADV.cs, XIVSlothCombo/Combos/AST.cs, XIVSlothCombo/Combos/NIN.cs, XIVSlothCombo/CombosPVP/BRDPVP.cs, XIVSlothCombo/CombosPVP/MCHPVP.cs, XIVSlothCombo/CombosPVP/NINPVP.cs, XIVSlothCombo/CombosPVP/PVPCommon.cs, XIVSlothCombo/CombosPVP/RDMPVP.cs, XIVSlothCombo/CombosPVP/SGEPVP.cs, XIVSlothCombo/CombosPVP/WARPVP.cs, XIVSlothCombo/ConfigWindow.cs, XIVSlothCombo/CustomCombo.cs, XIVSlothCombo/CustomComboPreset.cs
PVP global features now replaces every button and works on every job, regardless of individual job features.
Added CN client compatibility for the AST Quick Target features.
Added a `Redraw Feature` to the AST draw feature to attempt to optimize seal gains.
PVP Global Feature `Emergency Guard` now takes into consideration if under the debuff of WAR LB.
Wolves Den Pier now counts as a PVP zone, to enable global features in duels.
`JustUsed` now reverted back to previous, working state. (Fixes BRD simple opener issues)
=> PVP Updates + CN support for AST

XIVSlothCombo/Combos/BRD.cs, XIVSlothCombo/Combos/MCH.cs, XIVSlothCombo/CombosPVP/MCHPVP.cs, XIVSlothCombo/ConfigWindow.cs, XIVSlothCombo/ConfigWindowFunctions.cs, XIVSlothCombo/CustomComboPreset.cs, XIVSlothCombo/PluginConfiguration.cs
- PVP
- Fixed the use of analysis , was incorrectly using it with Bioblaster and spamming the casts;
- Added a distance check for Bioblaster (12y);
- PVE
- Made wilffire more responsive to apply the debuff, should feel better at the 2m windows;
- PVE
- Renamed Simple Raid Mode, to Simple No Waste Mode and added a slider for user to set the threshold [1:5] for the HP check to apply/reapply dots, songs and buffs;
=> [MCH & BRD]  Some PVP and PVE fixes and tweaks

XIVSlothCombo/Combos/BRD.cs, XIVSlothCombo/ConfigWindow.cs, XIVSlothCombo/CustomCombo.cs, XIVSlothCombo/CustomComboPreset.cs, XIVSlothCombo/ImageHandler.cs
- PVE
- Removal of the simple opener feature, its now baked inside the normal rotation logic;
- More dynamic and adapt better to what CDs you have at the start of the fight;
- Added a feature option to simple dots to only apply dots at the "opener" phase (until the 1st refresh of dots happens);
- Without it the BRD will always reapply dots for new targets;
- Raised the upper limit for `Simple No Waste` to 10%.
- Changed a couple features descriptions to make it more explicit and less confusing (?) [I hope 😝]
- Simple AoE Bard , fix for song spam.
- Fix for #543 
- Added an option for AoE song to exclude Wanderer`s Minuet from the rotation.
=> [BRD] Embedding the opener on the normal logic

XIVSlothCombo/Combos/SGE.cs
Reverted if/else logic to previous design, but kept null checks where appropriate and using BattleNPCKind still instead of ObjectKind check
=> SGEDPSFeature ToT Fix electric boogaloo

XIVSlothCombo/Combos/AST.cs, XIVSlothCombo/Combos/WHM.cs
[AST] Aspected Helios becomes Helios when under the level required for Aspected Helios
[AST] Made sure Aspected Helios, Horoscope and Neutral Sect play nicely together.
[WHM] Medica 2 becomes Medica 1 when under the level required for Medica 2
=> AST and WHM level checks for Aspected Helios and Medica 2

XIVSlothCombo/Combos/ALL.cs, XIVSlothCombo/Combos/AST.cs, XIVSlothCombo/Combos/BLU.cs, XIVSlothCombo/Combos/RDM.cs, XIVSlothCombo/Combos/SCH.cs, XIVSlothCombo/Combos/SGE.cs, XIVSlothCombo/Combos/WHM.cs
ALL: Added Lucid Dreaming info. Lucid Dreaming was lowered to level 14.
AST/BLU/RDM/SCH/SGE: Updated Lucid Dreaming calls to use All.LucidDreaming. SCH/SGE CanWeave upgraded to CanSpellWeave.
AST: Removed redundant level checks against LucidDreaming, but file overall needs a good looking over/refactor
SGE: DPSFeature - Prioritized Lucid Dreaming.
SGE: PhlegmaFeature - Simplified code provided from Taurenkey
=> LucidDreaming (6.1) Updates & Phlegma Cleanup

XIVSlothCombo/Combos/WAR.cs, XIVSlothCombo/CustomComboPreset.cs
[WAR]
Fix for `Infuriate` not appearing on Fell Cleave/Decimate outside of weave windows
Added option to `Infuriate on Fell Cleave/Decimate` to use `Inner Release` stacks first
Adjusted `Infuriate on Storms Path` to appear at 40 gauge or below instead of 50
=> WAR: Fix for Infuriate not appearing outside of weave windows

XIVSlothCombo/Combos/DNC.cs, XIVSlothCombo/CustomComboPreset.cs
`Simple Single Target Feather Pooling` now expends when target HP% < 2
Refactored `Single Target Multibutton` Esprit Overcap Options
Refactored `AoE Multibutton` Esprit Overcap Options
Refactored `Devilment Feature`
Updated descriptions
=> [DNC] Feather Pooling Optimisation + Refactor

XIVSlothCombo/Combos/AST.cs, XIVSlothCombo/Combos/NIN.cs, XIVSlothCombo/ConfigWindow.cs, XIVSlothCombo/CustomComboPreset.cs, XIVSlothCombo/PluginConfiguration.cs, XIVSlothCombo/XIVSlothCombo.cs
[NIN]
Added 2 Ninki pooling features on `Simple Single Target`. #589 
[AST]
Reworked and fixed `Target Previous Feature` due to patch update. Now switches back to your last manually selected target once the card is played. #588 
[General]
Adds `Sloth Message of the Day` that gets printed to the chatbox upon login or reload plugin.
=> NIN & AST Updates

XIVSlothCombo/CombosPVP/NINPVP.cs
Bug fix for NIN PVP AOE. Wrong Debuff ID was checked for Sealed Doton (Fix tested by Ari)
=> NINPVP: Sealed Doton DebuffID Fix

XIVSlothCombo/Combos/SMN.cs, XIVSlothCombo/CombosPVP/WARPVP.cs, XIVSlothCombo/ConfigWindow.cs, XIVSlothCombo/CustomCombo.cs, XIVSlothCombo/CustomComboPreset.cs, XIVSlothCombo/XIVSlothCombo.cs
[PVP]
Makes sure to disable the PVP flag if you don't have a party when on a Frontlines map (to bug fix any quests that take you to a solo instance on a Frontlines map). #599 
WAR Burst Mode now actually uses the full default combo and not just Heavy Swing. Plus tweaks to enable weaving. #606 
[SMN]
Mini-rework to the `Enable AOE Combo Features` to enable using summon abilities without requiring the summon egi feature enabled first.
Adds 6 options to the `Searing Light AoE option` to decide which phase to use the ability in.
[Plugin]
MOTD now fires off 3 seconds after logging in rather than right away.
=> PVP Feature Solo Instance Check + MoTD Updates

XIVSlothCombo/Combos/ALL.cs, XIVSlothCombo/Combos/SAM.cs, XIVSlothCombo/Combos/WAR.cs, XIVSlothCombo/CombosPVP/SAMPVP.cs, XIVSlothCombo/ConfigWindow.cs, XIVSlothCombo/CustomComboPreset.cs
SAM: Two Target Feature added to Oka Combo
SAM: True North Feature added
SAM: Separated sliders for AOE and ST overcap
SAM: Fixed Setsugekka level check for One Button Rotation
SAMPvP: Burst Mode and Gap Closer Features added
WAR: Added Primal Rend Melee Feature which activates Primal Rend when under the boss
=> SAM and WAR Features

XIVSlothCombo/Combos/RDM.cs, XIVSlothCombo/CustomComboPreset.cs
- PVE
- New feature
- `Corps-a-Corps` feature to be used between melee GCDs , and an option to use to pull you to the target when ready to enter melee phase;
- Tweaks
- `Lucid Dreaming` feature changed to accommodate  AoE abilities for `Veraero` and `Verthunder` plus `jolt`;
- Melee phases, its now possible to go from `ST` melee combo to  `AoE` and still get the finishers (of course breaking your melee combo but not losing your mana stacks) provide you have the mana for it;
- `AoE` to `ST` is being considered but still not ETA;
- Very niche, not optimal behavior , just use for trash and overworld things;
=> [RDM] Couple enhancements

XIVSlothCombo/CombosPVP/WARPVP.cs, XIVSlothCombo/CustomComboPreset.cs
The stun check on Blota is mostly due to an edge case with all gap closers, sometimes you can gap close but not make it to your target.
=> Warpvp option, and priority tweaks.

XIVSlothCombo/CombosPVP/WARPVP.cs
Reprioritize Primal Rend above Blota, and don't use Blota if Primal Rend is going to be up soon to avoid wasting heavy debuff
=> [WAR PVP] Reprioritize

XIVSlothCombo/Combos/SGE.cs, XIVSlothCombo/ConfigWindow.cs, XIVSlothCombo/CustomCombo.cs, XIVSlothCombo/CustomComboPreset.cs
- CustomComboPreset.cs & SGE.cs: Refactored/reordered/renumbered Sage using NikkoXIV's RDM prototype design
- CustomComboPreset.cs: Changed Sage feature names and descriptions
- CustomCombo: Added GetOptionValue (shorthand for Service.Configuration.GetCustomIntValue(), for sliders and radiobuttons) **Desperately needs a better name**
- ConfigWindow: Removed integer boxes for Flat HP checks. Enemy HP Percent changed to slider
- SGE-SageSoteriaKardia: Combined nested ifs by inversing buff and cooldown checks
- SGE-SageRhizomata: Combined nested Ifs
- SGE-SageDruoTauro: Reversed Tauro and Druo. Behavior is the same (uses Tauro when it can). Works more like native XIV trait that upgrades Druo to Tauro, vs degrading Tauro to Druo (better for leveling)
- SGE-SageAoEPhlegma: Cleaned up if …
=> [SGE] Code Refactor & Combo Organization

XIVSlothCombo/CombosPVP/SAMPVP.cs, XIVSlothCombo/ConfigWindow.cs, XIVSlothCombo/CustomComboPreset.cs
SAMPvP: Fixed issue where AOE melee protection extended to non Kasha Combo skills.
SAMPvP: Added a Movement Check for Midare and Ogi Namikiri
SAMPvP: Added Enemy HP Slider for Gap Closer Feature
SAMPvP: Stops Burst from happening if Enemy is guarding.
=> SAMPvP: Minor Adjustments

XIVSlothCombo/Combos/SMN.cs, XIVSlothCombo/CombosPVP/BLMPVP.cs, XIVSlothCombo/CombosPVP/PVPCommon.cs, XIVSlothCombo/ConfigWindow.cs, XIVSlothCombo/CustomCombo.cs, XIVSlothCombo/CustomComboPreset.cs, XIVSlothCombo/XIVSlothCombo.cs
[BLMPVP]
Added `Burst Mode` on Fire and Blizzard.
Added `Night Wing Feature` to `Burst Mode`.
Added `Aetherial Manipulation Feature` to `Burst Mode`.
[Bugs]
The numbering of features in the plugin config window should now remain consistent regardless of what has been set to show or hide.
`Enable AOE Combo Features` on SMN has been fixed to work properly, now actually using every ability and not cancelling out of summons early. #630 
[Framework]
Adds `debug` and `enabled` as optional commands after `/scombo` to aid users in supplying information to devs for problem solving.
=> BLMPVP + Bugfixes

XIVSlothCombo/CombosPVP/WARPVP.cs, XIVSlothCombo/CustomComboPreset.cs
Adds option for blota's primal rend cooldown check to be optional.
=> [WarPVP] Adjust blota's primal rend cooldown check to be optional

XIVSlothCombo/Combos/SCH.cs, XIVSlothCombo/ConfigWindow.cs, XIVSlothCombo/ConfigWindowFunctions.cs, XIVSlothCombo/CustomComboPreset.cs
SCH Refactor / Cleanup
SCH.cs
- SCH Ruin1: Corrected ID
- SCH Recitation Buff ID added
- ScholarSeraphConsolationFeature: Nested if cleanup
- ScholarEnergyDrainFeature -> ScholarAetherflowFeature. Similar now to Sage's Rhizomata Feature, it replaces all Aether stack using abilities with Aetherflow OR some finer details such as Recitation & Disspiation. Fully tested, resolves Nik-Potokar#605
- ScholarRaiseFeature: Fixed logic. Will replace Swiftcast with Resurrection when off cooldown (allowing for hard cast raise)
- ScholarFairyFeature: Mild code cleanup
- ScholarDPSFeature -> ScholarBroilFeature. Similar to SageSTDosisFeature now, with HP% check, ToT. Lucid Dreaming and Chain Stratagem (now with HP% check, and overlap protection) now using CanSpellWeave for better reliability (fixes …
=> [SCH] Code Cleanup & New Features

XIVSlothCombo/CombosPVP/RPRPVP.cs
`Communio Option` now holds final charge appropriately
`Communio Option` now returns `Void/Cross Reaping` if `Communio` would be otherwise wasted
=> [RPRPvP] Communio Option Fix

XIVSlothCombo/Combos/ALL.cs, XIVSlothCombo/Combos/BRD.cs, XIVSlothCombo/CustomCombo.cs
- PVE
- Burst Phase
- Some logic refactor to better accommodate `Battle Voice` and `Radiant Finale`.
- Have been tested with GCDs of 2.45 up to 2.50.
- Added delayed weaving for `Wanderer's Minuet` and `Raging Strikes` after the opener for better alignment.
- Song Protection
-  Added a tentative desync prevention for `Army Paeon` , the situation when `Wanderer's Minuet` come back from CD too soon because of a death or downtime, and the `Army Paeon` still had considerable duration.
- Will now wait for at least 4 repertoires of `Army Paeon` to change to `Wanderer's Minuet` to get the full buff of `Army's Muse`
- Fixes
- Very low level check for `Raging Strikes` uses, mainly before songs are acquired.
- Tanks
- Interrupt
- Changed priority of interject , elevated it to top priority. 
- Was …
=> [BRD] Timing tweaks for the burst phase

XIVSlothCombo/Combos/DNC.cs, XIVSlothCombo/CombosPVP/DNCPVP.cs, XIVSlothCombo/CustomComboPreset.cs
[DNC]
Added `Simple Dance Step Combo`
Added `Simple AoE Dance Step Combo`
Simple DNC modes now totally independent from others
Fixed all relevant conflicts
[DNCPvP]
`Curing Waltz Burst Option` renamed to `Curing Waltz Option`
Removed redundant comment text
Removed `En Avant Overcap Protection` hidden code
=> [DNC, DNCPvP] Features + Cleanup

XIVSlothCombo/Combos/SMN.cs, XIVSlothCombo/ConfigWindow.cs, XIVSlothCombo/CustomComboPreset.cs
- Swiftcast Garuda Option: Slipstream gets used when Swiftcast's buff is up to help accommodate SpS builds.
- Swiftcast Ifrit Option: Swiftcast is used earlier to accommodate SpS builds reverse drifting on the final Ruin.
- Searing Light Option: Broken into two, base used on cooldown. Burst Option is used during Bahamut/Phoenix Phase and now works for SpS builds.
- ClassID fixed
- Burst Choice Option added to let users to decide to burst in Bahamut Phase or Phoenix Phase.
- Pooled Festers logic updated to fix conflicts pre Searing Light unlock, Pooled Festers now used strictly during Searing Light and in Bahamut/Phoenix Phase.
- Egi Abilities on Egi Summons Feature added: Allows use of Egi Abilities (Astral Flow) on Egi Summons when Primals are summoned.
=> SMN Logic Update

XIVSlothCombo/CombosPVP/PVPCommon.cs
Fixes being unable to teleport or use return after switching from DoH/DoL/BLU with the emergency override
=> Fix for Wolves Den teleport glitch

XIVSlothCombo/Combos/RDM.cs, XIVSlothCombo/ConfigWindow.cs, XIVSlothCombo/CustomComboPreset.cs
[RDM]
- Updated descriptions to include correct `ReplaceSkill`
- Cleaned up code to remove `RDM.` from actions and removed old comments
- Added `Displacement <> Corps-a-corps` feature
- Added option to `Melee Finisher`: `Use on Veraero 1/2/3 and Verthunder 1/2/3`
=> RDM Cleanup and Fixes/Tweaks

XIVSlothCombo/Combos/DNC.cs, XIVSlothCombo/ConfigWindow.cs, XIVSlothCombo/CustomComboPreset.cs
Removed `ST Instant Saber Option` ✔️
Removed `AoE Instant Saber Option` ✔️
Added slider for Esprit threshold to `ST Esprit Overcap Option` ✔️
Added slider for Esprit threshold to `AoE Esprit Overcap Option` ✔️
Removed `Simple Dance Step Combo` ✔️
Removed `Simple AoE Dance Step Combo` ✔️
Added `Dance Step Combo Feature` (works with all modes) ✔️
Added Target HP% slider to stop `Simple Standard Step` ✔️
Added Target HP% slider to stop `Simple Technical Step` ✔️
Added Target HP% slider to expend `Simple Feather Pooling` ✔️
Added `Curing Waltz` slider to `Simple Panic Heals` ✔️
Added `Second Wind` slider to `Simple Panic Heals` ✔️
Added Target HP% slider to stop `Simple AoE Standard Step` ✔️
Added Target HP% slider to stop `Simple AoE Technical Step` ✔️
Added `Curing Waltz` slider to `Simple …
=> [DNC] Features & Fixes

XIVSlothCombo/Combos/DNC.cs, XIVSlothCombo/CustomComboPreset.cs
~~Added `Simple Step Fill Option`~~
~~Added `Simple AoE Step Fill Option`~~
Added `Simple Tech Fill Option`
Added `Simple AoE Tech Fill Option`
> (Initially, these two features applied to both SS and TS. Now, the new features only apply to TS, and allow for combined use with `Simple Standard Step Option` and `Simple AoE Standard Step Option`.
Adjusted priority of `Simple Interrupt Option`
Adjusted priority of `Simple AoE Interrupt Option`
Added relevant conflicts
=> [DNC] Simple Step Fill Options

XIVSlothCombo/Combos/SCH.cs, XIVSlothCombo/Combos/SGE.cs, XIVSlothCombo/ConfigWindow.cs, XIVSlothCombo/ConfigWindowFunctions.cs, XIVSlothCombo/CustomComboPreset.cs
20220511 : Revised Changelog
SGE: Removed Role Action IDs under SGE. Added Phlegma's attack range
SGE SageAoEPhlegmaFeature: Restructured for adding Phlegma out of range to Toxikon option. Lucid Dreaming added
SGE SageSTDosisFeature Eukrasian Dosis: Moved the buff check before debuff check, as the point of the routine is to enable the buff.
SGE SageZoePneumaFeature Added (resolves #621)
SCH: Removed Esuna Role ID
SCH ScholarAetherflowFeature: Aetherflow stopped from showing on top of abilities on cooldown. Option to show Aetherflow/Dissipation on Energy Drain only (previous design, resolves #673) or on all abilities (like Sage) added.
SCH ScholarBroilFeature: Aetherflow is now weaved, not forced, and moved up in priority after Lucid. Ruin 2 moved up in priority above Bio, to reduce …
=> SCH & SGE Discord Feedback

XIVSlothCombo/Combos/RDM.cs, XIVSlothCombo/ConfigWindow.cs, XIVSlothCombo/CustomComboPreset.cs
[RDM]
- Moved option for pooling `Corps-a-corps` to OGCD section
- Added option for pooling Engagement to allow for a manual displacement
- Added option for `Acceleration` to only appear during weave windows on AoE
- Fixed an issue where `Manafication` and `Embolden` may not be used correctly
- Fixed an issue where `Acceleration` may interfere with Melee combos
- Fixed an issue where the opener could appear during combat
- Added `Verraise` conflict warning with `Magical Ranged DPS: Raise Feature`
- Added range adjustment slider for the first `Moulinet` in the `AoE Melee Combo` feature.
- Fixed an issue where the option `Acceleration on Single Target` would still function when the parent feature is disabled.
=> RDM Tweaks, fixes and options

XIVSlothCombo/ActionWatching.cs, XIVSlothCombo/Attributes/BlueInactiveAttribute.cs, XIVSlothCombo/BlueMageService.cs, XIVSlothCombo/Combos/BLU.cs, XIVSlothCombo/ConfigWindow.cs, XIVSlothCombo/CustomCombo.cs, XIVSlothCombo/CustomComboPreset.cs, XIVSlothCombo/IconReplacer.cs, XIVSlothCombo/PluginConfiguration.cs, XIVSlothCombo/Service.cs
[BLU]
- New tracking of active spells. Requires the player to open the Blue Magic Spellbook to register any existing active spells.
- Features will skip over spells if the player does not have them active. Huzzah for all us non-Matra Magic having folks.
- Config window now displays which spells you still have to activate to meet the feature's quota of spells.
- `Solo Mode` feature added to `Final Sting Combo`. Checks if able to use Basic Instinct to increase damage for maximum one shot damage.
- `Hydro Pull Setup` feature added to `Ram's Voice into Ultravibration`. If the target is not in melee range, uses Hydro Pull to grab them into range for vibe checking.
=> BLU QoL Overhaul

XIVSlothCombo/Combos/SMN.cs
Fixes level on Ruby and Topaz ruins, fixes deathflare not working for aoe rotation.
Adjusts aoe demi summon behavior to be the same as single target.
=> [SMN] Couple level fixes, formatting, and deathflare aoe not working.

XIVSlothCombo/Combos/PLD.cs, XIVSlothCombo/CustomComboPreset.cs
[PLD]
Added `Expiacion and Circle of Scorn option` to only use during FoF windows, or when FoF is on cooldown.
Normal `Expiacion and Circle of Scorn feature` now uses it on cooldown.
=> PLD: Expiacion and Circle of Scorn option

XIVSlothCombo/Combos/RDM.cs, XIVSlothCombo/Combos/WHM.cs, XIVSlothCombo/ConfigWindow.cs, XIVSlothCombo/CustomComboPreset.cs
[RDM]
- Added `Embolden to Manafication` feature. (https://github.com/Nik-Potokar/XIVSlothCombo/issues/355)
- Improved checks for `Embolden` before `Manafication` is used
- Added `Riposte and Moulinet` and `Fleche, Riposte and Moulinet` to `Weave OGCD Damage` feature
- Updated the description for `Gap close with Corps-a-corps` to specify that you need the required mana to start the melee combo
[WHM]
- Added `AoE DPS Feature` including `Lucid Dreaming`, `Assize`, `Lily Overcap Protection` and `Afflatus Misery` when targeting an NPC. (https://github.com/Nik-Potokar/XIVSlothCombo/issues/355)
=> RDM Embolden Feature, Embolden checks and WHM Feature

XIVSlothCombo/Combos/AST.cs, XIVSlothCombo/Combos/BLM.cs, XIVSlothCombo/Combos/BRD.cs, XIVSlothCombo/Combos/DNC.cs, XIVSlothCombo/Combos/DRG.cs, XIVSlothCombo/Combos/MNK.cs, XIVSlothCombo/Combos/PLD.cs, XIVSlothCombo/Combos/WHM.cs
- Changed the potencially hazzard effects of `FindEffect` to `GetBuffRemaingTime` to avoid `Null Access Exceptions` in many jobs.
- 3 helper functions should be used to avoid those situations:
- `GetBuffRemaingTime`, `GetBuffStacks` and `GetDebuffRemaingTime`.
=> [Framework] Null Access Exception correction

XIVSlothCombo/Combos/MNK.cs, XIVSlothCombo/CustomCombo.cs, XIVSlothCombo/CustomComboCache.cs
[PVP]
- Fixes check for Crystaline Conflict maps due to Dalamud update breaking it.
[Framework]
- Adds `GetResourceCost` function to check how much an action costs.
- Adds `IsResourceTypeNormal` function to check if the action uses MP or another resource such as job gauge.
=> PVP Check Fix

XIVSlothCombo/Combos/MNK.cs
- Fix demolish burst option not changing to Bootshine with Formless Fist
- Fix demolish duration check order
=> [MNK] Fixes

XIVSlothCombo/Combos/SMN.cs, XIVSlothCombo/ConfigWindow.cs, XIVSlothCombo/CustomComboPreset.cs
- Moved `Demi Feature` above `Egi Feature` for single target as demis should have priority over egis (was this way already for AoE)
- Removed redundant level checks (checked for `Swiftcast` level, and `Ruby Ruin` level. `Swiftcast` is higher level)
- Applied `Egi Order`, `Egi Swiftcast`, and `Burst Phase` to AoE as well for parity.
- Changed order of features to account for `Egi Order`, `Egi Swiftcast`, and `Burst Phase` not being inside single target.
- Renames features that aren't ST only anymore to attempt to clarify what they do at first glance.
- Adds options for `Searing Light`, `Swiftcast`, and damage oGCDs to only use them on single target.
=> SMN ST/AOE parity changes

XIVSlothCombo/Combos/RPR.cs, XIVSlothCombo/CustomComboPreset.cs
Moved `Communio` and `Lemure's Scythe` options from `Enshroud` to `Guillotine`
Made `Guillotine` use `Grim Reaping` without the `Enshroud Option` enabled
=> RPR AOE Fix

XIVSlothCombo/CombosPVP/BLMPVP.cs, XIVSlothCombo/ConfigWindowFunctions.cs, XIVSlothCombo/XIVSlothCombo.cs
[Framework]
- Stopped situations where the default value wasn't being set to a config properly.
[PVP]
- BLM Burst Mode now takes into account stacks of Paradox due to recent 6.11a update changing the action.
=> Config Tweaks & 6.11a BLM Update

XIVSlothCombo/Combos/WHM.cs
SpellWeave checks removed, can't weave on Holy/HolyIII (Same cast and recast time)
Fixes #744
=> [WMH] AoE Fix

XIVSlothCombo/Combos/SMN.cs, XIVSlothCombo/ConfigWindow.cs, XIVSlothCombo/CustomComboPreset.cs
Singletarget swiftcast was not implemented correctly the first time.
AOE Egi order had the wrong combo preset, renamed preset to signify what it does.
=> Immediate bugfixes for SMN

XIVSlothCombo/Combos/RPR.cs
Since indexes for options started at one, nothing is selected by default since the default option is zero. 
This change makes it to where the first option is selected by default. (internally, not visually)
=> RPR Default radio buttons tweaks.

XIVSlothCombo/Combos/RDM.cs, XIVSlothCombo/CustomComboPreset.cs
[RDM]
`Weave OGCD Damage` Feature
- Fixed an issue where `Corps-a-corps` and `Engagement` would be shown while they had 0 charges remaining
- Fixed an issue where `Corps-a-corps` and `Engagement` wouldn't appear just prior to reaching 2 stacks when pooling
`Single Target Melee Combo` Feature
- Added new option `Unbalance Mana`: Uses an `Acceleration` charge to unbalance mana prior to the melee combo (Note: Will not activate between 45 and 49 mana as it would overcap after `Manafication`)
`Magick Barrier to Addle` Feature (New)
- Replaces `Magick Barrier` with `Addle` when on cooldown.  Includes double `Addle` protection.
=> [RDM] Fixes and New Option

XIVSlothCombo/Combos/DRG.cs
Simple AoE: Moved weave/gauge checks under action ID check (dalamud exception was occurring when it was checking all action IDs for weaving)/ Fixes #766
=> [DRG] Exception Fix

XIVSlothCombo/Combos/BLM.cs, XIVSlothCombo/CustomComboPreset.cs
- Level check for triplecast usage in BLM movement feature
- Updated PLD opener description to include information about the 18s pre-pull FoF opener execution.
=> [BLM/PLD] Fixes

XIVSlothCombo/ActionWatching.cs, XIVSlothCombo/Combos/ALL.cs, XIVSlothCombo/Combos/DRG.cs, XIVSlothCombo/Combos/MCH.cs, XIVSlothCombo/Combos/NIN.cs, XIVSlothCombo/CombosPVP/PVPCommon.cs, XIVSlothCombo/ConfigWindow.cs, XIVSlothCombo/CustomCombo.cs, XIVSlothCombo/CustomComboPreset.cs, XIVSlothCombo/IconReplacer.cs, XIVSlothCombo/Service.cs, XIVSlothCombo/XIVSlothCombo.cs
[Bug Fixes]
- Fixes #775 Should be fixed due to now undoing the previous changes.
- Fixes #767 Preset description adjusted and removed the `Suiton` check as 6.1 changed functionality of `Trick Attack` making this less useful for this feature.
- Fixes #765 All routes now correctly use the Mudras described.
- Fixes #735 Changed the check from cooldown remaining to checking for more than 1 charge.
- Fixes #695 Emergency features now won't kick in whilst under the effect of `Sky High` (the DRG LB buff they get whilst in the air)
- Fixes #683 Global feature tweaked to be more responsive by removing the check for the `Swiftcast` buff before returning the appropriate rez spell (or WHM's `Thin Air` if that feature is enabled) but still checks if `Swiftcast` is off cooldown to return that. …
=> Bugfixes Galore + Backend Tweaks

XIVSlothCombo/Combos/SMN.cs, XIVSlothCombo/ConfigWindow.cs, XIVSlothCombo/CustomComboPreset.cs
- Decouples Demi/Egi attacks from their `Summons on Main/AoE Combo` features.
- Removed "top level" features `EgisOnRuinFeature` and `EgisOnAOEFeature` as they didn't actually do anything.
- Moved single target Demi attacks into the `canSpellWeave` block as they are in AoE version (bugfix)
- Changes `AoE Rekindle (Astral Flow) Feature` to check `Rekindle` specifically instead of `Astral Flow` to match single target.
- Changes `Single Target Deathflare (Astral Flow)` to check its ability specifically to fall in line with the above change.
- Changes `AoE Deathflare (Astral Flow)` to check its ability specifically to fall in line with the above change.
- Renamed `SummonerSTPoolOnlyOption` to `SummonerSTOnlyPoolOption` to fall in line with other single target features.
- Renamed …
=> Smn decouple summons

XIVSlothCombo/Combos/MCH.cs, XIVSlothCombo/CustomComboPreset.cs
- PVE
- Added an option to `Stabilizer` to ensure that its only used to prep for `Wildfire` burst windows, avoiding desyncs and misalign of bursts, purposefully or not; 
- Reworked the `Simple Machinist` internal logic to be more responsive to CD desyncs, reopeners and openers with saved resources (looking at you dungeons and alliance raids :P) 
- 2m Burst windows should feel tighter, ensuring correct use.
- It will try to automatically minimize the effects of desync, being that occurring from death or starting the fight with some CDs off, because of that `Drill`, `Air Anchor` and `ChainSaw` can and will drift a little, but that should not negatively effect you that much.
- Note that a desync/misalign of burst is almost impossible to realign during the course of a fight unless you restart …
=> [MCH]  Logic Rework for Simple MCH

XIVSlothCombo/CombosPVP/BLMPVP.cs
Paradox no longer has charges since the 6.15 patch.
Pretty much a meaningless PR since i think it would still work even with the charge check but i feel it's better to have it implemented properly.
=> [BLMPVP] 6.15 patch removed charges from Paradox.

XIVSlothCombo/Combos/WAR.cs
Melee onslaught option checks for `Inner Release` cooldown, meaning it would cause you to not use onslaught at all until level 70.
Added level check to resolve.
=> Added level for Inner Release, and added level check for the melee onslaught option.

XIVSlothCombo/Combos/MCH.cs
Single/AoE: Barrel Stabilizer will no longer pop up DURING Hypercharge burst window
Single: Wildfire will not be available while Hypercharge is on cooldown (scenario where you had 100 heat, do the burst window before wildfire was ready, wildfire becomes ready right after the burst window is over but hypercharge has ~3 seconds left on cooldown
=> [MCH] Hypercharge Fixes

XIVSlothCombo/Combos/PvE/SCH.cs
Aetherflow's _Show on Energy Drain_ or _On All Aetherflow_ moves check corrected (should not interfere with user's current settings)
=> [SCH] Aetherflow Hotfix

XIVSlothCombo/Combos/CustomComboPreset.cs, XIVSlothCombo/Combos/PvE/MCH.cs
- Simple MCH `Reassemble` casts bug fix;
- `Wildfire` a bit more intelligent for levels below max level;
- Implementation of a `High Latency Mode` feature for Simple MCH;
- With this a disclaimer in the description of Simple MCH was added to advice for the use of `NoClippy` or `XIVAlexander` to avoid the "But it works on our basement servers from our office" mentality that plagues some jobs in the game.
- If someone don't want to run either, HLM is the way to go for it to function properly.
=> [MCH] Simple MCH improvements;

XIVSlothCombo/Combos/PvE/WAR.cs
Some combos were nested in brackets inside another combo. Github once again freaking out over white space
=> [WAR] Combo Nesting Fix

XIVSlothCombo/Combos/CustomComboPreset.cs, XIVSlothCombo/Combos/PvE/PLD.cs
- Reworked `Uptime Feature`
- Will use `Holy Spirit` if you're the appropriate level and not moving or have the `Requiescat` buff.
- Will use `Shield lob` if you're the appropriate level, moving and if you don't have the `Requiescat` buff.
- Changed description in `CustomComboPresets.cs` to properly reflect these changes.
=> [PLD] - Reworked Uptime Feature

XIVSlothCombo/Combos/CustomComboPreset.cs, XIVSlothCombo/Combos/PvE/SGE.cs, XIVSlothCombo/Window/Tabs/Debug.cs
Removed need to target oneself. Will work on self even when no target selected (normal healing behavior).  Soft targets checked for gamepad users.
=> [SGE] Fixed/Enhanced Single Target Heal's Targeting

XIVSlothCombo/Combos/PvE/MNK.cs
Changed `GetCustomIntValue` to `GetCustomFloatValue` since the value is a float.
=> Fixed MNK Demolish/Twin Snakes slider not working correctly.

XIVSlothCombo/XIVSlothCombo.cs
@k-kz It's finally done, redundant IDs are no longer a thing.
*coughs*
[Framework]
- Redundant IDs now cleared on boot.
=> Burn the witches (Redundant ID eliminator)

XIVSlothCombo/Combos/PvE/ALL.cs
ALL_Healer_Raise was affecting Summoner & ALL_Caster_Raise was affecting Scholar due to both classes having the same Resurrection ID. This has been fixed by this PR, _**BUT**_ needs a review. LocalPlayer.ClassJob.Id works as something to check but if there is a better item to check against SCH/SMN.JobID, please let me know
=> [ALL] Bugfix for Global Raise & SCH/SMN

XIVSlothCombo/Combos/CustomComboPreset.cs, XIVSlothCombo/Combos/PvE/SMN.cs, XIVSlothCombo/Window/Functions/UserConfig.cs
- Adjusted `DemiAttackCount` to reset when summoning a demi rather than when the demi expires, this allows damage oGCDs to be used even after a demi has left, but still under searing light.
- Adjusted Demi oGCD priority above Festers/Painflare. (Kept ED/ES above them in priority as well)
- Removed LastComboMove checks for Demi Attacks and replaced them with *specific* phase checks. (This allows for doubleweaving `Astral Flow` and `Enkindle Bahamut` which wasn't possible before due to the LastComboMove checks)
- Removed specific phase checks for pooled damage oGCDs as they only really needed Searing to be used.
- `Searing Light` is now a delayed weave.
- `Energy oGCDs` now follow the burst delay slider setting inside your opener. (first 40s of combat)
- Added specific non-opener code for …
=> Smn burst optimizations

XIVSlothCombo/Window/Functions/Presets.cs
[Framework]
- Preset descriptions with multiple lines are now aligned better with preset numbers.
=> Newline alignment on preset descriptions.

XIVSlothCombo/Combos/CustomComboPreset.cs, XIVSlothCombo/Combos/PvE/SCH.cs, XIVSlothCombo/CustomCombo/Functions/Party.cs, XIVSlothCombo/CustomCombo/Functions/PlayerCharacter.cs
SCH.cs-SCH_DeploymentTactics : DeploymentTactics idles as Adloquium until the party target or self has the Galvanize buff. Recitation is sub option
PlayerCharacter.cs: Added HasCompanionPresent. Clarified HasPetPresent
=> [SCH] Deployment Tactics Feature

XIVSlothCombo/Combos/CustomComboPreset.cs, XIVSlothCombo/Combos/PvE/SMN.cs
- Adjust description of `Ruin IV Combo Option`.
- Changed order of gauge/cooldown checks for swiftcast garuda for personal reading preference.
- Fixed a small bug in swiftcast garuda astral flow checking attunement rather than buff check (bug didn't exist in sps swiftcast garuda)
- removed a newline
- Uses gemshine/precious brilliance during garuda before slipstream while moving if you don't have swiftcast.
- Added ruin4 while moving during garuda if you have no attunement stacks
- Moved Ruin4 movement code above swiftcast demi code for priority.
- added precious brilliance comment to gemshine.
- Adjusted movement Ruin4 and Swiftcast (ifrit and sps swiftcast) to not interfere if you're in mid ifrit combo (Crimson Cyclone > Crimson Strike)
- Removed redundant searing light checks from …
=> [SMN] Movement tweaks for Garuda.

XIVSlothCombo/Combos/CustomComboPreset.cs, XIVSlothCombo/Combos/PvE/DNC.cs
Added `Simple Standard Fill Option`
Added `Simple AoE Standard Fill Option`
Added `Simple Peloton Opener Option`
Fixed `Tech Step` burst threshold ST slider
Fixed `Tech Step` burst threshold AoE slider
Fixed `Flourishing Fan Dance` buffID
Reordered some `Simple Mode` options inside the GUI
Ordered buffs according to section, then buffID
Migrated level checks to `LevelChecked()`
Converted to explicit types
Added extra code comments
Removed unnecessary parentheses/variables/whitespace
Fixed indentation
Type regions to reduce visual clutter
Updated feature/option descriptions
=> [DNC] `LevelChecked()` + Standard Fills + Peloton Pre-pull

XIVSlothCombo/Combos/CustomComboPreset.cs, XIVSlothCombo/Combos/PvE/ALL.cs, XIVSlothCombo/Combos/PvE/WHM.cs
Fixed `Use Tetragrammaton on oGCD Option`
Added lots of types to clean up code
Migrated level check features to `LevelChecked()`
Cleaned up whitespace, comment spacing etc
Tweaked most feature names/descriptions
Reordered all features/options (GUI and internally)
Converted class names missed from #717
Converted many vars to explicit types
Removed unnecessary variables
@NikkoXIV @Tsusai would one of you mind taking a quick look over this, in case I missed anything or made any mistakes? Ty!
=> [WHM] `LevelChecked()` + Cleanup

XIVSlothCombo/Combos/PvE/AST.cs, XIVSlothCombo/CustomCombo/Functions/Misc.cs, XIVSlothCombo/CustomCombo/Functions/Party.cs, XIVSlothCombo/Extensions/ListExtensions.cs, XIVSlothCombo/Extensions/UIntExtensions.cs
AST:
- LevelChecked implemented. 
- Level constants removed. 
- Gauge attached to class for cleaner use.
- AST_Cards_DrawOnPlay
- Randomization to party member selection added.
- Card -> Party selection based on Job IDs (language agnostic)
Misc.cs: Job Names changed to Job IDs.
UIntExtensions.cs: Usage cleanup
Party.cs: VS said it was safe to add a static to the PartyList
ListExtensions.cs: Added. Used for AST's target shuffling.
=> [AST] Cleanup and Card Play enhancements

XIVSlothCombo/Combos/PvE/SMN.cs
- Fix bug that caused second set of festers in a burst phase to go unused.
- Added a priority demi ogcd part to prioritize demi OGCDs if you're late into a demi summon but haven't hit your demi slider count. (still on-weave)
- Removed Rekindle (Phoenix Astral Flow) from following the delay slider, its not an attack.
=> Smn double fester phase fix.

XIVSlothCombo/Combos/CustomComboPreset.cs, XIVSlothCombo/Combos/PvE/SGE.cs, XIVSlothCombo/CustomCombo/Functions/Action.cs, XIVSlothCombo/CustomCombo/Functions/Cooldown.cs
- Action
- Added `ActionReady()`. Combines repetitive Level and Cooldown checks into one function  (works with all actions, including charges)
- Cooldown
- Added "static" to methods
- Cleaned up/sorted action IDs
- Updated for `ActionReady()`
- SGE.Gauge added
- Action List added for `Addersgall` & `Phlegma `
- DoT Dictionary added for `Dosis`/`Eukrasian Dosis debuffs`.
- SGE_ST_Dosis 
- `Toxikon Movement Option`: Cooldown checking added to stop cooldown seizure effect.
- `Eukrasian Dosis`: Level checks no longer required. Now reads the appropriate `Dosis` available, then using DoT dictionary to find it's appropriate debuff
=> [SGE/FRMWRK] Added ActionReady

XIVSlothCombo/Combos/PvE/BRD.cs, XIVSlothCombo/Window/Tabs/PvEFeatures.cs, XIVSlothCombo/Window/Tabs/PvPFeatures.cs
[Framework]
- Only one job heading menu can be open at a time. This is to alleviate FPS issues where too many are open at once.
[BRD]
- Fixes issue where buffs were not being applied with the `Simple Buffs` option selected
=> [MULTI] Preset Menu Change + Bug fix(es)

XIVSlothCombo/Combos/PvE/BRD.cs, XIVSlothCombo/Combos/PvE/MCH.cs
- Fixed an issue of `Gauss` & `Ricochet` hanging up during `Hypercharge` windows;
- Note: at the 1st 2m window you can still hit the cap sometimes, because there is an abundance of resources being generated because you do 3 `Hypercharge`s back to back, thats normal since you cant reliably use them all fast enough, dps should not suffer from that.
- Fixed a bug that prevented the uses of the main Buffs .
- Fixed a missed `canWeave` call for levels lower than `Wanderer Minuet`, on song calls in `Simple Bard`.
=> [MCH & BRD] Bug fixes;

XIVSlothCombo/Combos/CustomComboPreset.cs, XIVSlothCombo/Combos/PvE/SCH.cs
SCH
- Added Class Gauge
- Cleaned up / Sorted ActionIDs
- Internalized fields
- Added Action Lists
- Added Debuff Dictionary
- Combined LevelChecked & IsOffCooldown with ActionReady where needed to cleanup code
- Simplified Features Further
- SCH_Raise
- SCH_FairyReminder (using action list for the future)
- SCH_DeploymentTactics: Recitation Option's description tweaked
- SCH_DPS
- Ruin 2 now has a cooldown check to avoid seizure while oncooldown & moving
- Bio DoT Option now uses usable Bio action checking to determine which Bio DoT to check for, instead of checking by levels. via Debuff Dictionary
=> [SCH] ActionReady Cleanup, Description Edit, Action List & Debuff Dictionary

XIVSlothCombo/Combos/CustomComboPreset.cs, XIVSlothCombo/Combos/PvE/SGE.cs
SGE
* Actions made internal vs public
* Gauge made private, should point to function instead of being function result (Bugfix?) 
* SGE_ST_Dosis
* Toxikon: Clarified/Renamed Toxikon bool per Discord discussion w/ k
* Bugfix: Eukrasia buff check moved higher to encompass DoT & Toxikon code. Toxikon was interrupting Eukrasia/Eukrasia Dosis two button combo.
* SGE_AoE_Heal 
* Bugfix. Didn't do OriginalHook on Physis correctly with ActionReady
* Eukrasia buff check moved to the top to stop replacement actions from breaking the Eukrasia->Eukrasia Prognosis combo
* SGE_ST_Heal:
*  Haima was looking for current target still. Fixed. Ingame configuration will now show the options (Haima, Zoe, etc) in the same order as the code
* Eukrasia buff check moved to the top to stop replacement actions from …
=> [SGE] Bugfix / Light Cleanup

XIVSlothCombo/Combos/PvE/PLD.cs
- `Uptime Feature`
- No longer overwrites `Confiteor` conditions
- Level checks for `Confiteor` added
- Added `InMeleeRange` check to the FoF check
- Changed level checks to `LevelChecked()`
=> [PLD] Uptime Feature fixes & LevelChecked() 

XIVSlothCombo/Combos/CustomComboPreset.cs, XIVSlothCombo/Combos/PvE/SMN.cs
None of these are really *bugs*, but just slight behavior tweaks.
- Adjust comment.
- Remove redundant inopener check for first set of festers as it already checks if you have aetherflow stacks, and ED is either almost (3.2s) off cooldown, or off cooldown. This change allows you to use your first set of festers before your demi oGCDs if you start a fight with aetherflow stacks (dungeon or long downtime in a fight)
- Make `Astral Flow/Enkindle on Demi Summons Feature` work with `Aethercharge`, `Dreadwyrm Trance` as well as `Summon Bahamut` or `Summon Phoenix`. (OriginalHook does *not* work for this.) 
- Make demi astral flows not show up if on cooldown for `Astral Flow/Enkindle on Demi Summons Feature`.
=> [SMN] Small tweaks

XIVSlothCombo/Combos/PvE/SCH.cs, XIVSlothCombo/CustomCombo/Functions/Party.cs
FRMWRK
- Added _IsInParty()_
SCH
- DeploymentTactics feature checks for a party before checking 8 fixed party slots (skipping nulls/disconnecteds)
=> [SCH] Deployment Tactics Party Size Fix

XIVSlothCombo/Attributes/BlueInactiveAttribute.cs, XIVSlothCombo/Attributes/HoverInfoAttribute.cs, XIVSlothCombo/Attributes/ReplaceSkillAttribute.cs, XIVSlothCombo/Core/IconReplacer.cs, XIVSlothCombo/Core/PluginConfiguration.cs, XIVSlothCombo/CustomCombo/CustomCombo.cs, XIVSlothCombo/CustomCombo/Functions/Action.cs, XIVSlothCombo/CustomCombo/Functions/Config.cs, XIVSlothCombo/CustomCombo/Functions/Misc.cs, XIVSlothCombo/CustomCombo/Functions/Movement.cs, XIVSlothCombo/CustomCombo/Functions/Party.cs, XIVSlothCombo/CustomCombo/Functions/PlayerCharacter.cs, XIVSlothCombo/CustomCombo/Functions/Resource.cs, XIVSlothCombo/CustomCombo/Functions/Status.cs, XIVSlothCombo/CustomCombo/Functions/Target.cs, XIVSlothCombo/CustomCombo/Functions/Timer.cs, XIVSlothCombo/Data/ActionWatching.cs, XIVSlothCombo/Data/CooldownData.cs, XIVSlothCombo/Data/CustomComboCache.cs, XIVSlothCombo/Services/BlueMageService.cs, XIVSlothCombo/Services/Service.cs, XIVSlothCombo/Window/ConfigWindow.cs, XIVSlothCombo/Window/Functions/Presets.cs, XIVSlothCombo/Window/Functions/UserConfig.cs, XIVSlothCombo/Window/InfoBox.cs, XIVSlothCombo/Window/Tabs/Debug.cs, XIVSlothCombo/Window/Tabs/PvEFeatures.cs, XIVSlothCombo/Window/Tabs/PvPFeatures.cs, XIVSlothCombo/Window/Tabs/Settings.cs, XIVSlothCombo/XIVSlothCombo.cs
All the chore work and then some
(refer to commit details)
@Taurenkey @Genesis-Nova @Tsusai
=> [Framework] Internal cleanup

XIVSlothCombo/Combos/PvE/DNC.cs
Simply holds the 4th feather and pools it if TS is coming up in the next 5 seconds. Can very rarely overcap but greatly increases the chances of entering TS with 4 pooled feathers instead of 3. I think the potency trade-off to overcap risk is worth it.
=> Simple ST Feather Pooling

XIVSlothCombo/Combos/CustomComboPreset.cs, XIVSlothCombo/Combos/PvP/NINPVP.cs, XIVSlothCombo/Window/Functions/UserConfig.cs
[NINPVP]
- `Burst Mode` and `AoE Burst Mode` no longer conflict with each other. Both can now be used at the same time.
- `Assassinate` will now be used when `Hidden` on `AoE Burst Mode` (to match the functionality of `Burst Mode`).
- `Meisui Feature` added to both `Burst Mode` and `AoE Burst Mode`.
=> [NINPVP] Tweaks and Fixes

XIVSlothCombo/Combos/CustomComboPreset.cs, XIVSlothCombo/Combos/PvE/ALL.cs, XIVSlothCombo/Combos/PvE/BLU.cs, XIVSlothCombo/Combos/PvE/DRK.cs, XIVSlothCombo/Combos/PvE/GNB.cs, XIVSlothCombo/Combos/PvE/RPR.cs, XIVSlothCombo/Combos/PvE/SAM.cs, XIVSlothCombo/Core/PluginConfiguration.cs, XIVSlothCombo/Window/Functions/UserConfig.cs
Added horizontal multiple choice buttons
Added `Physical Ranged DPS: Ranged Interrupt Feature`
Added extra ReplaceSkill hover information
Added `J Kick Option` to `Primal Feature`
Added `Moon Flute Burst Pooling Option` to `Primal Feature`
Added `Sonic Boom Melee Feature`
Added `Perpetual Ray into Sharpened Knife Feature`
Timing adjustments
`Bloodspiller` dumps on the last GCD before `Blood Weapon`/`Delirium`
Added the improved logic from ST to the `Gnashing Fang Combo Feature`
Added `Danger Zone`/`Blasting Zone` to AoE combo
Added `Sonic Break` to AoE combo
Added `Double Down` to `No Mercy`
Added buttons to select skills replaced by `Soulsow Reminder Feature`
Added `Soulsow Reminder Feature` combat check
Added `Communio Movement Feature`
Added `Meikyo Shisui` to both AoE combos
Fixed …
=> Issues Cleanup

XIVSlothCombo/Extensions/BattleCharaExtensions.cs
[Framework]
- Adds the ability to check shield values from a BattleChara object.
- `ShieldPercentage` returns the value for the shield relative to their max HP as a percentage.
- `RawShieldValue` returns an estimate for the actual strength of the shield in HP.
- `HasShield` checks if the shield value is above 0.
=> [Framework] Shield values as BattleChara extension

XIVSlothCombo/Combos/CustomComboPreset.cs, XIVSlothCombo/Combos/PvE/DRG.cs, XIVSlothCombo/Window/Functions/UserConfig.cs, XIVSlothCombo/XIVSlothCombo.cs
Cleaned up simple DRG. Renamed to Advanced.
Removed all the other combo options.
Dives option now on CD, double weave, or single weave.
Added Stardiver Feature: Stardiver turns into Nastrond during Life of the Dragon and Geirskogul outside of it.
Added Lance Charge to Battle Litany Feature, and Dragon Sight sub option.
Added Melee feature for dives.
Redid DRG config. Remind users to check settings.
=> [DRG] Cleanup

XIVSlothCombo/Combos/CustomComboPreset.cs, XIVSlothCombo/Combos/PvE/AST.cs
Removed `Crown Play to Minor Arcana` (deprecated)
Combined `Minor Arcana` / `Lord of Crowns` in `DPS Feature`
Updated `Aspected Helios Feature` for 6.2 changes
Updated feature/option descriptions
=> [AST] 6.2 Changes Only

XIVSlothCombo/Combos/PvE/DRK.cs
Missing parentheses cause conditional exception
If only enable DRK_Bloodspiller without subcombo(DRK_DelayedBloodspiller), bloodspiller will always replace Souleater
=> [DRK] Bugfix: Bloodspiller Feature

XIVSlothCombo/Combos/CustomComboPreset.cs, XIVSlothCombo/Combos/PvE/BLU.cs, XIVSlothCombo/Combos/PvE/GNB.cs, XIVSlothCombo/Combos/PvE/SAM.cs, XIVSlothCombo/Window/Functions/UserConfig.cs
Reimplemented all the code that was lost during the borked merge.
BLU:
Re added BLU_PrimalCombo_Suparnakha, BLU_PrimalCombo_PhantomFlurry, BLU_PrimalCombo_Nightbloom to BLU_PrimalCombo.
SAM:
Re added: 
ST:
Ogi Opener logic tweak to be used before Kasha, 
Meikyo Shisui option now has two choices to use meikyo out of combo or not before Sen Appliers. Meikyo Sticker Spenders able to be used out of combat.
1-2-3 combo logic to use Yukikaze first when both buffs are up. Logic to continue combo when there are 3 sen.
Filler logic unbroken, fast SAM (1.99-2.01) uses double Yukikaze loop for its 4 GCD filler.
Senei option uses Shinten between 70 and 72
Ogi Namikiri being used during the correct even minute burst GCD.
Oka AOE:
Meikyo moved into the two target rotation feature.
GNB:
Re added: …
=> Unbreaking merge problems

XIVSlothCombo/Combos/PvE/BRD.cs
- A little bug on the Simple Bard Opener could make it use `Empyreal Arrow` or `Bloodletter`  before having `Raging Strikes` up, this PR should fix it;
=> [BRD] A little bug on the opener of Simple Bard;

XIVSlothCombo/Combos/CustomComboPreset.cs, XIVSlothCombo/Combos/PvE/AST.cs
LevelChecks, ActionReadys, oh my
Action IDs sorted
Play's SetTarget will check 8 players, skipping null results no matter if light party or full party. If party member `5` was disconnected, it became null, and code would think it's a light party and not search members 6-8
ST_DPS using actionID list and Debuff Dictionary code from SGE/SCH
=> [AST] Cleanup (Post 6.2)

XIVSlothCombo/Attributes/ReplaceSkillAttribute.cs, XIVSlothCombo/CustomCombo/CustomCombo.cs, XIVSlothCombo/CustomCombo/Functions/Action.cs, XIVSlothCombo/CustomCombo/Functions/Movement.cs, XIVSlothCombo/Data/ActionWatching.cs
- ActionWatching
- Added TraitSheet & GetTraitLevel
- Action
- Added GetTraitLevel reference.
- Renamed passed var of LevelChecked from id to actionid to help clarify what's being passed
- ReplaceSkillAttribute
- Removed duplicate ActionSheet. Now references the one from ActionWatching
- Movement
- Added Genesis's IsMoving Code from Discord (Based on and Closes #913 )
- CustomCombo
- Removed CheckMovement(), obsolete.
=> [Framework] TraitSheet/GetTraitLevel/TraitLevelChecked, [ReplaceSkill] Attribute Update, & Genesis's IsMoving Code

XIVSlothCombo/Combos/CustomComboPreset.cs, XIVSlothCombo/Combos/PvE/SCH.cs, XIVSlothCombo/Window/Functions/UserConfig.cs
- SCH
- Gauge now has extension HasAetherflow
- Configs return the user config information instead of holding just a string.
- SCH_DeploymentTactics
- No more hand holding on what can Deployment Tactics can work on.  Aldo only shows when Deployment Tactics is on cooldown.
- SCH_DPS
- [NEW] Energy Drain Weave Option. Uses up Aetherflow stacks when Aetherflow's remaining cooldown is <= user setting (0-10 seconds)
- Ruin II Movement option moved to have less priority than Bio Option
- Better usage of InCombat checking.
- AltMode was nested incorrectly. Added InCombat check to enable DoT prepull
- [NEW] SCH_AoE Feature.  Options are Aetherflow and Lucid Dreaming weaving
=> [SCH] Energy Drain DPS Option, AoE DPS Feature, and code stuff

XIVSlothCombo/Combos/CustomComboPreset.cs, XIVSlothCombo/Combos/PvE/SGE.cs, XIVSlothCombo/CustomCombo/Functions/Action.cs, XIVSlothCombo/Data/ActionWatching.cs, XIVSlothCombo/Window/Functions/UserConfig.cs
Framework
- InActionRange / GetRange added to pull action ranges from ActionWatching. Best used for actions with irregular ranges like Phlegma, but should work with all action range types.
SGE
- Gauge has extensions HasAddersgall & HasAddersting. Used in various existing checks
- Config now directly reads the userconfig values instead of being a string placeholder.
- Phlegma Range constant removed. All references updated for InActionRange(Phlegma)
- SGE_ST_Dosis
- Alternative mode added (Feature runs on Dosis II only. Similar to AST/SCH Alternative Modes)
- Kardia reminder option added
- Phlegma option added. Closes #893 
- SGE_ST_Heal: Ignore Diagnosis Shield Check suboption added to Eukrasian Diagnosis Option. Caveat Emptor. Closes #445 
- SGE_AoE_Heal: Ignore Prognosis Shield Check …
=> [SGE] Features & Code Cleanup

XIVSlothCombo/Combos/PvE/MCH.cs
As the title says , this a 1st pass to account for the gadgets changes to battery behavior on 6.2, this is a 1st pass, the timing could be adjusted later to be tighter if necessary.
=> [MCH] Adjust to gadgets to account for the 6.2 changes , 1st pass;

XIVSlothCombo/Combos/CustomComboPreset.cs, XIVSlothCombo/Combos/PvE/SCH.cs, XIVSlothCombo/Combos/PvE/SGE.cs
SGE: Removed Conflicting Tags from ST & AOE Heal Features vs Rhizo & Dauro Features
SGE Single Target DPS - Toxikon: Removed base action cooldown check. No Seizure effect with new IsMoving
SCH Single Target DPS - Ruin 2: Removed base action cooldown check. No Seizure effect with new IsMoving
=> Minor Tweaks to SCH and SGE

XIVSlothCombo/Combos/CustomComboPreset.cs, XIVSlothCombo/Combos/PvE/DRG.cs, XIVSlothCombo/Combos/PvE/DRK.cs, XIVSlothCombo/Combos/PvE/GNB.cs, XIVSlothCombo/Combos/PvE/RPR.cs, XIVSlothCombo/Combos/PvE/SAM.cs, XIVSlothCombo/Combos/PvE/WAR.cs, XIVSlothCombo/Window/Functions/UserConfig.cs, XIVSlothCombo/XIVSlothCombo.csproj
GNB (Thoroughly tested through the tier):
- Bloodfest cartridge management removed.
- Adjusted opener for 1NM23GF Opener.
- Adjusted timing for 1GCD GF delay at 2 min window.
- Removed GFNM logic from 6.1.
- Added !IsMoving check to melee Rough Divide option.
- Adjusted 30 sec Danger Zones when forced to delay the skill.
- Adjusted Bloodfest burst windows with 6.2 changes.
DRK:
- Reduced Blood overcap management during Blood Weapon from 70 to 60.
DRG:
- Bugfix where Piercing Talon would deactivate the opener if it was the first ability used in combat.
- Fixed Piercing Talon Option on AOE.
RPR:
- Added Opener option that allows for Early Enshroud and Early Gluttony Openers.
- Adjusted Soul management so that Soul is pooled for Gluttony so as to stop Gluttony drift.
- Adjusted Enshroud …
=> Post Raid Adjustments

XIVSlothCombo/Combos/PvE/SMN.cs
- Remove InCombat checks from top level and apply them to only things that require incombat to use. (Demi summonings)
- Add Ruin4 priority usage if demi summon is less than 2.5s remaining (you'll never see this unless you're running a sps build or shenanigans happens (downtime, messed up rotation))
=> [SMN] fixes and requests.

XIVSlothCombo/Combos/CustomComboPreset.cs, XIVSlothCombo/Combos/PvE/DOL.cs
Added feature request from Discord, where Arbor Call (I & II) become Triangulate & Truth of Forests, and Lay of the Land (I & II) become Prospect & Truth of Mountains if the buffs are not active
=> BTN/MIN Request

XIVSlothCombo/Combos/PvE/BLM.cs
Code Cleanup
- Various Trait IDs added.
- Level Constants removed. Substituted with `ActionReady`, `LevelChecked`, and `TraitLevelChecked`
- MP values for various actions will now be pulled from game data instead of constants (except Despair)
- `Gauge` and `HasPolyglotStacks` BLM gauge extension added
- `ThunderList` Dot Debuff Dictionary Added
=> [BLM] Cleanup

XIVSlothCombo/Combos/CustomComboPreset.cs, XIVSlothCombo/Combos/PvE/MNK.cs
#981 inspired me to make my first PR.
Added option to add Meditation chakra builder to Simple Single Target rotation.
Will only use it out of opener/builder, and out of melee range.
Did not add to AoE due to different AoE melee ranges.
=> Monk add Meditation builder out of melee range

XIVSlothCombo/Data/ActionWatching.cs
`GetLevel` now checks if the passed action is a current player action. This makes NPC actions & removed player skill/spell like AST's Crown Play in 6.2, return level 255 instead of 0. This ensures `LevelChecked` returns **False**, and hopefully disables options from firing when skills are removed, versus showing up at all levels.
=> [Framework] GetLevel "Failure" Fix

XIVSlothCombo/Combos/PvE/SGE.cs
Using Dosis, a regular GCD ability, instead of Phlegma, an ability with charges to compare for spellweaving.
=> Fixed Sage AoE Phlega Lucid Weaving.

XIVSlothCombo/Combos/PvE/WAR.cs
- Added a in combat check to both instances of infuriate as using Overpower when out of combat brings Infuriate up when its not usable.
=> [War] Add incombat check to infuriate.

XIVSlothCombo/Data/ActionWatching.cs
Checking what type an action is using row ID instead of English strings.
Any weird issues with LastAbility, LastSpell, LastWeaponskill not working might've been related if user's game was not set to English.
=> [Bugfix/Framework] ActionWatching LastAction fixes for non-English clients

XIVSlothCombo/Combos/CustomComboPreset.cs, XIVSlothCombo/Combos/PvE/NIN.cs
[NIN]
- `Raiton Uptime Feature` added as a suboption to `Throwing Dagger Uptime Feature`.
- `Phantom Kamaitachi Uptime Feature` added as a suboption to `Throwing Dagger Uptime Feature`.
=> NIN uptime features added and fixed

XIVSlothCombo/Attributes/CustomComboInfoAttribute.cs, XIVSlothCombo/CustomCombo/Functions/Misc.cs, XIVSlothCombo/Window/Messages/Messages.cs
Moved JobIDToName back to original location
Fixed Blue Mage Spellbook warning not showing to non-English clients due to recent jobname localization change
=> Jobname Localization Fixes

XIVSlothCombo/Combos/CustomComboPreset.cs, XIVSlothCombo/Combos/PvE/SCH.cs, XIVSlothCombo/Window/Functions/UserConfig.cs
Daemeous:
Fix Scholar Healing and Fairy Combos.
Adds Consolation option to Fairy Combo for use under Seraph.
Changed Lucid Dreaming on Succour to be emergency in case of not enough MP.
Added sub-option to only use Aetherflow if Indomitability is ready,
Naming Parity established with Sage.
Clarified descriptions.
Tartarga:
Fixed Adloquium Bar.
=> [SCH] Heal combo fixes + internal naming parity

XIVSlothCombo/Combos/CustomComboPreset.cs, XIVSlothCombo/Combos/PvE/WHM.cs
Fixed attempting to weave between Holy, by allowing weaves to be used whilst moving or when pressing the Holy button during a weave window from another spell (such as Stone or Aero).
Will now also use Assize right before Holy but after everything else.
Updated descriptions.
=> WHM AoE fixes

XIVSlothCombo/Combos/CustomComboPreset.cs, XIVSlothCombo/Combos/PvE/AST.cs, XIVSlothCombo/Combos/PvE/SCH.cs, XIVSlothCombo/Combos/PvE/SGE.cs, XIVSlothCombo/Combos/PvE/WHM.cs, XIVSlothCombo/Window/Functions/UserConfig.cs
* Healer DoT Refresh Sliders are activated by a sub option now. Default to 3s if not enabled
* WHM: Added DoT Debuff dictionary from other healers for quicker DoT Debuff checking, instead of level checks
=> Changes to Healer DoT refresh timer sliders

XIVSlothCombo/Combos/PvE/SCH.cs
Ruin II's Bio debuff refresh changed to 3 second Threshold.
=> Ruin II's Bio feature fixed

XIVSlothCombo/Combos/PvE/RPR.cs
RPR Regress's FindEffect was returning null errors in Dalamud when the buff did not exist. Code was checking a cooldown against a null.
=> [RPR] Regress null error fix

XIVSlothCombo/CustomCombo/Functions/Action.cs, XIVSlothCombo/Data/ActionWatching.cs
**[Framework]**
Added `GetActionEffectRange()` to grab a zero-range action's radius
Added logic and notes to `InActionRange()` for radius checking
=> [Framework] Upgraded InActionRange for Radius math of Self Targetting actions

XIVSlothCombo/Combos/PvE/RPR.cs, XIVSlothCombo/Window/Functions/UserConfig.cs
Solves various array out of index errors that generate when the option is enabled but no action has been selected (first time user use).
* RPR RPR_Soulsow: Added check to see options is a non-zero array
* UserConfig DrawHorizontalMultiChoice: Better handles first time initialization and resizing.
Closes #1067
=> [RPR] SoulSow Internal fixes

XIVSlothCombo/Combos/PvE/GNB.cs
Option was checking for delayed weave against `Gnashing Fang`.
Now checks against regular GCD action (`Solid Barrel`).
=> [GNB] Fix `No Mercy on Gnashing Fang`

XIVSlothCombo/Combos/CustomComboPreset.cs, XIVSlothCombo/Combos/PvE/GNB.cs, XIVSlothCombo/Window/Functions/UserConfig.cs
- Supports <2.45 SkS and 2.5 SkS rotations.
- Cleaned up internals which means config numbers are fucked but I don't care.
- Burst Strike Features grouped together.
- ST and Gnashing Fang combos support both regular and slow GNB rotations.
- ST now on Keen Edge.
- AoE now on Demon Slice.
=> GNB 3.0 Rework

XIVSlothCombo/Combos/PvE/GNB.cs
Mismatch between `CustomComboPreset` and `GNB`
=> [GNB] Fixed `No Mercy on Gnashing Fang` reference

XIVSlothCombo/Combos/CustomComboPreset.cs, XIVSlothCombo/XIVSlothCombo.cs
Adjusted Feature/Option names + descriptions for parity with rest of plugin.
Reset userbase configs for #1078 internal re-order.
=> [GNB] Feature/Option naming + user config reset

XIVSlothCombo/Combos/CustomComboPreset.cs, XIVSlothCombo/Combos/PvE/RPR.cs
This PR just adds support for holding a charge of True North so it can be used more effectively after Gluttony (2 back to back positionals) , either by using the older True North option or firing it off manually.
=> [RPR] Add option to hold one charge of True North for use with Gluttony

XIVSlothCombo/Combos/CustomComboPreset.cs, XIVSlothCombo/Combos/PvE/DNC.cs, XIVSlothCombo/Window/Functions/UserConfig.cs
• Migrated Simple Modes to `ActionReady()` use
• Added `Simple Saber Dance Option`
• Added `Simple AoE Saber Dance Option`
• Optimised `Esprit` gauge spending near `Technical Step` burst phase
• Added pre-burst protection check to `Saber Dance` use
• Adjusted `Standard Step` priority in differing combat states
• Adjusted `Technical Step` priority in differing combat states
• Adjusted `Devilment` priority in `Simple Dancer (Single Target) Feature`
• Adjusted `Devilment` priority in `Simple Dancer (AoE) Feature`
• Adjusted `Tillana` priority in `Simple Dancer (Single Target) Feature`
• Adjusted `Tillana` priority in `Simple Dancer (AoE) Feature`
• Adjusted `Starfall Dance` priority in `Simple Dancer (Single Target) Feature`
• Adjusted `Starfall Dance` priority in `Simple Dancer (AoE) …
=> [DNC] Adjustments and extra checks

XIVSlothCombo/Combos/CustomComboPreset.cs, XIVSlothCombo/Combos/PvE/SGE.cs, XIVSlothCombo/CustomCombo/Functions/Config.cs, XIVSlothCombo/Window/Functions/UserConfig.cs
@k-kz for your sanity
Your #1062 should be merged first, then #1053 (both are part of this, but just to be safe)
**[Framework]**
Fixed `DrawHorizontalMultiChoice` failing if userdata was did not already exist or not an expected array size
New UserConfig class helpers added
**[SGE]**
Restructured `Alternative DPS Mode` to `Advanced Action Options`
Added `Advanced Action Option` on `Toxikon` (concept from #1042)
Renamed `Toxikon Option` to `Movement Options`
Added use of `Toxikon`, `Dyskrasia` and `Eukrasia` to `Movement Options`
Internal Name cleanup (`SGE_ST_Dosis -> SGE_ST_DPS`, `SGE_AoE_Phlegma -> SGE_AoE_DPS`)
=> [SGE] DPS Revamp

XIVSlothCombo/Combos/CustomComboPreset.cs, XIVSlothCombo/Combos/PvE/SCH.cs, XIVSlothCombo/Combos/PvE/SGE.cs, XIVSlothCombo/CustomCombo/Functions/Status.cs, XIVSlothCombo/CustomCombo/Functions/Target.cs, XIVSlothCombo/Window/Functions/UserConfig.cs
SCH/SGE Single Target Heal
- Targeting code moved to function GetHealTarget
- Optional "Party UI Mouseover Target Checking" added. Does not apply actions to the target. Rejoice ye Redirect/Reaction/moAction healers.
- Esuna Option Added. Detects cleanable debuffs
Framework
- Status: HasCleansableDebuff added. Used for Esuna checking
- Target: GetHealTarget added. Optional checking the Party UI Mouseover Target added by passed parameter.
=> SCH/SGE: Healing Mouseover Electric Boogaloo + Esuna

XIVSlothCombo/Combos/CustomComboPreset.cs, XIVSlothCombo/Combos/PvE/BLM.cs
Discord Request: New feature to replace Aetherial Manipulation with Between the Lines while Ley Lines is active and player is not moving. Movement check exists in case the player needs to use Aetherial Manipulation to someone too far away outside of Ley Lines.
=> [BLM] Aetherial Manipulation Feature

XIVSlothCombo/Combos/CustomComboPreset.cs, XIVSlothCombo/Combos/PvE/SMN.cs
- Added option to check for any searing for bursting rather than just your own.
May solve issues when there is more than one SMN in a group and they're overwriting your searing.
=> [SMN] Added "Burst during Any Searing Light" option

XIVSlothCombo/Combos/PvE/SMN.cs
- Adds Energy Drain to `Simple Summoner`, `Advanced Summoner`, and `Energy Siphon to Painflare Feature` for their respective AoE button if you're high enough level to use Painflare, but too low to use Energy Siphon.
- Small bugfix for ED/ES following burst delay settings prior to unlocking a demi.
=> [SMN] Add Energy Drain to AoE Combo if too low level to use Energy Siphon.

XIVSlothCombo/Combos/PvE/SAM.cs
Minor change to Sam Opener that lets you use 10 extra Kenki if you have it from Prepull or a successful Third Eye during the opener (as almost every boss has a big AoE during your opener to use it on)
=> [SAM] Extra Kenki Utilisation in Opener

XIVSlothCombo/Combos/PvE/MNK.cs
Fixed an issue where snap punch would appear for a split second during opener/when it was time to refresh demolish but it would show up as snap punch for a split second.
=> [MNK] Skill Display Fix 

XIVSlothCombo/Combos/PvE/MNK.cs
When ST function is OFF and Dragon Kick --> Bootshine Feature function is ON, Dragon Kick was switched to Bootshine in all forms, but now it is switched only in FF and Opo-opo forms.
=> [MNK] Changes to the "Bootshine" replacement function

XIVSlothCombo/Combos/CustomComboPreset.cs, XIVSlothCombo/Combos/PvE/DRG.cs, XIVSlothCombo/Combos/PvE/DRK.cs, XIVSlothCombo/Combos/PvE/RPR.cs
DRK:
- Change Delirium being dependent on Blood Weapon and instead delays bursts based on Blood Weapon Stacks being less than 2. Addresses #1002.
DRG:
- ST goes into Chaos Thrust/Chaotic Spring combo if the target doesn't have the dot regardless of if the next chain should be Heavens' Thrust/Full Thrust
- Updated Low Ping Opener to reflect 6.2's changes.
- Added Elusive Jump as an opener trigger, requested in #1081
- ST Combo changed to True Thrust, AoE Combo changed to Doom Spike.
=> [DRK/DRG] Minor changes

XIVSlothCombo/Combos/CustomComboPreset.cs, XIVSlothCombo/Combos/PvE/NIN.cs, XIVSlothCombo/Window/Functions/UserConfig.cs
[NIN]
- Adds `Suiton Uptime` feature to `Advanced Mode - Single Target`.
- Adjusts uptime features to be subfeatures of their respective skill in `Advanced Mode - Single Target`.
- Adds `Pool Charges` feature as a subfeature of `Use Raiton` in `Advanced Mode - Single Target`.
=> [NIN] Uptime feature adjustment + Pooling Option

XIVSlothCombo/Combos/CustomComboPreset.cs, XIVSlothCombo/Combos/PvE/RPR.cs
Added `Void/Cross Reaping Option` to `Gibbet and Gallows Option`
Added `Grim Reaping Option` to `Guillotine Option` Cleaned up names/descriptions
=> [RPR] Further separation of burst options

XIVSlothCombo/Combos/CustomComboPreset.cs, XIVSlothCombo/Combos/PvE/DNC.cs, XIVSlothCombo/Window/Functions/UserConfig.cs
The code now knows its Jetes from its Pirouettes, and its Emboites from its Entrechats.
Added `Fives` increments to sliders
Adjusted single-target `Standard Step` conditions
Adjusted AoE `Standard Step` conditions
Improved ability to weave `Flourish` between dances at higher latencies
Fixed `Standard Step` execution delaying `Flourish`
Prevented `Fan Dance III` from weaving after flourish immediately before burst
Reduced pre-burst overcap potential for `Simple Feather Pooling Option`
Added pre-burst protection to `Simple AoE Feather Pooling Option`
Rewrote all code relating to `Fan Dance` usage in Simple modes
Split and simplified `Fan Dance` code for readability
Fixed `Simple Standard Dance Option` use when in combat
Fixed `Simple AoE Standard Dance Option` use when in combat …
=> [DNC] Semi-rework

XIVSlothCombo/XIVSlothCombo.cs
Adds a line outputting the currently equipped job level for debugging purposes.
=> [Framework] Add `Current Job Level` to debug log

XIVSlothCombo/Combos/CustomComboPreset.cs, XIVSlothCombo/Combos/JobHelpers/RDM.cs, XIVSlothCombo/Combos/PvE/ALL.cs, XIVSlothCombo/Combos/PvE/RDM.cs, XIVSlothCombo/Window/Functions/UserConfig.cs
RDM
* No existing functionality should have been lost, just redone visually. 
* RDM Helper file added. Holds a lot of the shared code for ST & AoE (Melee Finishers, oGCD, Mana Calculator, Lucid Dreaming) 
* RDM DPS Options by default work as a single button full operation
*  Options to change Action binding under an "Advanced Action Options" menu.
* Melee Manification routines nested under Melee Combo routine. 
* Variant Abilities Enabled
ALL
* Added a LucidDreaming helper for the common checks (level, offcooldown, mp, etc).
=> [RDM] Separation of Single and AoE DPS. Variant Support

XIVSlothCombo/Combos/PvE/Content/Bozja.cs
some odd reason I added AS as a buff but not the action ID? OOPS
=> Added missing ID for tanks

XIVSlothCombo/Combos/CustomComboPreset.cs, XIVSlothCombo/Combos/PvE/SCH.cs, XIVSlothCombo/Window/Functions/UserConfig.cs
(holding till prereqs are done)
- Single Target DPS
- Redesigned Alt mode to match Sage's Advanced Options.
- Options redone similarly to Reaper's SoulSow (select actions to bind feature to)
- Bio's action option no longer "idles" as Broil
- Ruin II added as an option
- Removed Feature "Bio on Ruin II"
- Aetherflow Feature
- UI Updates. Excogitation and Indominability now are user options, not preset options
- Deployment Tactics Feature: Code cleanup to use new GetHealTarget code with optional Mouse over checking
=> [SCH] Cleanup

XIVSlothCombo/Combos/CustomComboPreset.cs, XIVSlothCombo/Combos/PvE/SCH.cs, XIVSlothCombo/Window/Functions/UserConfig.cs
[SCH]
* Removed SummonSelene ActionID
* SCH_FairyReminder: Removed UserOption for Eos/Selene choice
* Updated SCH_FairyReminder Preset Description
Goodbye old friend.
=> [SCH] 6.4 Fairy Changes

XIVSlothCombo/Combos/CustomComboPreset.cs, XIVSlothCombo/Combos/JobHelpers/RDM.cs, XIVSlothCombo/Combos/PvE/RDM.cs, XIVSlothCombo/CustomCombo/Functions/Action.cs, XIVSlothCombo/Data/ActionWatching.cs
[RDM]
- Disabled AoE Unbalance Mana Option in UI. Never existed prior to code reorganization, just an accidental addition to the UI. May write it up in RDM at some point.
- AoE Corp-a-Corps: Also an accidental mistake from reorganization. Logic added to make this UI element actually do what it's supposed to do.
[Framework] Added GetActionCastTime. Pulls cast time from Action Sheet
[RDM Helper]
- ManaBalancer.CheckBalance: Replaced HasEffect checks for Verstone and Verfire with buff time remaining checks against their cast time. Stops Casting of VerStone/VerFire under 2 seconds of the buff remaining.
- Combined all forwarding functions under the root class
=> [RDM] Various Fixes

XIVSlothCombo/Combos/PvE/RDM.cs, XIVSlothCombo/Window/Functions/UserConfig.cs
Added Reprise as an optional action to attach Single Target's oGCD Weave to
=> [RDM] Single Target oGCD on Reprise

XIVSlothCombo/Combos/PvE/AST.cs
Replaced ActionReady with LevelChecked per Taurenkey's sleuthing ( Fixes #1231 )
If it was a snake I'd be dead.
=> Bugfix: [AST] Fixed Single Target Combust Checking

XIVSlothCombo/Data/ActionWatching.cs
Past me was a baka and coded stuff as a string instead of by key. Fixed now.
=> Fix "GetAttackType" for non-English clients

XIVSlothCombo/Combos/PvE/Content/Variant.cs
Added zone checking to determine the action IDs of Variant Cure, Rampart, and Spirit Dart
=> Mount Rokkon Variant Fixes

XIVSlothCombo/Combos/PvE/PLD.cs, XIVSlothCombo/Window/Functions/UserConfig.cs, XIVSlothCombo/XIVSlothCombo.csproj
Removed `OriginalHook()` checks on actions without game hooks
Fixed filler window `Atonement` management
Fixed filler window `Holy Spirit` management
Optimised opener `Fight or Flight` GCD timing check
Adjusted non-opener `Fight or Flight` windows to burst off cooldown
Added check to prevent double-weave of `Intervene`
Added oGCD checks to `Intervene` use to optimise action order
Improved `Royal Authority` checks for burst optimisation
`Shield Lob` no longer used unless out of range and MP for `Holy Spirit`
Adjusted gauge check method
Converted level & cooldown checks to `ActionReady`
Adjusted action priority across rotation
Adjusted user config checks
Refactored & cleaned up code
=> [PLD] 6.4 Changes + Optimisation

XIVSlothCombo/Combos/CustomComboPreset.cs, XIVSlothCombo/Combos/PvE/SCH.cs, XIVSlothCombo/Combos/PvE/SGE.cs, XIVSlothCombo/Window/Functions/UserConfig.cs
SGE
- Single Target Diagnosis Healing Edits
- HP% Slider Description Corrected (Closes #1145)
- HP% Slider renamed internally (will be reset)
- Ignore Shield preset suboption replaced as a multi checkbox group
- Added checking for Scholar Galvanize to prevent overwrite
- Buff checking function changed to more appropriate function. Won't reapply in a dual-Sage party
SCH
- Single Target Adloquium's buff checking function changed to more appropriate function. Won't reapply in a dual-scholar party
=> Healer Single Target Shields Fixes/Features

XIVSlothCombo/Combos/PvE/SMN.cs
Pre-level 100 logic fix for smn burst delay, errant ! made check not work as intended..
=> [SMN] Pre-level 100 burst delay logic fix.

XIVSlothCombo/Combos/CustomComboPreset.cs, XIVSlothCombo/Combos/PvE/DRK.cs
=> DRK Support disabling of Action Change, and lower level buffs

XIVSlothCombo/Combos/PvE/SCH.cs
Lowered SCH DPS Movement Priority ( Fixes #1450 )
Chain Stratagem Level Check for Burst Option
Baneful Impaction no longer OriginalHooking due to action replacement being optional
=> [SCH] Fixes (Movement, Baneful)

XIVSlothCombo/Combos/CustomComboPreset.cs, XIVSlothCombo/Combos/PvE/BLU.cs, XIVSlothCombo/Combos/PvE/SGE.cs, XIVSlothCombo/Window/Functions/UserConfig.cs
[SGE]
- Added Addersgall Overflow Protection to ST and AoE DPS paths. Can choose 1-3 gauge to use.
[BLU] 
- Fixed the flute opener not using oGCDs at the correct time.
- Re-ordered and re-phrased most of the features to better align with what users would look for first.
=> SGE and BLU Additions

XIVSlothCombo/Combos/PvE/WHM.cs
Config slider for DPS combo was pointed at the ST healing combo slider, corrected to use the slider in the DPS combo.
=> Fix WHM STDPS Lucid Config Slider

XIVSlothCombo/Combos/CustomComboPreset.cs, XIVSlothCombo/Combos/PvE/PLD.cs, XIVSlothCombo/XIVSlothCombo.csproj
Updated for new July 11 Main changes
=========================
* Adds option to keep Blades of Honor (oGCD) separate from the standard blades combo (all GCD).
* Fix broken Atonement/Holy Spirit "Early Spend"/"Late Spend" configurations
* Add option to change Fight or Flight into Requiescat upon use (keep burst oGCDs on one button)
* Move goring blade after Confiteor combo per Balance recommended rotation
* Adjust other PLD changes from main to avoid bugs when native FoF->Goring Blade "action change" is disabled
=> PLD: more dawntrail adjustments

XIVSlothCombo/Combos/CustomComboPreset.cs, XIVSlothCombo/Combos/PvE/GNB.cs, XIVSlothCombo/Combos/PvP/GNBPVP.cs, XIVSlothCombo/Window/Functions/UserConfig.cs
fixes #1451
fixes #1453
fixes #1461 
fixes #1470 
fixes #1471 
Changelog:
- fixed all issues above
- added Fated Circle option select (similar to Burst Strike)
- removed SkS options entirely
- added new 2.5 opti rotation (1min 2&3cart, 2min 2cart) & very stable
- other shit I'm probably forgetting
=> [GNB] Lv100 fixes & adjustments

XIVSlothCombo/Combos/CustomComboPreset.cs, XIVSlothCombo/Combos/PvE/VPR.cs
Makes the inclusion of Twinfand and Twinblood optional in the Dreadwinder/Pit of Dread replacement selections (for those of us who like to keep our oGCDs on a different button)
Before:
After:
=> VPR: add option to separate dreadwinder/dens ogcds from combo

XIVSlothCombo/Combos/CustomComboPreset.cs, XIVSlothCombo/Combos/PvE/GNB.cs
fixes #1313
fixes #1326 
fixes #1564 
fixes #1570 
Changelog
- reworked entire rotation logic
- cleaned up subLv100 rotations
- fixed Lv90 rotation from 2cart 2min bursting (thank you Kage)
- adjusted actions to better fit with rotation & buff windows
=> [GNB] Full ST Rotation Rework

XIVSlothCombo/Combos/CustomComboPreset.cs, XIVSlothCombo/Combos/PvE/MCH.cs, XIVSlothCombo/Combos/PvE/PLD.cs, XIVSlothCombo/Data/ActionWatching.cs, XIVSlothCombo/Window/Functions/UserConfig.cs, XIVSlothCombo/Window/Tabs/Debug.cs
- fixes WF issue on lvl 100
- fixes 2 min burst
- fixes overcap
- ! changed reassemble order - ppl will have to uncheck and recheck the options they want to have it on !
- various little things
fixes #1381 
fixes #1519 
fixes #1504 
fixes #1534 
fixes #1092
=> MCH Bugfixes

XIVSlothCombo/Combos/CustomComboPreset.cs, XIVSlothCombo/Combos/PvE/PLD.cs, XIVSlothCombo/Window/Functions/UserConfig.cs
- Improved Fight or Flight Logic (ST / AoE)
-- Added target HP% slider option.
-- Only fires if there is enough time to doubleweave Requiescat (if learned).
-- Adjusts for Requiescat coming off cooldown within the next GCD.
-- Now uses it appropriately at lower levels.
- Improved Holy Spirit Logic (ST)
-- Prioritizes delaying Sepulchre before FoF starts.
-- Prioritizes Sepulchre before FoF ends if available.
-- Prioritizes using during FoF, or delays before refreshing Divine Might as a spare out-of-range option.
-- Uses automatically when out of melee range and no better actions are available.
- Improved Atonement Logic (ST)
-- Uses first Atonement as soon as possible.
-- Delays Supplication until after Riot Blade.
-- Prioritizes using Supplication/Sepulchre inside FoF.
- Improved …
=> [PLD] Full Rework (Simple/Advanced)

XIVSlothCombo/Combos/PvE/DRG.cs
fixes #1545 
Changelog:
- small cleanup on Cooldown timers
- Life Surge optimal use (1 in LC, 2 in BL)
- Chaos Thrust level check
=> [DRG] small Lv100 fixes/adjustments

XIVSlothCombo/Combos/CustomComboPreset.cs, XIVSlothCombo/Combos/PvE/WAR.cs, XIVSlothCombo/Window/Functions/UserConfig.cs
fixes #1537 
Changelog
- added Late Primal Rend option that actually works
- nerf to PrimalRendReady fix
- Decimate/Chaotic Cyclone subLv80 break fix
- Storms Eye option select
- Infuriate Charges option select; you can now select how many Infuriate charges to keep ready, works with 2 selected as well for manual use (not sure on the synergy between this and the Infuriate gauge use, however the Charges option will take prio over the Gauge use option
=> [WAR] more Lv100 fixes/adjustments

XIVSlothCombo/Combos/CustomComboPreset.cs, XIVSlothCombo/Combos/PvE/PLD.cs, XIVSlothCombo/Window/Functions/UserConfig.cs
- Reset FoF UserConfig and made it 0% by default. Maximum value now limited to 50% (ST & AoE).
-- _Too many cases of players saying FoF stops being used X minutes into the fight because it defaults to 50%._
- Removed HP threshold slider from Sheltron (ST & AoE).
-- _Largely unnecessary. Now it triggers as long as you're taking damage and the gauge requirement is met._
=> [PLD] UserConfig Tweaks

XIVSlothCombo/CustomCombo/Functions/Target.cs
Added check for new status effect that nullifies directional requirements to `TargetNeedsPositionals()`.
=> [Functions] TargetNeedsPositionals() Fix

XIVSlothCombo/Window/Tabs/PvEFeatures.cs, XIVSlothCombo/Window/Tabs/PvPFeatures.cs
Currently the General/Multi-job Rows under PVE/PVP are easy to miss, as they have no icon and therefore are only the height of the text.
This PR simply adds a minimum size of 32px (scaled with font) to rows without icons, to make these rows consistent with Job Rows, hopefully making them easier to spot.
=> Make General/Multi-job Rows have the same height as other Rows

XIVSlothCombo/Combos/CustomComboPreset.cs, XIVSlothCombo/Combos/PvE/GNB.cs
fixes #1589 
fixes #1595
fixes #1623
fixes #1628 
- Skill Speed can now be used on GNB properly. Multiple fail-safes have been implemented for users who are forced on Skill Speed or just _don't_ want to play 2.5sks
- **Double Down** break fix
- **Gnashing Fang** break fix
- **Reign** combo on **Burst Strike** option select fix
- **Gnashing Fang** option select additions & cleanup
- adjusted actions & added more logic to better fit <2.47sks scenarios, 2.5sks rotation unaffected
- removed CombatDuration code
**NOTE:** _GNB is now only supported for 2.5 (base Skill Speed) issues only. Unless the rotation is breaking or doing absolutely ridiculous stuff, we are no longer accepting issues or suggestions regarding <2.47sks._
=> [GNB] fixes/adjustments

XIVSlothCombo/Combos/CustomComboPreset.cs, XIVSlothCombo/Combos/PvE/DRK.cs, XIVSlothCombo/Window/Functions/UserConfig.cs
=> [DRK] Update Opener, fix action combos are on

XIVSlothCombo/Combos/CustomComboPreset.cs, XIVSlothCombo/Combos/PvE/AST.cs, XIVSlothCombo/Combos/PvE/SCH.cs, XIVSlothCombo/Combos/PvE/SGE.cs, XIVSlothCombo/Window/Functions/UserConfig.cs
Puts draw, out of combat, on top of the dps combos, so you can more easily draw pre pull without another button needed. 
Added ST opener per balance. Will only use one lightspeed delayedweave after combust
Due to this needed to also split ST and aoe into 2 sections. 
Added weave only options to st heals
Dignity, intersection, Ewer, Spire, exaltation
Added Bole and Arrow to st heals, with weave only and health % options. 
Fixed card weave to properly state Balance/spear instead of balance/arrow
Sage overcap fix. Changed the druo to tauro feature into tauro to druo feature. Functionally the same just swapping buttons on a healer bar. But it prevents the overcap from
1 wasting tauro on overcap since it is the tank dr cd
2 blowing 2 charges using a druo and tauro at the same time on overcap …
=> AST Changes, Sage overcap fix, Sch opener fix

XIVSlothCombo/Combos/PvE/SMN.cs
Add 1 GCD delay to searing light.
Add in combat check to demis.
Add logic to Solar/Bahamut checks to force waiting for searing light if pooled ogcds is enabled.
Fix for ST only searing light causing demi ogcds to not go on aoe.
Moved Lux Solaris out of the demi ogcd section, added a < 100% hp check as well as a timer check to ensure it doesn't get wasted.
Should fix #1618 
Addresses #1660
=> [SMN] Demi phase adjustments.

.github/workflows/build.yml
posted as a draft to allow anyone to voice comments or concerns before i convert it to a full pull request
i don't want to take the risk of this being merged before things are tested
I completely understand any hesitation to merging this commit
any testing that anyone would like to be done to lay to rest any fears about broken compatibility from the updated actions are fine with me, there is no rush to have this merged from my point of view
feel free to comment any tests or checks that should be done to make sure nothing is broken
list of changed actions:
1. changed actions/checkout from v2 to v4
2. changed microsoft/setup-msbuild from v1.0.2 to v2
3. changed actions/upload-artifact from v2 to v4
4. changed actions/download-artifact from v2 to v4
=> Update the GitHub Actions File to Remove Warnings

XIVSlothCombo/Combos/PvE/BRD.cs, XIVSlothCombo/CustomCombo/CustomCombo.cs
Fixed issue with Encore not letting the weaves happen, moved encore down. Fixes #1674
Change the song switching logic to use pitch perfect to get rid of stacks as it was occasionally if luck was against you, changing to mage's with rep stacks. It was set to use WM again, which even with action change setup wasn't working. 
Cleaned up the Buff section heavily. Removed the complicated logic that was slowing the use of the 3 main buffs and causing massive drift. Using buffs RS and BV first to reduce risk of drift. 
Added Empyreal arrow cd check to bloodletter of 1 second, so BL wont late weave blocking an empy for a second or so. 
Mimiced in the aoe section.
=> [BRD] Encore fix and cleanup/match to balance standard

XIVSlothCombo/Combos/CustomComboPreset.cs, XIVSlothCombo/Combos/PvE/BRD.cs, XIVSlothCombo/Window/Functions/UserConfig.cs, XIVSlothCombo/XIVSlothCombo.csproj
Fixed pitch perfect issue, not using the skill when buffs are not on cd. Rptd via discord
Also fixed rain of death level check? Fixes #1692 
Fixed st ogcd button, added heartbreak shot. 
Removed the no waste setting turning off opener at the beginning of st combo. It was preventing Initial Empyreal arrow from going off before buffs for standard opener. 
Updated the buff section to tie all 3 buffs together to minimize them drifting apart. getting around 10 seconds of drift over 20 mins now with buffs together.
Rewrote the dot section to be more clear. Ragingjaws is operational, but don't trust xivanalysis as it is looking for it to hit all 3 buffs not just raging. There is a slider for that. set it to 4-5 if that is a problem. fixes #1719 
Apex arrow feature was redundant and not working …
=> [BRD] Fixes and Cleanup

XIVSlothCombo/Combos/CustomComboPreset.cs, XIVSlothCombo/Combos/JobHelpers/SAM.cs, XIVSlothCombo/Combos/PvE/SAM.cs, XIVSlothCombo/Core/IconReplacer.cs, XIVSlothCombo/Data/ActionWatching.cs, XIVSlothCombo/Window/Functions/UserConfig.cs
=> [SAM] Standalone Combo Adjustments

XIVSlothCombo/Combos/CustomComboPreset.cs, XIVSlothCombo/Combos/JobHelpers/PCT.cs, XIVSlothCombo/Combos/PvE/PCT.cs, XIVSlothCombo/Window/Functions/UserConfig.cs
Seems good to go! 
Few things i wanna update later on is re-working the opener code to be all in one piece and not segmented as it is now.
Plus other optimizations to come when i have time to do more testing.
=> [PCT] Lvl 100 Opener, Advanced ST, Advanced AoE 

XIVSlothCombo/CustomCombo/Functions/Status.cs, XIVSlothCombo/Window/Tabs/Debug.cs
- Gave the old debug window a haircut.
- Custom styling makes information more readable.
- Added several new entries of helpful debug information.
- Added several collapsing headers to help keep information organized.
- Status effects on player will now show their respective owners (if one exists).
- Status effects on the target will now show their respective owners (if one exists).
- Added several empty/null checks to handle IDs without a name or a SourceObject.
- Party members are now listed (if present).
=> [Tabs] Debug Window Update

XIVSlothCombo/Combos/CustomComboPreset.cs, XIVSlothCombo/Combos/PvE/BRD.cs, XIVSlothCombo/Combos/PvP/DRGPVP.cs, XIVSlothCombo/Combos/PvP/MCHPVP.cs, XIVSlothCombo/Combos/PvP/WARPVP.cs, XIVSlothCombo/Window/Functions/UserConfig.cs
I plan to do more later, but for now here's a few.
=> [PvP] Rotations & Menu Descriptions overhaul

XIVSlothCombo/Combos/CustomComboPreset.cs, XIVSlothCombo/Combos/PvE/DRK.cs
=> [DRK] Burst Optimizations

XIVSlothCombo/Combos/CustomComboPreset.cs, XIVSlothCombo/Combos/PvE/DNC.cs
(Behavior won't change entirely unless Saber Dance's Esprit slider is >50)
Close #1679
=> [DNC] Add Favor Tillana over Esprit Option

XIVSlothCombo/Combos/PvE/WHM.cs
Now only checks for Medica2/3 buffs owned by the player.
=> [WHM] Fix checking for other WHM's Medicas

XIVSlothCombo/Combos/CustomComboPreset.cs, XIVSlothCombo/Combos/PvP/PCTPVP.cs, XIVSlothCombo/Window/Functions/UserConfig.cs
- Draws and uses motifs when appropriate.
- Includes a burst control option to hold abilities.
- Smart Subtractive Palette usage depending on movement.
- Uses Tempera Coat and converts it into Tempera Grassa before expiring.
=> [PCT PVP] Initial Release

XIVSlothCombo/Combos/PvE/MNK.cs
=> [MNK] fixes/adjustments

XIVSlothCombo/Combos/PvE/PCT.cs, XIVSlothCombo/Window/Functions/UserConfig.cs
Copied the ST advanced mode and removed configuration requirements for an optimized Simple mode
Fixes #1768
=> [PCT] Simple Modes, Motif % stop in advanced

XIVSlothCombo/Combos/CustomComboPreset.cs, XIVSlothCombo/Combos/PvE/AST.cs
Reverted _Added earthly star to the prepull noncombat line with the card draw so you can plant your star before pull_ 
Shifted earthly star a bit higher above the ogcds that cant drift. oracle/arcana
Added tag to not be moving to lay earthly star in aoe to help prevent it wasting during aoe pulls
Added a buff check to the opener for lightspeed to fix rare double cast (discord rpt)
=> [AST] Earthly Star Priority Shift

XIVSlothCombo/Combos/CustomComboPreset.cs, XIVSlothCombo/Combos/PvE/VPR.cs
Removes the action range checks from the Vicepit combo sequence and Reawaken in the AoE combo (simple and advanced), so they will still fire without a target selected.
=> [VPR] Add options to disable range checks in AoE combo

XIVSlothCombo/Combos/CustomComboPreset.cs, XIVSlothCombo/Combos/PvE/NIN.cs, XIVSlothCombo/Window/Functions/UserConfig.cs
=> [NIN] Ninja True North Fixes, Kazematoi dump

XIVSlothCombo/Combos/CustomComboPreset.cs, XIVSlothCombo/Combos/PvE/BRD.cs, XIVSlothCombo/Window/Functions/UserConfig.cs
Raging jaws was not catching the radiant buff for some people. 5 seconds was a tight window. Loosened it significantly so they can even make sure jaws catches other classes buffs that are far less prone to drift.
=> [BRD] Bard fixes

XIVSlothCombo/Combos/CustomComboPreset.cs, XIVSlothCombo/Combos/JobHelpers/SAM.cs, XIVSlothCombo/Combos/PvE/SAM.cs
fixes #1708 
fixes #1767 
fixes #1780
fixes #1789
=> [SAM] fixes/adjustments

XIVSlothCombo/Combos/CustomComboPreset.cs, XIVSlothCombo/Combos/PvE/DNC.cs, XIVSlothCombo/Window/Functions/UserConfig.cs
=> [DNC] Increase the anti-drift for Technical Step

XIVSlothCombo/Combos/PvE/DRK.cs
=> [DRK] Fix Delirium Bloodspiller usage under 96

XIVSlothCombo/Combos/PvE/PCT.cs
Moves the Swiftcast logic to the `IsMoving` code block for Advanced ST and AoE and adds motif level checks to the logic, so it does not waste Swiftcast when synced below motif levels.
This also removes the weave check for Swiftcast, which I believe is fair as a movement option. If this is unacceptable, I can re-add it or make it an option.
=> [PCT] Move Swiftcast logic to IsMoving and add motif level checks

XIVSlothCombo/Combos/CustomComboPreset.cs, XIVSlothCombo/Combos/PvE/WHM.cs
This adds an AoE 'opener', simply doing Swift->Holy, designed to work off of a dungeon pull where you were healing/DoTing during the pull and then come to a stop.
Also conveniently opens a weave window at the beginning of your AoE rotation, for Assize and Presence of Mind to fit into.
=> [WHM] Add AoE 'opener' option

XIVSlothCombo/Combos/CustomComboPreset.cs, XIVSlothCombo/Combos/PvE/PCT.cs, XIVSlothCombo/Window/Functions/UserConfig.cs
As per [The Balance FAQ](https://www.thebalanceffxiv.com/jobs/casters/pictomancer/faq/#q2), Holy is a DPS gain in AoE. Adds a feature to include Holy in White to the AoE combo and a slider to choose how many charges to hold on to.
=> [PCT] Add AoE Holy in White feature

XIVSlothCombo/Combos/PvE/SCH.cs
=> [SCH] Aetherflow Fix

XIVSlothCombo/Combos/PvE/BRD.cs
=> [BRD] Preventing Bloodletter/Rain of death from doubleweaving itself.

XIVSlothCombo/Combos/CustomComboPreset.cs, XIVSlothCombo/Combos/PvE/SAM.cs
* Iaijutsu:
* Handle Kaeshi: Namikiri correctly
* Add Goken checks to Tsubame Gaeshi handling (would not apply at all previously)
* Keep Shoha on Iaijutsu after Kaeshi use (not only if weavable)
* Kyuuten/Shinten: Add option to include Zanshin after Senei/Guren
* Ikishoten: Add option to include Shoha before Ogi Namikiri
@Akechi-kun, could you check if these adjustments are appropriate? I'm trying my hand at my first PR here :)
=> [SAM] Improve Iaijutsu and Ikishoten features
