- XIVComboExpanded/Combos/RPR.cs
- XIVComboExpanded/CustomComboPreset.cs
I did some testing and it seemed to work consistently but I haven't had enough time to test thoroughly with levelsync.
Regarding https://github.com/Nik-Potokar/MyDalamudPlugins/issues/29
> Add Death's Design between combos

- .github/workflows/build.yml
- README.md
Reverts Nik-Potokar/XIVComboWayTooAkiiified#41
> Revert cuz I'm stupid

- XIVComboExpanded/Combos/SCH.cs
- XIVComboExpanded/CustomComboPreset.cs
Added Biolysis/Bio2/(Sorta Bio1) on Ruin II as requested #34. Won't work under level 38 as Ruin II won't be unlocked then.
> ADDED SCHDPSFeature

- XIVComboExpanded/Combos/GNB.cs
> Fixed Hypervelocity issue on Solid Barrel Combo

- XIVSlothCombo/Combos/BRD.cs
Another little refactor to make the function more performant, easier to understand and DRY.
Removed un-necessary braces from if conditionals
Refactored duplicated heavy shot cooldown checks into one variable
Refactored duplicated inCombat checks into blocks
Renamed variables to be camelCase instead of all lowercase, to be consistent with other variables around the codebase
Grouped the useIronJaws check into one single variable to ease readability
Moved level check conditionals to be at the start of the conditionals to save function calls on lower level content
All tested, builds and rotation still working as it was prior to the refactor
Thanks! :)
> chore: refactor SimpleBardFeature in BRD

- XIVSlothCombo/Combos/MCH.cs
Will now work correctly with charges of Reassemble 
#101
> [MCH] MachinistAlternateMainCombo fix 

- XIVSlothCombo/Combos/BRD.cs
Another general tidy up of the BRD file.
Removes obscurity on some variables
Moves level checking to the start of conditionals to optimise lower level content
Removed some optional chaining as the conditional checked for existence
Shored up the formatting a little bit
Added a couple extra level checks in for consistency and some edge cases of "between-levels" content
Grouped up inCombat checks into blocks to limit verbosity
Removed extra braces from some conditionals
Introduced braces in conditions instead of repeating checks
Thanks! <3
> chore: tidy up BRD file

- XIVSlothCombo/Combos/BRD.cs
Corrects wrong song, added pitch perfect spender and moved oGCD's to prioritize song uptime.
> BRD SimpleBard fix and optimization

- XIVSlothCombo/Combos/BRD.cs
- XIVSlothCombo/CustomComboPreset.cs
Adds a simple buffs and also separate radiant finale feature.
Preliminary release, no optimisation, just does them on cooldown when they are available, but after the songs logic.
> feat: bard simple buffs and radiant

- XIVSlothCombo/CustomCombo.cs
Can use this to get health for when to stop DoTs
> DoT health

- XIVSlothCombo/Combos/BLU.cs
- XIVSlothCombo/CustomComboPreset.cs
Added 3 combos for Blue Mage as said in #136:
1. Buffed Song of Torment
2. Moon Flute Opener
3. Final Sting Combo
I've added descriptions of what spells are needed, but essentially it's the load out from Blue Academy and if a user doesn't have those spells it won't break it, eventually I'll go back and make it more friendly to other load outs but for now it's just me sharing my combos.
> BLU Additions

- XIVSlothCombo/Combos/BRD.cs
- XIVSlothCombo/Combos/MCH.cs
- XIVSlothCombo/CustomComboPreset.cs
-Fxed BRD interrupt feature.
-Added MCH Gauss / Ricochet drift prevention feature. Will put on main combo and leave 1 charge of each.
-Added MCH Barrel Stabilizer drift prevention feature. Will add Barrel Stabilizer to main combo is between 5 and 20 heat.
> BRD and MCH stuff

- XIVSlothCombo/Combos/GNB.cs
- XIVSlothCombo/CustomComboPreset.cs
#141
Added different order of oGCDs before you get DD so you don't triple weave
Cleaned up a little bit of the code.
> GNB: Added Burst pre DD

- XIVSlothCombo/Combos/GNB.cs
Fixed sub level 90 issue pointed out in #141.
> Sub level 90 DZ fix

- XIVSlothCombo/Combos/BRD.cs
- XIVSlothCombo/CustomComboPreset.cs
BETA testing for simple bards opener. May have some issues, but some simple testing proved fruitful.
> feat: beta for simple opener

- XIVSlothCombo/Combos/GNB.cs
- XIVSlothCombo/CustomComboPreset.cs
Added opt in features as requested in #141:
- No Mercy on Gnashing Fang
- DD on Gnashing Fang
- CDs on Gnashing Fang
> Added Opt-In Features for Gnashing Fang.

- XIVSlothCombo/Combos/BRD.cs
Fixes a couple opener issues, adding in extra actions and bloodletters. :)
References #188
> fix: brd opener issues

- XIVSlothCombo/Combos/BRD.cs
- XIVSlothCombo/CustomComboPreset.cs
Just adds a conflict flag and a little more info in the desc.
> chore: brd opener tweaks

- XIVSlothCombo/Combos/BRD.cs
Tidies up BRD to use the new methods, like IsOffCooldown, IsOnCooldown and GetCurrentCharges
> chore: tidy up bard to use new methods

- XIVSlothCombo/Combos/PLD.cs
- XIVSlothCombo/XIVSlothCombo.csproj
> [PLD] Rage of Halone lvl checks added

- XIVSlothCombo/Combos/BLU.cs
- XIVSlothCombo/Combos/RPR.cs
- XIVSlothCombo/CustomComboPreset.cs
Features requested in #162.
Fixed Enshrouded bug in #271.
> Blu Requested Features, RPR Bug Fix

- XIVSlothCombo/Combos/DNC.cs
- XIVSlothCombo/CustomComboPreset.cs
[DNC] Features & Fixes
- Replaced all relevant instances of `actionIDCD.IsCooldown` with `CanWeave()` for significantly more reliable clipping protection
- Changes back to GCD skills ~0.7s *before* GCD rolls around, as opposed to ~0.0s
- Left `DancerCombinedDanceFeature` alone for now
- Single Target Multibutton Enhancements:
- Renamed and split `DancerFanDanceOnMainComboFeature`
- `DancerFanDanceMainComboOvercapFeature` (Adds FD1 when feathers are full)
- `DancerFanDance34OnMainComboFeature` (Adds FD3/4 when available)
- Completely revamped Fan Dance Combo Features: #292 
- Hidden `DancerFanDanceCombo` and introduced `DancerFanDanceComboFeatures`
- Added `DancerFanDance1_3Combo` (FD1 -> FD3)
- Added `DancerFanDance1_4Combo` (FD1 -> FD4)
- Added `DancerFanDance2_3Combo` (FD2 -> FD3)
- …
> [DNC] Features & Fixes

- XIVSlothCombo/Combos/NIN.cs
- XIVSlothCombo/CustomComboPreset.cs
Fixed level checks for bunshin for all combos that use it.
> [NIN] Fixed bunshin level checks

- XIVSlothCombo/Combos/NIN.cs
- XIVSlothCombo/ConfigWindow.cs
- XIVSlothCombo/CustomComboPreset.cs
- XIVSlothCombo/PluginConfiguration.cs
Added optional trick attack to `Simple Target`. Also added different `Simple Mudra` paths.
> [NIN] Additional Features

- XIVSlothCombo/Combos/NIN.cs
Bug fixed today's feature adding trick attack as an option on the simple single target.
> Note to self: Don't try to fix stuff when tired. 

- XIVSlothCombo/Combos/DRK.cs
- XIVSlothCombo/Combos/NIN.cs
- XIVSlothCombo/Combos/SCH.cs
- XIVSlothCombo/Combos/SMN.cs
- XIVSlothCombo/CombosPVP/DRKPVP.cs
- XIVSlothCombo/CombosPVP/MCHPVP.cs
- XIVSlothCombo/CombosPVP/PLDPVP.cs
- XIVSlothCombo/CombosPVP/WARPVP.cs
- XIVSlothCombo/ConfigWindow.cs
- XIVSlothCombo/CustomComboPreset.cs
- XIVSlothCombo/PluginConfiguration.cs
Added:
- Function to draw sliders for int and float values easily.
- Slider to SCH Lucid DPS feature.
Removed:
- All `OriginalHook(actionID)` as the default return value.
> Bug fixes and QoL menu updates

- XIVSlothCombo/CustomCombo.cs
- Based on the work Ele did on their PR for AST rework!
> Custom CanWeave with default 0.7 , retaining functionality

- XIVSlothCombo/Combos/MCH.cs
- XIVSlothCombo/CustomComboPreset.cs
- Fix for the AOE feature not calling hypercharge;
- Changed the feature name to `Simple Machinist AOE` , since at this point it is that really xD
> [MCH] Fix for the AOE not calling hypercharge

- XIVSlothCombo/Attributes/CustomComboInfoAttribute.cs
- XIVSlothCombo/Combos/NIN.cs
- XIVSlothCombo/ConfigWindow.cs
- XIVSlothCombo/ConfigWindowFunctions.cs
- XIVSlothCombo/CustomComboPreset.cs
- XIVSlothCombo/PluginConfiguration.cs
Fixes up the NIN Aeolian features plus adds some more QoL to it. Framework for easy config settings started.
Somehow felt slothy by the end, what could it be? 🤔
> NIN Aeolian Fixes and Touchups

- XIVSlothCombo/Combos/BRD.cs
> BRD : Fix to a barrage hangup on simple opener

- XIVSlothCombo/Combos/GNB.cs
- XIVSlothCombo/CustomComboPreset.cs
Refactoring with ClientStructs additions
> GNB: Refactoring and bugfixes

- XIVSlothCombo/Combos/DRG.cs
- XIVSlothCombo/CustomComboPreset.cs
Added High Jump and Mirage toggles to the Full Thrust Combo Plus feature.
Added Simple Dragoon.
> [DRG] Stockh's Simple Dragoon and Full Thrust Combo Plus feature tweaks.

- XIVSlothCombo/Combos/DRG.cs
- XIVSlothCombo/CustomComboPreset.cs
Added Life Surge under buffs feature.
Tweaks and Fixes for Simple Dragoon:
- Weaving windows fixes for Stardiver.
> [DRG] Life Surge feature + Simple Dragoon tweaks.

- XIVSlothCombo/Combos/WAR.cs
- XIVSlothCombo/Combos/WHM.cs
- XIVSlothCombo/ConfigWindow.cs
- XIVSlothCombo/ConfigWindowFunctions.cs
- XIVSlothCombo/CustomComboPreset.cs
Int based sliders can now have values set to increments of 1s, 10s, 100s or 1000s. Still respects min and max values of the slider if they don't lie on the increments.
> Adds increments to int sliders.

- XIVSlothCombo/Combos/AST.cs
- XIVSlothCombo/CustomComboPreset.cs
Adds Celestial Opposition to Aspected Helios feature.
Celestial Opposition -> Aspected Helios -> Helios
> Adds Celestial Opposition to Aspected Helios feature

- XIVSlothCombo/Combos/NIN.cs
- XIVSlothCombo/CustomComboPreset.cs
Address issue #364. Changed Simple AoE to be more like the original AoE feature.
Base feature is the simple 1->2 combo, however will use Huraijin if you don't have Huton buff (it's so minor it shouldn't really be its own feature tbh).
> Addresses #364

- XIVSlothCombo/Combos/DRG.cs
- XIVSlothCombo/CustomComboPreset.cs
Wyrmwind Thrust fix for Simple Dragoon
> [DRG] Simple Dragoon fix.

- XIVSlothCombo/Combos/RDM.cs
- XIVSlothCombo/CustomComboPreset.cs
Per description
"Replaces Jolt with Verstone/Verfire, when proc is available and won't cause severe imbalance"
> [RDM] Added "Jolt into Verproc".

- XIVSlothCombo/Combos/BLM.cs
Update Manafont check in opener to use CD of Manafont.
Update xenoglossy to be used only if enochian has enough time remaining.
> [BLM] Simple Opener Manafont Fix

- XIVSlothCombo/Combos/AST.cs
- XIVSlothCombo/Combos/RDM.cs
- XIVSlothCombo/Combos/SGE.cs
- XIVSlothCombo/Combos/SMN.cs
- XIVSlothCombo/Combos/WHM.cs
- XIVSlothCombo/ConfigWindow.cs
- XIVSlothCombo/ConfigWindowFunctions.cs
- XIVSlothCombo/CustomComboPreset.cs
Sliders for Lucid Dreaming added to each healer. Corrected parent combos. Threw user config settings into seperate function.
> Adds sliders to all healers + File tidying

- XIVSlothCombo/Combos/DRG.cs
- XIVSlothCombo/CustomComboPreset.cs
Fixed three issues with Simple Opener, where the opener would get stuck on Chaotic Spring, Fang and Claw, or Wheeling Thrust.
Added a new Dive feature that doesn't require buffs to fire off.
Code cleaning/optimization.
Localization fixes.
Description updates.
CustomComboPreset.cs overhaul of the DRG section in order to avoid having to edit Feature Numbers from now on.
> [DRG] Simple Opener Fixes, new features, code cleaning, localization and description updates.

- XIVSlothCombo/Combos/DRG.cs
- XIVSlothCombo/CustomComboPreset.cs
Fixed an interaction that would prevent certain abilities from firing off under Simple Dragoon and Simple Opener.
Fixed Simple Dragoon AoE issue that would break the feature.
Fixed missing conflicts and description of features in CustomComboPreset.cs
Sorry K!
> [DRG] General Bugfixes.

- XIVSlothCombo/Combos/AST.cs
- XIVSlothCombo/ConfigWindow.cs
- XIVSlothCombo/CustomCombo.cs
- XIVSlothCombo/CustomComboPreset.cs
Simple Heal:
- Adds Celestial Intersection to single target heal.
- Adds Essential Dignity to single target heal. Allows custom HP Percentage.
AoE Heal:
- Adds Horoscope
> [AST] Simple Heal:

- XIVSlothCombo/Combos/SGE.cs
- XIVSlothCombo/ConfigWindow.cs
- XIVSlothCombo/CustomComboPreset.cs
SageDPSFeatureTest advanced options (including Lucid MP selection) integrated into SageDPSFeature as optional sub options (Stock/Advanced)
> [SGE] Integrated Dosis "Test" after testing

- XIVSlothCombo/Combos/AST.cs
- XIVSlothCombo/CustomComboPreset.cs
fixes #331 & commented out unused variables
> [AST] Fix "Crown Play" Description

- XIVSlothCombo/Combos/AST.cs
- XIVSlothCombo/CustomComboPreset.cs
Adds Exaltation to single target heal.
> [AST] Exaltation

- XIVSlothCombo/Combos/RDM.cs
Bugfix: Verprocs were overriding Scorch/Resolution procs.
> [RDM] RedMageJoltVerprocCombo Fix

- XIVSlothCombo/Combos/DRG.cs
- XIVSlothCombo/CustomComboPreset.cs
Added Life Surge option to the Full Thrust Combo Plus feature.
Simple Dragoon oGCD priority adjustments.
> [DRG] Full Thrust Combo Plus Life Surge Feature and Simple Dragoon adjustments.

- XIVSlothCombo/Combos/BRD.cs
- XIVSlothCombo/Combos/MCH.cs
- XIVSlothCombo/CustomCombo.cs
- XIVSlothCombo/CustomComboPreset.cs
- Fix reassemble max charges for before you getting the upgrade to 2 charges;
- Solves: #411 
- Fix for wildfire uses before lv 90
- Solves: #410  
- Fix for songs being called at the same time with simple songs.
- Solves: #404
> MCH & BRD : Some fixes, details inside.

- XIVSlothCombo/Combos/BLM.cs
- XIVSlothCombo/CustomComboPreset.cs
Updated Polygot usage checks.
Cast Fire3 when at 3 Umbral Hearts regardless of MP.
> [BLM] Update opener to be based on logic instead of steps, add 1 triplecast opener

- XIVSlothCombo/Combos/DRK.cs
- XIVSlothCombo/Combos/PLD.cs
- XIVSlothCombo/ConfigWindow.cs
- XIVSlothCombo/CustomComboPreset.cs
PLD: All on one button for single target.
PLD: All on one button for AoE.
PLD: Atonement Drop fix, now it actually drops the last Atonement stack.
PLD: Expiacion and Circle Of Scorn on both Single target and AoE combo.
PLD: Minor code refactoring.
PLD: Parented all relevant combos.
PLD: Ordered combos to make the menu easier to navigate.
> [PLD] Single target and AoE features

- XIVSlothCombo/Combos/PLD.cs
I accidentally removed the Atonement Feature that uses all stacks, this should bring it back.
> PLD: Atonement Feature fix

- XIVSlothCombo/Combos/MCH.cs
- XIVSlothCombo/CustomCombo.cs
- XIVSlothCombo/CustomComboPreset.cs
- Raising protection parameter for reassemble clipping;
- Adding the ability to "late weave" the 1st wildfire;
> MCH : Raising protection for clipping during hypercharge for reassemble;

- XIVSlothCombo/Combos/DRK.cs
- XIVSlothCombo/Combos/GNB.cs
- XIVSlothCombo/CustomComboPreset.cs
DRK: Optimisation and reordering
GNB: Reorganising combo presets.
> DRK and GNB Optimisations

- XIVSlothCombo/Combos/DRK.cs
DRK: Fixed Souleater Combo bug
> DRK: Bugfixes

- XIVSlothCombo/Combos/PLD.cs
- XIVSlothCombo/Combos/WAR.cs
- XIVSlothCombo/ConfigWindow.cs
- XIVSlothCombo/CustomCombo.cs
- XIVSlothCombo/CustomComboPreset.cs
- XIVSlothCombo/PluginConfiguration.cs
PLD: ST and AOE Refactoring
PLD: Removed Atonement Test features, added slider to Atonement Feature, added slider to Intervene Feature
> PLD: Refactoring

- XIVSlothCombo/Combos/MNK.cs
- XIVSlothCombo/CustomComboPreset.cs
Reverts Nik-Potokar/XIVSlothCombo#450
> Revert "[MNK] Update main combo to have options for CDs and Lunar Solar opener."

- XIVSlothCombo/Combos/MNK.cs
- XIVSlothCombo/CustomComboPreset.cs
This time with the duplicate Meditation enum entry removed.
> [MNK] Update main combo to have options for CDs and Lunar Solar opener.

- XIVSlothCombo/Combos/DRG.cs
- XIVSlothCombo/CustomComboPreset.cs
Removed High Jump into Mirage feature.
> [DRG] 6.1 preliminary changes

- XIVSlothCombo/Combos/ALL.cs
- XIVSlothCombo/Combos/DRK.cs
- XIVSlothCombo/Combos/GNB.cs
- XIVSlothCombo/Combos/SAM.cs
- XIVSlothCombo/Combos/WHM.cs
- XIVSlothCombo/CustomComboPreset.cs
SAM: Kaiten Removed
SAM: Kyuten level changed to 62, Shinten moved to 52
WHM: Minor DPS feature refactoring
> SAM and WHM: 6.1 Compatibility 

- XIVSlothCombo/Combos/BRD.cs
- XIVSlothCombo/CustomComboPreset.cs
- Fixes for the 6.1 Pitch Perfect change.
> BRD :  Fixes for the changes in 6.1

- XIVSlothCombo/CombosPVP/MCHPVP.cs
- XIVSlothCombo/CustomComboPreset.cs
- Trans-AM Mode , 1 button combo.
> MCH : Trans-AM mode (pvp)

- XIVSlothCombo/Combos/DRG.cs
- XIVSlothCombo/ConfigWindow.cs
- XIVSlothCombo/CustomComboPreset.cs
- XIVSlothCombo/XIVSlothCombo.csproj
Melee offset box size fix
Dev beta notice added
`.csproj` updated
DRG 6.1 Compatibility preliminary fixes
DRG minor refactor for S13 to pick up
> v3.0.9.4 Dev Beta

- XIVSlothCombo/Combos/PLD.cs
- XIVSlothCombo/CustomCombo.cs
PLD: Atonement Drop Fix
Framework: this.isMoving Call added. Will check if character is currently moving.
> PLD: Atonement Drop Fix

- XIVSlothCombo/Combos/DRK.cs
- XIVSlothCombo/Combos/GNB.cs
- XIVSlothCombo/Combos/WAR.cs
- XIVSlothCombo/CustomComboPreset.cs
DRK: Fixed issue where Shadowbringer on Main Combo and on oGCD Feature conflicted
WAR: Fixed Infuriate not being used during Inner Release on Infuriate
> DRK: Shadowbringer Conflict Fix

- XIVSlothCombo/Combos/RDM.cs
RedMageJoltVerprocCombo: Commented, cleaned parenthesis
RedMageSwiftVerraise: Code cleanup/optimization, bad use of OriginalHook
> [RDM] Work

- XIVSlothCombo/Combos/SGE.cs
> [SGE] Added Eukrasia level checks to Simple Combos

- XIVSlothCombo/CustomComboPreset.cs
- Quick fix to add IronJaws Apex to the conflict list of Simple Bard.
> BRD : Adding IronJaws Apex feature to the conflict list of Simple Bard.

- XIVSlothCombo/Combos/SMN.cs
Fixes energy drain for aoe combo bug
Adjusts some ogcd checks.
Some formatting fixes.
Big "fixes" are lines 246, 334, 336, 337
> [SMN] Small fixes, checks adjusted.

- XIVSlothCombo/Combos/GNB.cs
- XIVSlothCombo/Combos/PLD.cs
- XIVSlothCombo/Combos/WAR.cs
- XIVSlothCombo/CustomComboPreset.cs
WAR: AOE Parity additions (Infuriate, Inner Release on AOE)
PLD: Fixed issue where uptime features ignored magic combo
GNB: Added tincture check for Burst Strike
> WAR: AOE Parity features with ST

- XIVSlothCombo/Combos/PLD.cs
Atonement Drop Fix.
Expiacion will no longer early weave.
> PLD: Atonement Drop Fix | Expiacion early weave fix

- XIVSlothCombo/Combos/SGE.cs
- XIVSlothCombo/CustomComboPreset.cs
SagePhlegmaFeature: Added suggested refactor from previous pull request
SageDPSFeature: Added Target of Target checking for Dosis Debuff (Discord request)
> [SGE] Small Refactor & DPSFeature Addition

- XIVSlothCombo/Combos/MCH.cs
Added a level check for Heat Blast on main combo and better handling of Gauss/Ricochet logic
> [MCH] Level check and better handling of oGCDs

- XIVSlothCombo/Combos/RPR.cs
`Nightmare Scythe` will no longer take priority over `Guillotine` when certain features are enabled.
Some quick refactoring on `Slice Combo` and `Scythe Combo`.
> [RPR] Fixes & Refactoring

- XIVSlothCombo/Combos/DNC.cs
- XIVSlothCombo/CustomComboPreset.cs
Refactoring
Added `Simple ST` / `Simple AoE` as conflicts to `Flourishing Features` section
> [DNC] Refactor & Conflicts

- XIVSlothCombo/CustomComboPreset.cs
Sets SMN gemshine feature to be a suboption of single target egi.
> Adjust SMN feature description, and tweaks.

- XIVSlothCombo/Combos/SGE.cs
- XIVSlothCombo/CustomComboPreset.cs
Sage.cs-SageDPSFeature: Null target log errors corrected.
Sage.cs-SageSingleTargetHeal: Null target log errors corrected.
Sage.cs API Cleanup, updated "using" headers
CustomComboPreset.cs-Sage: Sorted list, indented as a tree. Last number used written as comment at end.
> Sage Fixes

- XIVSlothCombo/Combos/AST.cs
Fix for [AST] Aspected Benefic feature no longer functioning #553
> Fixes [AST] Aspected Benefic feature no longer functioning #553

- XIVSlothCombo/Combos/DRK.cs
- XIVSlothCombo/CustomComboPreset.cs
DRK: Removal of Opener, readjusted features to do the opener automatically
DRK: oGCD Feature has a dedicated window for Carve and Spit
> DRK: Opener adjustment

- XIVSlothCombo/Combos/GNB.cs
- XIVSlothCombo/Combos/WAR.cs
- XIVSlothCombo/CustomComboPreset.cs
WAR: Sub 50 and 40 Berserk Fixes
GNB: Adjusted Main Combo to emulate the optimal rotation
> WAR: Sub 50 and 40 Berserk fixes

- XIVSlothCombo/Combos/WHM.cs
- XIVSlothCombo/CustomComboPreset.cs
WHM: Fix for Divine Benison not appearing correctly in level capped content.
Note: Math was bad. Bad math!
> WHM oGCD Heals/Shields Fix + Priority option

- XIVSlothCombo/Combos/PLD.cs
- XIVSlothCombo/ConfigWindow.cs
[PLD]
Delays `Fight or Flight` weave by an additional 0.3 seconds to make sure `Goring Blade` doesn't drift outside of `Fight or Flight` window. #534
> PLD Fight or Flight adjustment

- XIVSlothCombo/Combos/ALL.cs
- XIVSlothCombo/Combos/AST.cs
- XIVSlothCombo/Combos/BLM.cs
- XIVSlothCombo/Combos/BLU.cs
- XIVSlothCombo/Combos/BRD.cs
- XIVSlothCombo/Combos/DNC.cs
- XIVSlothCombo/Combos/DRK.cs
- XIVSlothCombo/Combos/GNB.cs
- XIVSlothCombo/Combos/MCH.cs
- XIVSlothCombo/Combos/MNK.cs
- XIVSlothCombo/Combos/PLD.cs
- XIVSlothCombo/Combos/RDM.cs
- XIVSlothCombo/Combos/RPR.cs
- XIVSlothCombo/Combos/SCH.cs
- XIVSlothCombo/Combos/SGE.cs
- XIVSlothCombo/Combos/SMN.cs
- XIVSlothCombo/Combos/WAR.cs
- XIVSlothCombo/Combos/WHM.cs
- XIVSlothCombo/CustomComboPreset.cs
Added all Role Actions except Lucid Dreaming to All.CS
Added Tank Interrupt Feature and Tank Double Reprisal Protection
Switched Alternative and Regular Raise feature names around. Regular Raise feature now found in Global Features for Healer and Casters.
Double Addle Protection, Double Feint Protection, and Double Phys Ranged Mitigation Protection Added.
> ALL: implementation

- XIVSlothCombo/CustomComboPreset.cs
- Reverting regression of conflict of IronJaws Apex with Simple Bard
> [BRD] Reverting regression

- XIVSlothCombo/Combos/SMN.cs
- XIVSlothCombo/ConfigWindow.cs
- XIVSlothCombo/CustomComboPreset.cs
Added `Lucid Dreaming Feature` to ST/AoE combos
Added slider for `Lucid Dreaming Feature`
Minor spacing stuff
> [SMN] Added `Lucid Dreaming` to ST/AoE combos

- XIVSlothCombo/Combos/DRG.cs
- XIVSlothCombo/CustomComboPreset.cs
High Jump level check.
HasEffectAny references changed to HasEffect.
Added True North as opener starter requirement for Simple Opener.
Improved/updated Simple DRG and Simple Opener descriptions.
> [DRG] Feature fixes and description improvement/update.

- XIVSlothCombo/Combos/DRG.cs
- XIVSlothCombo/CustomComboPreset.cs
Fixed `Piercing Talon Uptime Option` on `Simple DRG`
Added `Piercing Talon Uptime Option` to `Simple DRG AoE`
Indentations on `CustomComboPreset.cs`
> [DRG] `Simple Ranged Uptime Options`

- XIVSlothCombo/Combos/RDM.cs
Added `Veraero II` level check to `AoE Combo`
Added `Verthunder II` level check to `AoE Combo`
> [RDM] `AoE Combo` level checks

- XIVSlothCombo/Combos/SCH.cs
- XIVSlothCombo/ConfigWindow.cs
- XIVSlothCombo/CustomComboPreset.cs
CustomComboPreset: Edited / Corrected Description
ConfigWindow: Added Radio buttons for Eos or Selene
SCH: ScholarFairyFeature - Added Eos option based on radio (default)
> [SCH] ScholarFairyFeature Fix/Feature (Low Priority)

- XIVSlothCombo/Combos/PLD.cs
- XIVSlothCombo/ConfigWindow.cs
- XIVSlothCombo/CustomComboPreset.cs
[PLD]
Changed `Atonement Feature` to use all `Sword Oath` stacks
Added  `Atonement Drop Feature` on `Atonement Feature`
Removed `Atonement Slider`
Updated various PLD descriptions
> [PLD] Atonement Feature

- XIVSlothCombo/Combos/PLD.cs
[PLD]
Added additional check to `Confiteor Combo Feature` and `AoE Confiteor Feature` to avoid early `Confiteor` usage.
> [PLD] Early Confiteor fix

- XIVSlothCombo/Combos/PLD.cs
- XIVSlothCombo/Combos/SAM.cs
- XIVSlothCombo/CombosPVP/SAMPVP.cs
- XIVSlothCombo/CustomComboPreset.cs
PLD: Fix for #613 
SAM: Two Target Rotation fix for Meikyo Shisui
SAMPvP: Added Burst Mode to Kasha Combo subfeature
SamPvP: Added AOE Melee Protection
> PLD: Fix for #613

- XIVSlothCombo/Combos/BLM.cs
- XIVSlothCombo/ConfigWindow.cs
- XIVSlothCombo/CustomComboPreset.cs
- XIVSlothCombo/XIVSlothCombo.csproj
Refactor Simple BLM to only use Triplecast if at least x2 Fire4s can fit in
Add custom Astral Fire refresh config
Clean up Simple AoE BLM
Update descriptions and names for everything
> [BLM] Optimizations + Configs

- XIVSlothCombo/Combos/SGE.cs
- XIVSlothCombo/CustomComboPreset.cs
Let me know if I need to make other nomenclature changes before you accept this PR and I'll add it to the branch
Two small fixes too, because I'm an idiot.
> SGE: Appended "Feature" suffix to Main features per K-kz's request

- XIVSlothCombo/Combos/DRG.cs
Fixed an issue with Lance Charge feature adding Battle Litany to the rotation.
Tweaked Battle Litany Feature to make it single weaved, plus removed an unnecessary canWeave from the code.
> [DRG] Feature tweaks.

- XIVSlothCombo/CombosPVP/RPRPVP.cs
- XIVSlothCombo/ConfigWindow.cs
- XIVSlothCombo/CustomComboPreset.cs
Added `Burst Mode`
Added `Grim Swathe Option`
Added `Death Warrant Option`
Added `Plentiful Harvest Opener Option`
Added `Plentiful Harvest + Immortal Sacrifice Pooling Option`
Added `Enshrouded Burst Option`
Added `Enshrouded Death Warrant Option`
Added `Communio Finisher Option`
Added `Ranged Harvest Moon Option`
Added `Arcane Circle Option`
> [RPRPvP] Burst Mode & Options

- XIVSlothCombo/Combos/SGE.cs
Can I offer you a bone for these trying times
> SageSTDosisFeature: Called out by damolitionn for a repeated if check

- XIVSlothCombo/Combos/BLM.cs
- XIVSlothCombo/CustomComboPreset.cs
- Fix overcapped polygot
- Add pooling option for Advanced BLM
> [BLM] Update logic to try to only Sharpcast Thunder

- XIVSlothCombo/Combos/SAM.cs
- XIVSlothCombo/CombosPVP/SAMPVP.cs
SAM: Senei Timer adjusted
SAMPvP: Added missed CanWeave to Soten
> SAM Updates

- XIVSlothCombo/Combos/DNC.cs
- XIVSlothCombo/CustomComboPreset.cs
Nested `Simple Feather Pooling` to remove conflicts
Nested `Simple AoE Feather Pooling` to remove conflicts
> [DNC] Nested Feather Pooling

- XIVSlothCombo/ConfigWindow.cs
Made `EoS MP Management` sliders snap to hundreds.
> [DRK] Slider Fixes

- XIVSlothCombo/Combos/AST.cs
- XIVSlothCombo/ConfigWindow.cs
- XIVSlothCombo/XIVSlothCombo.cs
[UI]
PVP features now in their own tab, seperate from PVE.
> Seperated PVE features from PVP

- XIVSlothCombo/ActionWatching.cs
- XIVSlothCombo/Combos/ADV.cs
- XIVSlothCombo/Combos/ALL.cs
- XIVSlothCombo/CombosPVP/PVPCommon.cs
- XIVSlothCombo/ConfigWindow.cs
- XIVSlothCombo/CustomCombo.cs
- XIVSlothCombo/CustomComboPreset.cs
- XIVSlothCombo/PluginConfiguration.cs
- XIVSlothCombo/XIVSlothCombo.cs
[Framework]
- Moved debug tools from a feature to its own window in the config menu.
- `Output Combat Log` feature now moved to settings.
> Debug Moving

- XIVSlothCombo/Combos/SAM.cs
> SAM: Ogi on Iaijutsu Fix

- XIVSlothCombo/Combos/RPR.cs
- XIVSlothCombo/ConfigWindow.cs
- XIVSlothCombo/CustomComboPreset.cs
> RPRPVP Fixes

- XIVSlothCombo/Combos/BLM.cs
- XIVSlothCombo/Combos/MNK.cs
- XIVSlothCombo/CustomComboPreset.cs
Burst option for Monk & improvement on double weave on forbidden chakra and riddle of fire together.
Fix paradox BLM ley lines option not being applied correctly
Update BLM/MNK formatting & combo ordering
> [BLM/MNK] Updates

- XIVSlothCombo/Combos/BRD.cs
- XIVSlothCombo/CustomComboPreset.cs
- Added a conflict for `MachinistMainCombo` legacy feature with `Simple Machinist`
- Hotfix for BRD `OneButtonSongs` feature.
> [MCH & BRD] Little hotfixes

- XIVSlothCombo/Combos/MNK.cs
> Fix for MNK null errors on Perfect Balance stacks

- XIVSlothCombo/Combos/DNC.cs
- XIVSlothCombo/ConfigWindow.cs
- XIVSlothCombo/CustomComboPreset.cs
- XIVSlothCombo/PluginConfiguration.cs
Renamed all features and options to hurt peoples' brains a little less
> Complete naming reformat

- README.md
- XIVSlothCombo/Attributes/CustomComboInfoAttribute.cs
- XIVSlothCombo/Combos/BLU.cs
- XIVSlothCombo/Combos/BRD.cs
- XIVSlothCombo/Combos/DNC.cs
- XIVSlothCombo/Combos/DOL.cs
- XIVSlothCombo/ConfigWindow.cs
- XIVSlothCombo/CustomCombo.cs
- XIVSlothCombo/CustomComboPreset.cs
All internal naming stuff, just to bring things in line for the debug log, yada yada.
> Feature name formatting

- XIVSlothCombo/CustomComboPreset.cs
`PLD`
Changed `Requiescat Feature` description to indicate usage timing and removed wrong information.
Changed `Holy Spirit Feature` description to indicate usage timing.
> PLD: Changed descriptions to be more descriptive.

- XIVSlothCombo/XIVSlothCombo.csproj
Removed both instances of `FFXIVClientStructs` since we pull from Dalamud's.
Changed `<Authors>` tag to reflect current state of dev team.
> Remove Structs, edit author tag

- XIVSlothCombo/Combos/RPR.cs
- XIVSlothCombo/ConfigWindow.cs
[RPR]
`Shadow of Death` refresh timer fixed. Now works at `0s`
[RPRPvP]
Adjusted `Arcane Circle Option` HP% minimum threshold
> [RPR] [RPRPvP] Fixed/Adjusted sliders

- XIVSlothCombo/Combos/RDM.cs
[RDM]
- Code cleanup: Added line breaks for easier reading
> [RDM] Added line breaks for easier reading

- XIVSlothCombo/ConfigWindow.cs
- XIVSlothCombo/CustomComboPreset.cs
[RDM]
- UI: Changed radio buttons to horizontal layout
> [RDM] Change to horizontal radio buttons

- XIVSlothCombo/ConfigWindowFunctions.cs
- Radio button now selects the first called option if the user has not selected a value.
> Framework Tweaks

- XIVSlothCombo/Combos/SMN.cs
Was trying to use it in low level content before it was usable.
> Add level check for painflare

- XIVSlothCombo/CustomComboPreset.cs
Remove old conflict check related to previous AoE feature design and Auto Card Play
> [AST] AoE/AutoTargetDraw Conflict Fix

- XIVSlothCombo/Combos/BLM.cs
- XIVSlothCombo/ConfigWindow.cs
- XIVSlothCombo/ConfigWindowFunctions.cs
- XIVSlothCombo/CustomComboPreset.cs
- Added Swiftcast/Triplecast usage while moving
- Added Xenoglossy or Scathe usage while moving
- Added a new float slider that uses one decimal digit
> [BLM] Movement feature, Rounded float slider

- XIVSlothCombo/Combos/BLM.cs
> Fixed Paradox hard level check

- XIVSlothCombo/XIVSlothCombo.cs
- Adds version to debug log from `/scombo debug`
- Optional job parameter can be passed to `/scombo debug` to show only features enabled for that job plus globals.
> Debug adjustment

- XIVSlothCombo/Combos/WHM.cs
Puts Misery before Medica 2.
Misery -> Blood Lily (if proced) -> Medica 2 -> Medica 1
> [WHM] Lily fix.

- XIVSlothCombo/Combos/MCH.cs
Somehow my old code went in ... and not the right one...  sry
> MCH - Hotfix

- XIVSlothCombo/Combos/CustomComboPreset.cs
- XIVSlothCombo/Combos/PvE/ALL.cs
- XIVSlothCombo/Combos/PvE/DRK.cs
- XIVSlothCombo/Combos/PvE/GNB.cs
- XIVSlothCombo/Combos/PvE/RPR.cs
- XIVSlothCombo/Combos/PvE/SAM.cs
- XIVSlothCombo/Combos/PvE/SMN.cs
- XIVSlothCombo/Combos/PvE/WAR.cs
Added True North Protection Feature to Global
Added HasBattleTarget() to Uptime Features
Fixed some features not dependent on GNB_ST_MainCombo_CooldownsGroup
> Fixes and Optimisation

- XIVSlothCombo/Combos/CustomComboPreset.cs
- XIVSlothCombo/Combos/PvE/BLM.cs
- Deprecate BLM_Scathe
- Add thunder options to simple/advanced BLM
- Fix overwrite between Thunder III/IV
> [BLM] Thunder Updates

- XIVSlothCombo/Combos/PvE/WHM.cs
Fixed some combos being accidentally nested within other combos
(I literally just fixed a missing } and reduced a tab and idk why github is thinking it's so goddamn complicated)
> [WHM] Nesting Fix

- XIVSlothCombo/Combos/PvE/PLD.cs
- Fix atonement usage so that x2 gets used outside of FoF, and all 3 usages are used under FoF after the stacks have been renewed.
> [PLD] Atonement

- XIVSlothCombo/Combos/PvE/RDM.cs
- XIVSlothCombo/Window/Functions/UserConfig.cs
[RDM]
`AoE Melee Combo` feature
- Added option to include `Moulinet` so you can get the benefits of the `Use Manafication and Embolden` option on `Moulinet` as well.
> RDM - AoE Melee Combo options available on Moulinet

- XIVSlothCombo/Combos/CustomComboPreset.cs
- XIVSlothCombo/Combos/PvE/MNK.cs
Cleaned up some of the file
Removed redundant option
> [MNK] Cleanup + redundancy removal

- XIVSlothCombo/Combos/PvE/DNC.cs
Added some extra code comments
Removed unnecessary variables
Fixed indentation
Type regions to reduce visual clutter
Fixed `Tech Step` burst threshold ST slider
Fixed `Tech Step` burst threshold AoE slider
> [DNC] Fixes & cleanup

- XIVSlothCombo/Combos/PvE/MNK.cs
> Add level check to thunderclap's formless fist buff check

- XIVSlothCombo/Combos/PvE/MCH.cs
This PR should  correct a bug with the mentioned feature that made it unable to work at lvs lower than 84, should all be working now, tested on lv50, lv80 and lv90 content since they are the checkpoints for the skills acquired.
It adds a little tweak to `Simple Machinist` that allows it to do more burst damage if it starts the fight with a lot of resources.
> [MCH] Corrected behaviour of `alt drill/aa/hotspot ` feature

- XIVSlothCombo/Combos/CustomComboPreset.cs
- XIVSlothCombo/Combos/PvE/BLU.cs
Updated code since when I first made it
> BLU Refactoring

- XIVSlothCombo/Combos/CustomComboPreset.cs
- XIVSlothCombo/Combos/PvE/SGE.cs
- XIVSlothCombo/Window/Functions/UserConfig.cs
Implemented LevelChecked
Removed Level Constants
Attached JobGauge to SGE class for easy reading
Tried to clarify AoE (Phlegma) option names, and Single Target Heal HP Percent Sliders
> [SGE] `LevelChecked()` + Cleanup

- XIVSlothCombo/Combos/PvE/RPR.cs
Removed redundant namespaces
Removed whitespace
Migrated level checks to `LevelChecked()`
Comment spacing
Removed level constants
> [RPR] `LevelChecked()` + Cleanup

- XIVSlothCombo/Combos/PvE/BRD.cs
Removed whitespace
Migrated level checks to `LevelChecked()`
Comment spacing
Removed level constants
Removed redundant parentheses
Added regions for var sets
@augporto could you take a glance at this one when you get a min? Ty
> [BRD] `LevelChecked()` + Cleanup

- XIVSlothCombo/Combos/CustomComboPreset.cs
Added missing ConflictingCombo tags to SGE_Rhizo & SGE_DruoTauro per Gib's discord report
> [SGE] Conflicting Combo Fix

- XIVSlothCombo/Combos/CustomComboPreset.cs
- XIVSlothCombo/Combos/PvP/SMNPvP.cs
- XIVSlothCombo/Window/Functions/UserConfig.cs
Added SMNPvP
Added `Burst Mode`
Added `Radiant Aegis Option`
> [SMNPvP] Initial implementation

- XIVSlothCombo/Combos/CustomComboPreset.cs
- XIVSlothCombo/Combos/PvP/RPRPVP.cs
Parentheses cleanup
Explicit type conversion
Update cooldown check methods
Removed unused actionIDs
Removed `this.`
Code readability
Fixed target bind check
Removed `Grim Swathe Option` and baked it in by default
> [RPRPvP] Cleanup

- XIVSlothCombo/Combos/PvE/SAM.cs
SAM_ST_GekkoCombo_Kasha: Added missing level check for Shifu
> [SAM] Bugfix: Missing level check

- XIVSlothCombo/Combos/PvE/AST.cs
[AST]
- `Quick Target Cards` no longer goes crazy on your party list.
- `Quick Target Cards` now works once again in _that_ 8 man trial with trusts.
> AST Card Targeting fixes and adjustments.

- XIVSlothCombo/Combos/PvE/SGE.cs
- XIVSlothCombo/CustomCombo/Functions/Target.cs
FRMWK
* Added HasFriendlyTarget. 
SGE
* Fixed Gauge reference. No functional change but I meant to do a method forward and not a class variable 
* SGE_ST_Dosis_EDosis: Resovlved edge case error where EukrasiaDosis is still available in the half second Eukrasia buff is removed
* SGE_ST_Heal: Implemented HasFriendlyTarget to allow SGE_ST_Heal to work again with AI party members/chocobos
> [SGE] Bugfixes

- XIVSlothCombo/Combos/CustomComboPreset.cs
- XIVSlothCombo/Combos/PvE/SGE.cs
- XIVSlothCombo/Window/Functions/UserConfig.cs
Instead of graying out when Eukrasia is active, Eukrasia will change to user selected Eukrasian Action
> [SGE] Eukrasia Feature

- XIVSlothCombo/Core/IconReplacer.cs
- XIVSlothCombo/Data/ActionWatching.cs
As per the latest Dalamud update, hooks have been updated to the latest implementation. No functional changes.
> Updated obsolete hook implementation

- XIVSlothCombo/Combos/PvE/SAM.cs
[SAM]
- The whole thing has been level checked.
> [SAM] Migration to LevelChecked

- XIVSlothCombo/Combos/PvE/NIN.cs
Todo: Remove when fixed structs are shipped.
> Fixed NIN gauge temporarily

- XIVSlothCombo/Combos/CustomComboPreset.cs
- XIVSlothCombo/Combos/PvE/GNB.cs
- XIVSlothCombo/Combos/PvE/SAM.cs
Fixed `Double Down Option`
Fixed `Sonic Break/Bow Shock Option`
Fixed `Ikishoten on Mangetsu Combo`
Fixed `Hagakure on Mangetsu Combo`
> [GNB & SAM] Fixes

- XIVSlothCombo/Combos/CustomComboPreset.cs
- XIVSlothCombo/Combos/PvE/DRG.cs
Separated various Jump and Mirage Dive statements
Brought back Jump to Mirage Feature
> [DRG] 6.2 Changes (Jump / Mirage Dive Action Divorce)

- XIVSlothCombo/Attributes/CustomComboInfoAttribute.cs
- XIVSlothCombo/Attributes/ReplaceSkillAttribute.cs
- XIVSlothCombo/Combos/CustomComboPreset.cs
- XIVSlothCombo/Combos/PvE/DOL.cs
- XIVSlothCombo/CustomCombo/CustomCombo.cs
Internal stuff
- FSH_Cast is now DolAny.
- DoL class now DOL
- ~~ReplaceSkill tag works with DoL now~~ (Reverted this change in favor of #926 )
[DOL] 
- Level constants removed
- [FSH] Diving features are now under a dedicated Diving Feature as Options. More swapping options added (aimed for a full "mode" swap)
- [BTN/MIN] DOL_Eureka level checks removed. Eureka Buff check is the level check.
> [DOL] Cleanup & Fishing Features

- XIVSlothCombo/Window/Functions/UserConfig.cs
Imported Missing UserConfig Entry from backup
> [SCH] Beta EnergyDrain Fix

- XIVSlothCombo/CustomCombo/Functions/Target.cs
- XIVSlothCombo/Data/ActionWatching.cs
[Global]
- Adds a method to check if the current target requires you to do positionals (i.e open ring, not closed ring).
> [Global] Positional Checker

- XIVSlothCombo/Combos/CustomComboPreset.cs
- XIVSlothCombo/Combos/PvE/SCH.cs
- XIVSlothCombo/Window/Functions/UserConfig.cs
New Features:
- SCH_Lustrate: Change `Lustrate` into `Excogitation` when `Excogitation` is ready.
- SCH_Recitation: Change `Recitation` into one of `Adloquium`, `Succor`, `Indomitability`, and `Excogitation`.
> [SCH] Scholar feature improvement

- XIVSlothCombo/Combos/CustomComboPreset.cs
- XIVSlothCombo/Combos/PvE/ALL.cs
- XIVSlothCombo/Window/Tabs/Debug.cs
Replaces sprint with Isle Sprint on the island
> Sprint to Island Sanctuary Sprint feature

- XIVSlothCombo/Combos/CustomComboPreset.cs
- XIVSlothCombo/Combos/PvE/RPR.cs
- XIVSlothCombo/CustomCombo/Functions/Target.cs
[Global] Positional awareness system
[RPR] Dynamic True North feature using new positional system
> Add support for positonal awareness

- XIVSlothCombo/Combos/CustomComboPreset.cs
- XIVSlothCombo/Combos/PvE/BRD.cs
- XIVSlothCombo/Combos/PvE/DRG.cs
- XIVSlothCombo/Combos/PvE/MCH.cs
- XIVSlothCombo/Combos/PvE/MNK.cs
- XIVSlothCombo/Combos/PvE/NIN.cs
- XIVSlothCombo/Combos/PvE/SAM.cs
- XIVSlothCombo/Window/Functions/UserConfig.cs
Updated and tested all jobs (except BRD which I don't have yet), lowered Nin priority quite a bit to avoid CD drift.
> BRD/DRG/MCH/MNK/NIN/SAM Self-Healing all updated.

- XIVSlothCombo/Combos/PvP/BLMPVP.cs
canweave was firing for everything. Nested after action ID check
> [BLMPvP] CanWeave Fix (Fixes #979)

- XIVSlothCombo/Combos/PvE/SAM.cs
- XIVSlothCombo/Window/Functions/UserConfig.cs
Added a option to stop using Higanbana below a specified Target HP % threshold.
> Samurai Higanbana threshold

- XIVSlothCombo/Combos/PvE/NIN.cs
> Phantom bug fix

- XIVSlothCombo/Combos/PvE/BRD.cs
- XIVSlothCombo/Combos/PvE/NIN.cs
- XIVSlothCombo/Combos/PvE/SAM.cs
Fixed a bug that Git reintroduced whereby SAM and BRD had some AoE and ST Combo Healing Sliders linked.
Fixed brackets on Phantom Kamaitachi.
> Fixed SAM and BRD Combo Healing linked sliders.

- XIVSlothCombo/Combos/PvE/SAM.cs
Added LevelChecked for Hagakure
ActionReady'd Guren
> SAM_AoE_MangetsuCombo Fix

- XIVSlothCombo/Combos/PvE/NIN.cs
Undo my last change to phantom holding whilst fixing the previous bug.
> Refix Phantom Change

- XIVSlothCombo/Combos/PvE/ALL.cs
- XIVSlothCombo/Combos/PvE/BLM.cs
- XIVSlothCombo/Combos/PvE/RDM.cs
> [ALL] LevelChecked/ActionReady

- XIVSlothCombo/Combos/PvE/BRD.cs
- XIVSlothCombo/Combos/PvE/SAM.cs
It was in totally the wrong place and AoE wasn't implemented correctly.
> Bard and Samurai Combo Heal Fixes

- XIVSlothCombo/Combos/CustomComboPreset.cs
- XIVSlothCombo/Combos/PvE/SCH.cs
- XIVSlothCombo/Window/Functions/UserConfig.cs
Adds some healing combos for the Scholar.
Fairy Combo - Whispering Dawn primary 
Fey Illumination -> Fey Blessing -> Whispering Dawn
AOE - Succor Primary 
(Standard Aethorflow and Lucid Dreaming options) - Indomitability (When you have Aethor) -> Succor
Single Target - Physick Primary 
(Standard Aethorflow and Lucid Dreaming options) - Target check ( Soft->Hard->Self) - Adloquim (when they dont have Galvanize or Target HP below whatever percentage you set in options) -> Lustrate (When you have Aethor and the target HP is below whatever percentage you set in options) -> Physick
> [SCH] Heal Combos

- XIVSlothCombo/Attributes/CustomComboInfoAttribute.cs
- XIVSlothCombo/CustomCombo/Functions/Misc.cs
Calls for Job Names will now pull from game.
> Job Name Localization

- XIVSlothCombo/Combos/CustomComboPreset.cs
- XIVSlothCombo/Combos/PvP/RDMPVP.cs
- Adds option to remove frazzle from pvp burst mode.
Addresses #611
> Adds option to remove frazzle from RDMPVP's burst mode.

- XIVSlothCombo/Combos/PvE/AST.cs
- XIVSlothCombo/Combos/PvE/SCH.cs
- XIVSlothCombo/Combos/PvE/SGE.cs
- XIVSlothCombo/Combos/PvE/WHM.cs
- XIVSlothCombo/Window/Functions/UserConfig.cs
Sage and Scholar DoT thresholds now updating.
Improved functionality to accept ~~2 decimal places.~~ -- *changed to 1d.p. - k*
~~Updated descriptions to recommend GCD and how to type in values.~~
Cleaned up pointless brackets.
> [Healers] DoT Thresholds fixed and updated.

- XIVSlothCombo/Combos/CustomComboPreset.cs
- XIVSlothCombo/Combos/PvE/AST.cs
- XIVSlothCombo/Combos/PvE/SGE.cs
- XIVSlothCombo/Combos/PvE/WHM.cs
- XIVSlothCombo/Window/Functions/UserConfig.cs
DoT menus on the other 3 healers
Region'd SGE's Config
Added Green + on those Dot Menus
> Advanced DoT menus on AST/SGE/WHM

- XIVSlothCombo/Combos/PvE/SGE.cs
> Just fixed the Kardion buff ID.

- XIVSlothCombo/Combos/CustomComboPreset.cs
- XIVSlothCombo/Combos/PvE/SGE.cs
- XIVSlothCombo/Window/Functions/UserConfig.cs
Added `Rhizomata Option` to `Single Target DPS Feature`
Added `Rhizomata Option` to `AoE DPS Feature`
Adjusted some feature names/descriptions
Re-ordered ST options (attacks, buffs)
> [SGE] Add `Rhizomata Option` to ST and AoE combos

- XIVSlothCombo/CustomCombo/Functions/Status.cs
Silence, Pacification, Amnesia checks will work for non-English clients
> Localization Tweaks to Debuff Checks

- XIVSlothCombo/Combos/PvE/WHM.cs
- XIVSlothCombo/Window/Functions/UserConfig.cs
* Added Slider to the "Thin Air on Medica Option" to select how many stacks of Thin Air to keep for other uses.
#1064
> [WHM] Requested Feature: Medica Thin Air

- XIVSlothCombo/Combos/CustomComboPreset.cs
- XIVSlothCombo/Combos/PvP/DRKPVP.cs
- XIVSlothCombo/Combos/PvP/PVPCommon.cs
- XIVSlothCombo/Window/Functions/UserConfig.cs
[DRKPVP]
- `Burst Mode` added.
- `Plunge Feature` added.
> [DRKPVP] Implementation of Burst Mode

- XIVSlothCombo/Combos/CustomComboPreset.cs
- XIVSlothCombo/Combos/PvE/MNK.cs
Adds Dynamic True North to Monk.
> [MNK] Dynamic True North

- XIVSlothCombo/Combos/PvE/MNK.cs
Fixed inverted TargetNeedsPositionals() check.
> [MNK] Dynamic True North Check Fix

- XIVSlothCombo/Combos/PvE/MNK.cs
Changed order in if statement for minor efficiency increase.
> [MNK] Dynamic True North minor tweak

- XIVSlothCombo/Combos/PvE/AST.cs
- XIVSlothCombo/Window/Functions/UserConfig.cs
> AST Simple Heal: Added SoftTarget and MO support

- README.md
Fixed link to build badge to reflect GitHub changes
> Fix Readme Build Badge

- XIVSlothCombo/Combos/PvE/AST.cs
- XIVSlothCombo/Data/ActionWatching.cs
- XIVSlothCombo/Window/Tabs/Debug.cs
- XIVSlothCombo/XIVSlothCombo.csproj
- XIVSlothCombo/XIVSlothCombo.json
> API 8 / .NET 7

- XIVSlothCombo/Extensions/Presets.cs
- XIVSlothCombo/Window/Functions/Presets.cs
Fixed Dalamud api issues with GetAttribute extension now being able to return nulls
Silenced variant ui related null warnings
> [Framework] Squashed some null warnings

- XIVSlothCombo/Combos/PvP/GNBPVP.cs
[GNBPvP]
Fixed checks for use of `Gnashing Fang`
> [GNBPvP] Fix `Gnashing Fang`

- XIVSlothCombo/Combos/PvE/DOH.cs
- XIVSlothCombo/Combos/PvE/WAR.cs
[WAR/PLD] LevelChecked Updates, few ActionReadys.
[DOH] Removed unused Levels Class
> [WAR/DOH] LevelChecked Updates, few ActionReadys.

- XIVSlothCombo/Window/Functions/UserConfig.cs
> [RDM] Variant Cure Fix

- XIVSlothCombo/Combos/PvE/AST.cs
- XIVSlothCombo/Combos/PvE/BLM.cs
- XIVSlothCombo/Combos/PvE/BRD.cs
- XIVSlothCombo/Combos/PvE/Content/Bozja.cs
- XIVSlothCombo/Combos/PvE/Content/Variant.cs
- XIVSlothCombo/Combos/PvE/DNC.cs
- XIVSlothCombo/Combos/PvE/DRG.cs
- XIVSlothCombo/Combos/PvE/DRK.cs
- XIVSlothCombo/Combos/PvE/GNB.cs
- XIVSlothCombo/Combos/PvE/MCH.cs
- XIVSlothCombo/Combos/PvE/MNK.cs
- XIVSlothCombo/Combos/PvE/NIN.cs
- XIVSlothCombo/Combos/PvE/PLD.cs
- XIVSlothCombo/Combos/PvE/RDM.cs
- XIVSlothCombo/Combos/PvE/RPR.cs
- XIVSlothCombo/Combos/PvE/SAM.cs
- XIVSlothCombo/Combos/PvE/SCH.cs
- XIVSlothCombo/Combos/PvE/SGE.cs
- XIVSlothCombo/Combos/PvE/SMN.cs
- XIVSlothCombo/Combos/PvE/WAR.cs
- XIVSlothCombo/Combos/PvE/WHM.cs
- XIVSlothCombo/Window/Functions/UserConfig.cs
Created a directory at `/Combos/PvE/Content/` to contain `Bozja.cs` and `Variant.cs`
Updated all relevant namespaces
Removed unnecessary namespaces
> [Framework] Organise content files

- XIVSlothCombo/Combos/CustomComboPreset.cs
- XIVSlothCombo/Combos/PvE/PLD.cs
Fixes ST combo not using Rage of Halone for the combo finisher. Only applies to levels 26-59.
> [PLD] Rework Fix

- XIVSlothCombo/Combos/PvE/Content/Bozja.cs
Added the Pure Essences needed to make role actions work.
> Pure Essence IDs added.

- XIVSlothCombo/Combos/CustomComboPreset.cs
Fixed hotbar icon bug with PvP Global features
> [Framework] Fix PvP Globals display error

- XIVSlothCombo/Combos/PvE/Content/Bozja.cs
Last of the pure essences added for healers and tanks, will be adding the deeps / normals next.
> Pure Essences Added

- XIVSlothCombo/Combos/PvE/SMN.cs
fix could wave more than two abilities during combo
> [SMN] fix triple wave

- XIVSlothCombo/Combos/CustomComboPreset.cs
- XIVSlothCombo/Window/ConfigWindow.cs
Fixed my AST merge breaking the plogon
Also silenced two null warnings
> [Merge Bugfix] Fixed AST Plugin Crash

- XIVSlothCombo/Window/Tabs/Debug.cs
Removed PLD Debug Line from Debug Tab
> Removed PLD Debug Line from Debug Tab

- XIVSlothCombo/Combos/PvE/Content/Bozja.cs
Added meme essences needed for phys ranged cure 2 targetting, added the mana regain buff.
> More Essences / buffs added

- XIVSlothCombo/Combos/PvE/SCH.cs
- XIVSlothCombo/Data/TempSCHGauge.cs
Fixes SCH gauge for 6.4 (until CS update in Dalamud at least)
> Temp SCH gauge fix

- XIVSlothCombo/Combos/PvE/SCH.cs
- XIVSlothCombo/Combos/PvE/SGE.cs
- [SGE] 
- SGE_Rhizo: Rhizomata will no longer replace Taurochole & Kerochole while on cooldown for better tracking of their CD timers
- [SCH] 
- SCH_Aetherflow: Aetherflow will no longer replace Excogitation & Sacred Soil while on cooldown for better tracking of their CD timers
- TmpSCHGauge removed (Dalamud has fixed this)
> [SCH/SGE] Tweaks to Aetherflow/Rhizomata Combos

- XIVSlothCombo/CustomCombo/Functions/Config.cs
[FRMK/RDM] UserBoolArray: Fixed IndexOutOfRangeException occurring with recent RDM oGCD option expansion (Thanks Taurenkey)
> [FRMK/RDM] Fix UserBoolArray IndexOutOfRangeException Issue

- XIVSlothCombo/Combos/CustomComboPreset.cs
- XIVSlothCombo/Combos/PvE/BLU.cs
- Level 80 Moon Flute opener added.
- Old opener left for accessibility purposes.
> New BLU moon flute opener

- XIVSlothCombo/Combos/PvE/RDM.cs
Removed Jolt fallback to Riposte. Sloth at level 1 is pointless
> "Riposte Leak" Fix

- .gitmodules
- XIVSlothCombo.sln
- XIVSlothCombo/Combos/JobHelpers/AST.cs
- XIVSlothCombo/Combos/PvE/BLU.cs
- XIVSlothCombo/Core/IconReplacer.cs
- XIVSlothCombo/Core/PluginAddressResolver.cs
- XIVSlothCombo/Core/PluginConfiguration.cs
- XIVSlothCombo/CustomCombo/Functions/Cooldown.cs
- XIVSlothCombo/CustomCombo/Functions/Party.cs
- XIVSlothCombo/CustomCombo/Functions/PlayerCharacter.cs
- XIVSlothCombo/CustomCombo/Functions/Target.cs
- XIVSlothCombo/Data/ActionWatching.cs
- XIVSlothCombo/Data/CustomComboCache.cs
- XIVSlothCombo/Services/Service.cs
- XIVSlothCombo/Window/ConfigWindow.cs
- XIVSlothCombo/Window/IconTextButton.cs
- XIVSlothCombo/Window/InfoBox.cs
- XIVSlothCombo/Window/Tabs/AboutUs.cs
- XIVSlothCombo/Window/Tabs/PvEFeatures.cs
- XIVSlothCombo/Window/Tabs/PvPFeatures.cs
- XIVSlothCombo/XIVSlothCombo.cs
- XIVSlothCombo/XIVSlothCombo.csproj
- XIVSlothCombo/XIVSlothCombo.json
- To be merged after the patch
> API9 Fixes

- XIVSlothCombo/Combos/CustomComboPreset.cs
- XIVSlothCombo/Combos/PvE/PLD.cs
- XIVSlothCombo/Combos/PvE/SAM.cs
- XIVSlothCombo/Combos/PvE/WAR.cs
- XIVSlothCombo/Core/IconReplacer.cs
- XIVSlothCombo/CustomCombo/Functions/Target.cs
- XIVSlothCombo/Services/Service.cs
- XIVSlothCombo/Window/Functions/UserConfig.cs
- XIVSlothCombo/Window/Tabs/PvEFeatures.cs
Fixes #1274
Fixes #1272 
Possibly Fixes #1262 
Fixes #1260
> More Issue Fixes

- XIVSlothCombo/Combos/PvE/WHM.cs
- XIVSlothCombo/Window/Functions/UserConfig.cs
Added advanced options to remap action ID used for Single Target DPS
Closes #1207 
Closes #703 
All healers at parity
> [WHM] Single Target DPS Advanced Options

- XIVSlothCombo/Combos/CustomComboPreset.cs
- XIVSlothCombo/Combos/PvE/AST.cs
- XIVSlothCombo/Combos/PvE/BRD.cs
- XIVSlothCombo/Combos/PvE/MNK.cs
- XIVSlothCombo/Combos/PvE/PLD.cs
- XIVSlothCombo/Combos/PvE/WAR.cs
- XIVSlothCombo/Combos/PvE/WHM.cs
- XIVSlothCombo/Combos/PvP/WARPVP.cs
- XIVSlothCombo/CustomCombo/Functions/Target.cs
- XIVSlothCombo/Data/ActionWatching.cs
- XIVSlothCombo/Data/CustomComboCache.cs
- XIVSlothCombo/Window/Functions/UserConfig.cs
- XIVSlothCombo/XIVSlothCombo.cs
- XIVSlothCombo/XIVSlothCombo.json
Closes #1280 
Fixes #1297 
Fixes #1298 
Closes #1295
Closes #1300
Resolves #1286
Resolves #1278
Resolves #1270
Fix up WHM ST issues and simplify opener
> Resolved Issues

- XIVSlothCombo/Combos/PvE/AST.cs
- XIVSlothCombo/Combos/PvE/SCH.cs
- XIVSlothCombo/Combos/PvE/SGE.cs
- XIVSlothCombo/Combos/PvE/WHM.cs
- XIVSlothCombo/Window/Functions/UserConfig.cs
Added Esuna HP % Checking for all four healers
> [Healers] Esuna HP % Checking

- XIVSlothCombo/Combos/PvE/SMN.cs
Fixes small issue where Enkindle Solar Bahamut was not included on the Astral Flow/Enkindle on Demis Feature.
> fixes SMN_DemiAbilities not including solar bahamut.

- XIVSlothCombo/Combos/PvE/SGE.cs
> [SGE] Fixed AoE Heal Eukrasia Prognosis

- XIVSlothCombo/Combos/CustomComboPreset.cs
- XIVSlothCombo/Combos/PvE/WAR.cs
- XIVSlothCombo/XIVSlothCombo.cs
- added new actions & buffs
- added Primal Wrath to ST & AOE combo
- added Primal Ruination to ST & AOE combo
- added 1GCD check for after Inner Release for better opti
- amongst other things
> [WAR] Lv100 restoration

- XIVSlothCombo/Combos/PvE/WHM.cs
> WHM Support disabling of Action Change

- XIVSlothCombo/Combos/CustomComboPreset.cs
- XIVSlothCombo/Combos/JobHelpers/RPR.cs
- XIVSlothCombo/Combos/PvE/RPR.cs
- XIVSlothCombo/Window/Functions/UserConfig.cs
- XIVSlothCombo/XIVSlothCombo.cs
added simple modes
clean up advanced mode
add lvl 100 opener
add new skills
> RPR DT changes

- XIVSlothCombo/Combos/CustomComboPreset.cs
- XIVSlothCombo/Combos/JobHelpers/DRG.cs
- XIVSlothCombo/Combos/PvE/DRG.cs
- XIVSlothCombo/Window/Functions/UserConfig.cs
- XIVSlothCombo/XIVSlothCombo.cs
- XIVSlothCombo/XIVSlothCombo.csproj
removed deprecated skills
added new ID's and new skills
added new opener
added new rotation
cleaned up code
fixes #1246 
fixes #1355 
fixes #1240 
fixes #1203 
fixes #1157 
fixes #1144 
fixes #1115 
fixes #743 
fixes #1206 
fixes #1455 
closes #1356
> DRG DT Changes

- XIVSlothCombo/Combos/PvE/AST.cs
Add support for the 96 Aspected Helios upgrade Helios Conjunction.
> [AST] Add Helios Conjunction upgrade support

- XIVSlothCombo/Combos/CustomComboPreset.cs
- XIVSlothCombo/Combos/PvE/WAR.cs
> [WAR] Lv100 fixes & adjustments

- XIVSlothCombo/Combos/PvE/BRD.cs
> Fix for BRD AoE Combo Feature #10

- XIVSlothCombo/Combos/CustomComboPreset.cs
- XIVSlothCombo/Combos/PvE/DNC.cs
- XIVSlothCombo/XIVSlothCombo.cs
- XIVSlothCombo/XIVSlothCombo.csproj
> DNC level 100

- XIVSlothCombo/Combos/CustomComboPreset.cs
- XIVSlothCombo/Combos/PvE/BRD.cs
- XIVSlothCombo/Window/Functions/UserConfig.cs
> Fix BRD's 3-3-12 WM->MB->AP for Single Target

- XIVSlothCombo/Combos/PvE/SMN.cs
> Fixes SMN_EDFester feature not applying to Necrotize.

- XIVSlothCombo/Combos/CustomComboPreset.cs
- XIVSlothCombo/Combos/JobHelpers/RPR.cs
- XIVSlothCombo/Combos/PvE/RPR.cs
- fixes 2 min burst
- fixes SoD spam
- fixes Perfectio not going off
- fixes priorities
fixes #1531 
fixes #1528 
fixes #1517 
fixes #1515 
fixes #1512 
fixes #1376 
fixes #1290 
fixes #1093 
fixes #1535 
Fixes #1546
fixes #1550 
fixes #1551 
fixes #1554 
fixes #1556 
fixes #1563 
Fixes #1566
fixes #1567
> RPR bugfixes

- XIVSlothCombo/Combos/CustomComboPreset.cs
- XIVSlothCombo/Combos/JobHelpers/VPR.cs
- XIVSlothCombo/Combos/PvE/VPR.cs
- XIVSlothCombo/Window/Functions/UserConfig.cs
- fix 2 min not always under noxious gnash
- add TN to dreadwinder
- cleanup
fixes #1510 
fixes #1514 
fixes #1516 
fixes #1540 
fixes #1527 
fixes #1490 
fixes #1541 
fixes #1506
> VPR Bugfixes

- XIVSlothCombo/Combos/PvE/WHM.cs
- XIVSlothCombo/Window/Functions/UserConfig.cs
> [WHM] Fix for Cure III's minimal/non use

- XIVSlothCombo/Combos/CustomComboPreset.cs
- XIVSlothCombo/Combos/JobHelpers/VPR.cs
- XIVSlothCombo/Combos/PvE/VPR.cs
- XIVSlothCombo/Window/Functions/UserConfig.cs
- removed Noxious Gnash
- simplified the reawaken usage
- added honed buffs
- renamed skills to new names
fixes #1650
> [VPR] Update to 7.05

- XIVSlothCombo/Combos/PvE/SCH.cs
- XIVSlothCombo/Window/Functions/UserConfig.cs
> [SCH] AoE Heal Lucid Dreaming Fix

- XIVSlothCombo/Combos/PvE/WAR.cs
fixes #1592 
fixes #1591 
fixes #1668 
fixes #1677 
- Primal Rend ST & AOE disabled option fix
- Fell Cleave subLv80 break fix
> [WAR] fixes/adjustments

- XIVSlothCombo/Combos/CustomComboPreset.cs
- XIVSlothCombo/Combos/PvE/WHM.cs
- XIVSlothCombo/Window/Functions/UserConfig.cs
Due to the addition of glare 4 and wanting to PoM asap on trash pulls, I added an option check for weaving PoM in the aoe combo.
> Adds Pom Option to weave only or not for aoe

- XIVSlothCombo/Combos/CustomComboPreset.cs
- XIVSlothCombo/Combos/JobHelpers/RDM.cs
- XIVSlothCombo/Combos/PvE/RDM.cs
- add RDM lvl 100 opener
- moved opener to Jobhelper
fixes #1572
> [RDM] Add lvl 100 opener

- XIVSlothCombo/Combos/CustomComboPreset.cs
- XIVSlothCombo/Combos/PvE/PLD.cs
- XIVSlothCombo/Window/Functions/UserConfig.cs
- Fixed Requiescat sometimes not double-weaving properly.
- Fixed Confiteor not being used if the Requiescat effect expired.
- Fixed Fight or Flight sometimes being delayed by other abilities.
- Fixed Goring Blade sometimes not being used before its effect expired.
- Fixed Blade of Honor sometimes not being used before its effect expired.
- Fixed Sheltron not being used during Requiescat despite having time to weave.
- Fixed Variant Spirit Dart not being used outside of melee range.
- Fixed Variant Cure not being used without a target.
- Fixed Holy Spirit / Holy Circle not being used during Requiescat at lower levels.
- Improved response time of certain actions that relied on status checks.
- MP Reservation will no longer prevent Goring Blade from being used.
- Fixed Intervene Option …
> [PLD] Paladin Revision 2

- XIVSlothCombo/Combos/CustomComboPreset.cs
- XIVSlothCombo/Combos/PvP/PVPCommon.cs
- XIVSlothCombo/Combos/PvP/VPRPVP.cs
- Uses Serpent's Tail when appropriate.
- Uses Reawakened combos (Generations and Legacies) and Ouroboros after Limit Break.
- Uses Hunter's Snap / Swiftskin's Coil on cooldown for consistent damage and buff upkeep.
- Uses Uncoiled Fury when out of Hunter's Snap charges or when target is out of melee range.
- Happy PvP'ing!
> [VPR PVP] Initial Release

- XIVSlothCombo/Combos/CustomComboPreset.cs
- XIVSlothCombo/Combos/JobHelpers/VPR.cs
- XIVSlothCombo/Combos/PvE/VPR.cs
- XIVSlothCombo/Window/Functions/UserConfig.cs
- XIVSlothCombo/XIVSlothCombo.csproj
- revamped AoE
- made reawaken more compact
- made vicewinder autopick depending on position
- made ogcd's behave better
fixes #1652 
fixes #1658 
fixes #1673
> [VPR] Refactor ST

- XIVSlothCombo/Combos/CustomComboPreset.cs
> [GNB] Descriptions rewrite

- XIVSlothCombo/Combos/CustomComboPreset.cs
- XIVSlothCombo/Combos/JobHelpers/RDM.cs
- XIVSlothCombo/Combos/PvE/ALL.cs
- XIVSlothCombo/Combos/PvE/RDM.cs
- XIVSlothCombo/Window/Functions/UserConfig.cs
- RDM Helper Cleanup
- Prefulgence moved from oGCD to Finisher
- VerRaise features (RDM & All) include throwing in a VerCure
> [RDM] VerRaise / Prefulgence Tweaks

- XIVSlothCombo/Combos/JobHelpers/DRG.cs
- XIVSlothCombo/Combos/PvE/DRG.cs
> [DRG] Fixes/Cleanup

- XIVSlothCombo/Combos/CustomComboPreset.cs
- XIVSlothCombo/Combos/PvE/AST.cs
> [AST] Fixes, Earthly Star

- XIVSlothCombo/Combos/CustomComboPreset.cs
- XIVSlothCombo/Combos/JobHelpers/AST.cs
- XIVSlothCombo/Combos/JobHelpers/NIN.cs
- XIVSlothCombo/Combos/PvE/AST.cs
- XIVSlothCombo/Combos/PvE/NIN.cs
- XIVSlothCombo/Window/ConfigWindow.cs
- XIVSlothCombo/Window/Functions/Presets.cs
- XIVSlothCombo/Window/Functions/UserConfig.cs
- XIVSlothCombo/Window/Tabs/Debug.cs
- XIVSlothCombo/Window/TargetHelper.cs
- XIVSlothCombo/XIVSlothCombo.cs
> [NIN] DT Update

- XIVSlothCombo/Combos/JobHelpers/RPR.cs
- XIVSlothCombo/Combos/PvE/RPR.cs
> [RPR] Optimizations and bugfixes

- XIVSlothCombo/Combos/CustomComboPreset.cs
- XIVSlothCombo/Combos/PvE/SGE.cs
- fix lvlcheck opener
- update text on when opener is available
> [SGE] opener lvlcheck fix

- XIVSlothCombo/Combos/JobHelpers/MCH.cs
- XIVSlothCombo/Combos/PvE/MCH.cs
- Update Queen usage for even and odd minutes
- Cleanup of code
- closes #1737 
- closes #1724 
- closes #1720 
- closes #1548 
- closes #1452 
- closes #1353 
- closes #650
> [MCH] Queen update

- XIVSlothCombo/Combos/PvE/BRD.cs
Fixed barrage buff not being accounted for on heavy to ss feature
Fixes #1741
> [BRD] Heavy to SS barrage fix

- XIVSlothCombo/Combos/PvE/VPR.cs
> [VPR] fixes/adjustments

- XIVSlothCombo/Combos/PvE/DRG.cs
> [DRG] little fixes

- XIVSlothCombo/Combos/PvE/ALL.cs
- XIVSlothCombo/Combos/PvE/SCH.cs
- XIVSlothCombo/Window/Functions/UserConfig.cs
Fixes AoE Lucid Slider again, and weave
Closes Discord Report
> [SCH] AoE Heal Lucid Fixes

- XIVSlothCombo/Combos/PvE/GNB.cs
> [GNB] fixes/adjustments

- XIVSlothCombo/Combos/JobHelpers/MCH.cs
- XIVSlothCombo/Combos/PvE/MCH.cs
> [MCH] Optimizations

- XIVSlothCombo/Combos/JobHelpers/DRG.cs
- XIVSlothCombo/Combos/JobHelpers/RPR.cs
- XIVSlothCombo/Combos/PvE/DRG.cs
- XIVSlothCombo/Combos/PvE/RPR.cs
> [RPR] & [DRG] Little fixes

- XIVSlothCombo/Combos/CustomComboPreset.cs
- XIVSlothCombo/Combos/JobHelpers/SCH.cs
- XIVSlothCombo/Combos/JobHelpers/SGE.cs
- XIVSlothCombo/Combos/PvE/SCH.cs
- XIVSlothCombo/Combos/PvE/SGE.cs
- XIVSlothCombo/Window/Functions/UserConfig.cs
Added priority system from Sage with Excogitation and Protraction
Cleaned up SGEHelper while referencing it.
> [SCH] Single Target Heal Priority

- XIVSlothCombo/Window/Icons.cs
Icons for "All" and "DoL" added
> [Core] Add missing class Icons

- XIVSlothCombo/XIVSlothCombo.cs
Added VPR and PCT to /scombo debug
> [Core] Added VPR and PCT to /scombo debug

- XIVSlothCombo/Combos/CustomComboPreset.cs
- XIVSlothCombo/Combos/PvE/WHM.cs
> [WHM] Remove unnecessary Medica III option

- XIVSlothCombo/Combos/CustomComboPreset.cs
- XIVSlothCombo/Combos/PvE/VPR.cs
- XIVSlothCombo/Window/Functions/UserConfig.cs
Adds Variant Cure and Variant Rampart options to VPR's advanced modes.
> [VPR] Add variant action options

- XIVSlothCombo/Window/Functions/Presets.cs
- XIVSlothCombo/Window/Tabs/PvEFeatures.cs
> [Core] Fix issue with nonfunctional Variant Options

- XIVSlothCombo/Combos/CustomComboPreset.cs
- XIVSlothCombo/Combos/PvE/PCT.cs
- XIVSlothCombo/Window/Functions/UserConfig.cs
Adds Variant Cure and Variant Rampart options to PCT's advanced modes.
> [PCT] Add variant action options

- XIVSlothCombo/Combos/JobHelpers/MNK.cs
- XIVSlothCombo/Combos/PvE/MNK.cs
> [MNK] 2 little fixes

- XIVSlothCombo/Combos/JobHelpers/MCH.cs
- XIVSlothCombo/Combos/PvE/MCH.cs
> [MCH] Cleanup + Refactoring

- XIVSlothCombo/Combos/JobHelpers/MNK.cs
- XIVSlothCombo/Combos/PvE/MNK.cs
- make PB combo activate without option
(option should not be on there)
- General Cleanup
> [MNK] PB Update

- XIVSlothCombo/Combos/CustomComboPreset.cs
- XIVSlothCombo/Combos/JobHelpers/VPR.cs
- XIVSlothCombo/Combos/PvE/VPR.cs
> [VPR] Refactor + Add twinfang/blood option

- XIVSlothCombo/Combos/CustomComboPreset.cs
- XIVSlothCombo/Combos/JobHelpers/RPR.cs
- XIVSlothCombo/Combos/PvE/RPR.cs
> [RPR] few fixes

- XIVSlothCombo/Combos/JobHelpers/DRG.cs
- XIVSlothCombo/Combos/PvE/DRG.cs
> [DRG] Cleanup + Fixes

- XIVSlothCombo/Combos/PvE/DRK.cs
- XIVSlothCombo/Window/Functions/UserConfig.cs
> [DRK] Add HP% Threshold for DRK's Delirium

- XIVSlothCombo/Combos/JobHelpers/BLM.cs
- XIVSlothCombo/Combos/JobHelpers/DRG.cs
- XIVSlothCombo/Combos/JobHelpers/MCH.cs
- XIVSlothCombo/Combos/JobHelpers/RPR.cs
- XIVSlothCombo/Combos/JobHelpers/SGE.cs
- XIVSlothCombo/Combos/JobHelpers/VPR.cs
- Fix BLM not using Thunder
- Fix DRG Not using TN + stuck on chaotic spring combo
- Fix MCH not checking everything
- Fix RPR TN
- SGE cleanup of gauges
- Fix VPR TN
> [Stuff] Various little fixes
